### ISSUE TITLE
Base is not being passed to rdflib.json_ld parser correctly

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1]
You can't pass an rdflib `Namespace` to rdflib_jsonld as a base parameter.   Line 209 in rdflib_jsonld.context.py has the following:

`                source_url = urljoin(base, source)`

`urljoin` calls `urlparse` and line 525 or urllib.parse has:
```    
    bscheme, bnetloc, bpath, bparams, bquery, bfragment = \
            urlparse(base, '', allow_fragments)
```

If `base` is a `Namespace`, everything ends up in bpath.  See:

https://gist.github.com/hsolbrig/d83d828dedcf090888871164c12f290a#file-urllib_issue-py

this means that biolinkml.utils.rdfgen needs to add a `str()` conversion around the base that gets passed in.

**Comment by sierra-moxon** [comment]
reviewing Harshad's PR in April, I think I can close this as completed.
