### ISSUE TITLE
Ifabsent uri needs to automatically be emitted as a prefix

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#10]
At the moment, [ifabsent_uri.yaml](tests/test_utils/input/ifabsent_uri.yaml) requires the `emit_prefixes` to generate python.  This should not be necessary

**Comment by sierra-moxon** [comment]
I believe that [ifabsent_uri.yaml](https://github.com/linkml/linkml/issues/tests/test_utils/input/ifabsent_uri.yaml) no longer exists.  closing as won't do.
