### ISSUE TITLE
write tests for all steps in MIXS schemasheets workflow

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1006]
especially for
- degenerate names that are tolerated by some linkml tools, but not others
- access to linkml types like date_or_datetime

EDIT:

My experience using sheets2linkml with various generators and converters in the MIxS projects:
- our tools should be more defensive, reporting states that could cause problems when used with other tools. schemasheets, gen-jsonschema and gen-linkml allow element names that don't work with the jsonschema CLI tool or common OWL/RDF tools. The linter reports these bad names, but not with enough severity.
- linkml allows names beginning with digits, that breaks jsonschema 
- schemasheets emits LinkML with names that fail during owl generation. This is especially problematics with free-text permissible values
- our tools should provide error messages that more explicitly indicate the actions that would fix the bad configuration 
- we should have documentation explain that the selection of element names in linkml has implications in the many possible generated artifacts

Semi-related... it should be possible to represent all linkml-compliant data as some kind of table 
- can't dump linkml-compliant data to SQLite if there are any slots with range `date`
- can't convert linkml-compliant data to TSV is there are any multivalued slots ???

I tend to explore issues like this in Makefiles. I could write some python tests, but I'm not sure where to put them. linkml/linkml doesn't import schemasheets, so I was thinking about making the tests in one of these:

- MIxS repo
- schemasheets repo
- something brand new

**Comment by turbomam** [comment]
Actually, I think I'm going to write these tests in either
- the MIxS repo
- a new repo

because I want to show integration of schemasheets and core linkml

**Comment by sierra-moxon** [comment]
@turbomam - if these tests are moving to those repos, can we close this issue or migrate it to another repo? :)

**Comment by turbomam** [comment]
> @turbomam - if these tests are moving to those repos, can we close this issue or migrate it to another repo? :)

will decide that week
