### ISSUE TITLE
offline access to core imports

### ISSUE THREAD

**Issue by joshmoore** [linkml/linkml#1012]
**Is your feature request related to a problem? Please describe.**

Working locally on a model which imports `linkml:types`:
```
 imports:
   - linkml:types
   - ../model
```
failed without an internet connection.

**Describe the solution you'd like**

Core imports could fall back to embedded versions when a network connection is missing.

**How important is this feature?** Select from the options below:
• [x] Low - it's an enhancement but not crucial for work
• [ ] Medium - can do work without it; but it's important (e.g. to save time or for convenience)
• [ ] Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• [ ] Short-term - 2-4 weeks
• [ ] Mid-term - 2-4 months
• [ ] Long-term - 6 months - 1 year

**Additional context**

A workaround during development is point to a git checkout of the source code:

```diff
 imports:
-  - linkml:types
+  - /src/linkml-runtime/linkml_runtime/linkml_model/model/schema/types
```

**Comment by cmungall** [comment]
Related: #502

**Comment by bastiion** [comment]
This is especially of high interest in reproducible build environments, which disallow loading external resources at build time. Take the [Nix](https://nixos.wiki/wiki/Nix_package_manager) package manager as an example (it gains a lot of traction not only within our communities).  There it is possible to load resources beforehand into the nix-store. All those resources must be hashed  for reproducibibity and pureness reasons, during the build phase nothing but the nix-store can be a source of information and data, thus, there must be some way to tell the linkml generators to work offline during transformation and use some "cached" resources from an arbitrary local directory.
