### ISSUE TITLE
Option to use 'title' instead of 'name' in the autogenerated docs

### ISSUE THREAD

**Issue by StroemPhi** [linkml/linkml#1016]
**Is your feature request related to a problem? Please describe.**
I use my LinkML model primarily for the documentation of the metadata schema within a Semantic MediaWiki (SMW) instance. The idea for the future is to build the SMW classes and properties directly from the LinkML YAML. As SMW has its very own formatting rules (e.g. capitalized classes and slots), I used the `title` metaslot of a schema element to provide a SMW compliant name. 

**Describe the solution you'd like**
I would like to be able to have the option to use the `title` instead of the name of an element in the doc generation. E.g. in the generated table of the slots of a class (as defined in [class.md.jinja2](https://github.com/linkml/linkml/blob/main/linkml/generators/docgen/class.md.jinja2)), I'd like to have the 'name' column be showing the titles of the slots as hyperlinks to them. I also would expect to do this kind of docs customization within a copy of the default Jinja templates that live in `src/docs` (related to https://github.com/linkml/linkml-project-cookiecutter/issues/10). 

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work
As I've made a workaround in my VENV adding the following method to docgen.py:
```
def link_title(self, e: Union[Definition, DefinitionName]) -> str:
    """
    Render an element as a hyperlink based on the element title
    :param e:
    :return:
    """
    if e is None:
        return 'NONE'
    if not isinstance(e, Definition):
        e = self.schemaview.get_element(e)
    if self._is_external(e):
        return self.uri_link(e)
    elif isinstance(e, ClassDefinition):
        return f'[{e.title}]({e.name}.md)'
    elif isinstance(e, EnumDefinition):
        return f'[{e.title}]({e.name}.md)'
    elif isinstance(e, SlotDefinition):
        if self.use_slot_uris:
            if e.slot_uri is not None:
                return self._markdown_link(e.slot_uri.split(":")[1])
        return f'[{e.title}]({e.name}.md)'
    elif isinstance(e, TypeDefinition):
        return f'[{e.title}]({e.name}.md)'
    else:
        return f'[{e.title}]({e.name}.md)' 
```

**When will use cases depending on this become relevant?** Select from the options below:
Now, but my as long as my workaround works, there is no direct need for me.

**Additional context**
![grafik](https://user-images.githubusercontent.com/56996739/196270874-0539bb3e-a08f-4080-827b-692cfd4fdf8e.png)

previously discussed on Slack [here](https://monarchinitiative.slack.com/archives/C01LDTVURH9/p1666011474083719).

**Comment by sierra-moxon** [comment]
From triage: 
We need to understand the difference between title and name; and document the difference as a first step to implementing the right approach.

**Comment by sujaypatil96** [comment]
You can customize your class documentation pages to have them look the way you want by defining a custom jinja template for it.

In this case you would make a copy of the base [class.md.jinja2](https://github.com/linkml/linkml/blob/main/linkml/generators/docgen/class.md.jinja2) template from the upstream linkml library, and specifically under the _Slots_ [table](https://github.com/linkml/linkml/blob/main/linkml/generators/docgen/class.md.jinja2#L52-L65) you can use something like:

```
[slot.title](gen.link(slot))
```

**Comment by sujaypatil96** [comment]
The option that you will need to use to point `gen-doc` to a folder containing custom jinja templates is `--template-directory`. More documentation about the generator can be found here: https://linkml.io/linkml/generators/markdown.html

**Comment by sujaypatil96** [comment]
Closing this issue. Feel free to reopen if you need more guidance.
