### ISSUE TITLE
`gen-linkml` does not handle imports correctly

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#1018]
When we apply gen-linkml on the [MIxS schema](https://github.com/GenomicsStandardsConsortium/mixs/blob/main/model/schema/mixs.yaml) to create one monolithic combined LinkML YAML from MIxS schemas, gen-linkml doesn't combine import schemas properly.

**Comment by cmungall** [comment]
Can you be more specific? It sounds like it does not respect `--mergeimports`? It is the case it *always* merges imports, or *never* merges them? Or something else? Can you make a small test case?

**Comment by sierra-moxon** [comment]
@turbomam @sujaypatil96  - would you be able to add a test case to this issue?  (showing how gen-linkml does not combine imports correctly for MIxS schema?   Thank you ahead of time :)

**Comment by sierra-moxon** [comment]
I found it!  just needed to get a little lower in the list. :) https://github.com/linkml/linkml/issues/969 thanks @turbomam!  Closing this one in favor of that one.
