### ISSUE TITLE
null values in json result in json schema validation error

### ISSUE THREAD

**Issue by wdduncan** [linkml/linkml#102]
We have dataset that is submitted as json, but it contains `null` values. E.g.:
```json
{
        "bin_name": "bins.1",
        "gtdbtk_domain": null,
 }
```
In the yaml, we define the bin object like this:
```json
MAG bin:
    attributes:
      bin name:
        range: string
     gtdbtk domain:
        required: false
        range: string
```
When we run the validation, we receive the error:
```
None: None is not of type 'string'
```
In the generated json schema, MAG bin is specified like so:
```json
"MAGBin": {
         "additionalProperties": false,
         "description": "",
         "properties": {
            "bin_name": {
               "type": "string"
          },
          "gtdbtk_domain": {
               "type": "string"
            }
  }
```
How can we get it also accept `null` when validating?

This discussion may be relevant: https://groups.google.com/g/jsonschema/c/mD6GDca4zN8?pli=1

cc @cmungall

**Comment by cmungall** [comment]
@wdduncan is this still an issue?

how are you validating? can you provide a test case?

**Comment by gaurav** [comment]
I think you can fix this by defining the "type" as ["string", "null"], [according to this StackOverflow answer](https://stackoverflow.com/a/16241482/27310). I'm not sure what the best way of incorporating this into LinkML would be.

**Comment by wdduncan** [comment]
@cmungall This issue looks stale. Perhaps we should close it or assign it to someone else?
