### ISSUE TITLE
indicate which class a slot is inherited from in web docs

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#1025]
In the web documentation generated from a LinkML model, for example: https://microbiomedata.github.io/nmdc-schema/, let's find the documentation for a single representative class, say, [Biosample](https://microbiomedata.github.io/nmdc-schema/Biosample/).

You'll see an _Inheritance_ column in the slots table which indicates where the slot is coming from. A feature request here is to also add information about which classes the slot is being inherited from or being mixed in from.

**Comment by amc-corey-cox** [comment]
@sujaypatil96 I'm planning to take this one if you don't mind. Here is what I have in mind:
Replace the 'inherited' text with a clickable link of the class from which the slot is inherited. Does that sound like what we'd like to see?

**Comment by cmungall** [comment]
oh i just met with @sujaypatil96 a couple of hours ago. We discussed the plan of intersecting the `domain_of` metaslot that gets injected from schemaview with the ancestors - but maybe you could handle the jinja part of it when Sujay does a PR that includes the method?

**Comment by amc-corey-cox** [comment]
Sure, or I could work on a different issue if that is better. I won't get started until later this week so let me know.

**Comment by sujaypatil96** [comment]
@cmungall and I did some basic hacking, and I probably incorrectly added the good first issue label to it because the task requires some SchemaView and LinkML core library programming expertise. I'm already halfway through this issue, so I can take this up fully if you don't mind @amc-corey-cox?

I'll tag you on a different issue that you can take up?

**Comment by amc-corey-cox** [comment]
Sure, that sounds great. Thanks!
