### ISSUE TITLE
Add a consistent version option to all linkml command line tools

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1034]
All Linkml command line tools should have a version function.

I'm looking at the the [LinkML Tutorial](https://linkml.io/linkml/intro/tutorial01.html), where one tests the install by running `linkml-convert --help`.   This creates a screenfull of stuff.  IMO, any linkml command line tools should be able to emit a short version line that includes the particular pypi version it came from as well as, perhaps, a link to its github data.  Something similar to what goes in one of the github software version badges.

**Proposal**
All functions include "-V / --version", and we create a bit of common code that formats the information.  Might even consider doing something clever with the terminal fonts and coloration :-)

**Priority**
Not essential, but would add to the consistency.

**Comment by dalito** [comment]
Related issue fo linkml: #378

**Comment by dalito** [comment]
Some tools have their own internal version info, e.g. https://github.com/linkml/linkml/blob/f899d36eb78bf00fc435413f4229dcccde50c625/linkml/generators/jsonschemagen.py#L52 - In #1052 the only linkml-version is returned.
