### ISSUE TITLE
`linkml-vallidate` emits the text "`None`" when validation is successful.

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1038]
[Part 1 of the LinkML tutorial](https://linkml.io/linkml/intro/tutorial01.html) asks you to run `linkml-validate -s personinfo.yaml data.yaml ` stating that "You should see no errors".  What you _do_ see is:
```
> linkml-validate -s personinfo.yaml data.yaml 
None
> 
```

The "None" shouldn't be there.

I would _also_ propose that we might consider some sort of summary that shows that the validator actually did its job.  This could either be a default that you could disable if you really wanted silence, or something that you called for.  We also need to decide whether, in this context, errors should go to `stdout` or `stderr`.  The summary definitely should go to `stdout`.

**Comment by sierra-moxon** [comment]
Do you think this is helpful for the linter to incorporate when pulling in the "schema validation" bits?

**Comment by pkalita-lbl** [comment]
It's kind of orthogonal, but I can keep this issue on my plate anyway
