### ISSUE TITLE
Converting to RDF in LinkML Tutorial should use the "-t" option

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1043]
The [LinkML tutorial](https://linkml.io/linkml/intro/tutorial01.html) says that you should use

`linkml-convert -s personinfo.yaml data.yaml -o data.ttl`

 to convert to RDF.  This doesn't align with what we see, and it should read:

`linkml-convert -s personinfo.yaml data.yaml -t ttl`

 instead

**Comment by cmungall** [comment]
hmm, it should be introspecting the format from the suffix - I think we have a CLI test for this behavior already?

But either way it's a good idea to be explicit in the tutorial

**Comment by hsolbrig** [comment]
the "ttl" is the output format.  The tutorial has you dump into a file and then look at the file
