### ISSUE TITLE
`tree_root` needs to be documented in LinkML tutorial step 2

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1046]
One of the key bits of the LinkML tutorial step 2 is the "tree_root" declaration. It is not touched on in the documentation.

**Comment by cmungall** [comment]
Just checking you mean this tutorial:

https://linkml.io/linkml/intro/tutorial02.html?highlight=tree_root

(not the ICBO one)

Yes, I would like to have:

- [ ] a FAQ entry
- [ ] a section here https://linkml.io/linkml/schemas/index.html
- [ ] improve the metamodel description here https://w3id.org/linkml/tree_root

**Comment by hsolbrig** [comment]
Yes - that is the tutorial I was referencing.
