### ISSUE TITLE
Need error reporting / intercept mechanism

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1058]
Prior to the creation of the linkml-runtime, `rawloader` made three steps:
1) Load the (yaml) linkml model as a dictionary
2) Pass over the dictionary adding bits and pieces (e.g. `name`) if they were missing
3) load the resulting dictionary into SchemaDefinition

The runtime now collapses this into only two steps:
1) Load the linkml model into SchemaDefinition
2) Add bits and pieces

Most of the earlier processing is already covered by the emitted python -- single entries into lists and the like.  The one thing that there _isn't_ an easy solution for is the addition of required fields, in particular `name`.  As name is defined as a key, the current LinkML implementation rejects a model outright if it isn't supplied, so we get no chance to do anything about it.

Solutions to this issue include:
1) Add an error intercept.  Instead of the simple:
```python
        if self._is_empty(self.name):
            raise ValueError("name must be supplied")
```
we could say:
```python
        if self._is_empty(self.name):
           self.MissingRequiredField("name", self.name)
```
or something similar.  The default behavior could then be the raise above, but one would also be able to correct or ignore the problem and move on.

2) Add a global flag that indicates whether validation should be done at all.

As these solutions are not mutually exclusive and the second solution would depend on an equivalent sort of code change in any case, we propose that we implement the first part immediately

**Comment by sierra-moxon** [comment]
I think is done; closing for now as such, please reopen if necessary.
