### ISSUE TITLE
jsonschema generation should generate additionalProperties: false for enclosing properties

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#106]
we correctly generate

         "additionalProperties": false,

for each class

but we should also do this on the enclosing object

**Comment by wdduncan** [comment]
@hrshdhgd @cmungall just pinging you again on this ... I have to use `jq` to add the global restriction.   

For example see the [Makefile](https://github.com/microbiomedata/nmdc-schema/blob/12e96f68ca3c0e796614efcec35b02cfdc9ddb46/Makefile#L76) in the nmdc-schema repo.

**Comment by cmungall** [comment]
Hi Bill, I think you meant to ping Harold, not Harshad. Would you be able to make a PR to do this yourself?

**Comment by wdduncan** [comment]
Hah! Yes, I did. Sorry @hrshdhgd ... I can try to make a PR. I may need @hsolbrig help with some details :)

**Comment by cmungall** [comment]
We should parameterize this at two levels

 1. global, at the level of jsonschemagen cli
 2. at the class level

That will allow the schema developer to determine whether the slot list is open or closed

I suggest doing 1 straight away, we can open a new ticket for 2 as this will require a model extension
