### ISSUE TITLE
update CONTRIBUTING guidelines to provide development environment testing instructions

### ISSUE THREAD

**Issue by dalito** [linkml/linkml#1064]
`CONTRIBUTING.md` which was updated in linkml/linkml-runtime#85 mentions that linkml-runtime uses pytest as test framework. 

Curently it is not a dev-dependency in `pyproject.toml`. Should it be one? CI also still uses unittest.

**Comment by sujaypatil96** [comment]
Stick to Python unittest for now.

Wait for future updates to testing framework from @hsolbrig

**Comment by sujaypatil96** [comment]
Thank you for the suggestion @dalito.

The `CONTRIBUTING.md` doc needs some updating with new compact make commands that come for free with the cookicutter setup. This issue can be repurposed for a `CONTRIBUTING.md` guidelines update.

**Comment by dalito** [comment]
CONTRIBUTING.md now links to the respective section in the docs which were also improved. Also LinkML switched to `pytest` recently so the inconsistency I stumbled upon is gone. So I am closing this.
