### ISSUE TITLE
Namespaces test for complete URI fails

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1067]
The rdflib 6.0 release has changed the semantics of `__contains__` for the Namespace class.  According to https://github.com/RDFLib/rdflib/blob/e9fea549fd8f325415ca6c5a787e2b8d2a23b85a/rdflib/namespace/__init__.py#L131, "in" is now defined as "Allows to check if a URI is within (starts with) this Namespace." 

Something of the form:

   `':/' in uri`  

no longer returns `True`.  As we are going to assume that changes to namespace itself will break things, a backwards compatible fix appears to be to change the above to `':/' in str(uri)`.  Note that we have to find both `in` and `not in` references.

**Comment by nlharris** [comment]
Seems like this is probably now fixed?

**Comment by sierra-moxon** [comment]
this is likely fixed now; we are working with this.
