### ISSUE TITLE
`EnumDefinition.permissible_values` can contain duplicate `PermissibleValue` entries

### ISSUE THREAD

**Issue by joeflack4** [linkml/linkml#1068]
## Description of issue experienced
Gaurav noticed duplicates when testing out the enumerations endpoint.
Example: https://terminology.ccdh.io/enumerations/CRDC-H.Treatment.treatment_effect?value_only=true

## Related issues
Original issue: https://github.com/cancerDHC/ccdh-terminology-service/issues/27 

## Possible solution
While I can dedupe in the terminology service, and am doing so, I am thinking that the best place to do this deduping is probably in the YAMLDumper (if not somewhere higher up in the abstraction chain). 

The class right now is pretty light:
```python
class YAMLDumper(Dumper):

    def dumps(self, element: YAMLRoot, **kwargs) -> str:
        """ Return element formatted as a YAML string """
        return yaml.dump(remove_empty_items(element, hide_protected_keys=True),
                                            Dumper=yaml.SafeDumper, sort_keys=False, **kwargs)
```

You can see the deduping I have in mind as pseudocode in the [terminology service GitHub issue](https://github.com/cancerDHC/ccdh-terminology-service/issues/27 ).

## Discussion
@cmungall I marked this as a "bug" and put it under the project "Generation of APIs..." since it has an effect on our APIs. I'm considering you the steward of LinkML, so I'm wondering if you agree with my approach. If so, this should not be difficult for me to do.

**Comment by sierra-moxon** [comment]
@joeflack4 - does Chris's solution work for you?  If so, could you please close this issue? thank you :)

**Comment by joeflack4** [comment]
Hey @sierra-moxon . Gosh, it's been a year since I looked at this one. I see that I intended to fix something; I think this was in the CCDH Terminology Service code, which I would have fixed. It looks like Chris expects that an error should be thrown by LinkML when there are duplicate permissible values, so I think that fix still needs to be added to LinkML (unless it's been done already).
