### ISSUE TITLE
Decimal type needs to emit JSON-Schema number 

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#107]
Line 68 in jsonschemagen has:
```python
 # translate to json-schema builtins
        if rng == 'int':
            rng = 'integer'
        elif rng == 'Bool':
            rng = 'boolean'
        elif rng == 'str':
            rng = 'string'
        elif rng == 'float' or rng == 'double':
            rng = 'number'
        elif not rng.startswith('#'):
            # URIorCURIE, etc
            rng = 'string'
```

In the short term we need to add "decimal" (case?) to the number range.

In the longer term, we need to consider adding the JSON Schema type as a part of the type definition itself(???)

**Comment by sierra-moxon** [comment]
I believe this issue is closeable as already fixed; please of course reopen if I got this wrong.
