### ISSUE TITLE
Enable `load_schema_wrap()` to accept URL to schema

### ISSUE THREAD

**Issue by cthoyt** [linkml/linkml#1073]
## Problem

The `load_schema_wrap()` function
https://github.com/linkml/linkml-runtime/blob/775369806ea1fde4d853719c4bcbfe44bb4f046c/linkml_runtime/utils/schemaview.py#L53-L60

which is transitively used in the `SchemaView.__init__()`

https://github.com/linkml/linkml-runtime/blob/775369806ea1fde4d853719c4bcbfe44bb4f046c/linkml_runtime/utils/schemaview.py#L101-L108

only accepts a path, and not a URL. This means that a repository built on top of a given schema needs to make a copy of that schema. For example, the SSSOM schema is canonically defined in https://github.com/mapping-commons/sssom then mirrored in https://github.com/mapping-commons/sssom-py. For various technical reasons, the PR https://github.com/mapping-commons/sssom-py/pull/182/files proposes to introduce a _second_ copy of the schema in the repository just so it's available for a single wrapper around the LinkML RDF writer function.

## Proposed Solution

It would make much more sense to have a PURL here that points to a specific version of the schema (e.g., on a github tag) than to have to do this round-about importing, which hugely decouples updating the schema from the package itself. The `load_schema_wrap()` function could accept a URL that it would be responsible for grabbing (perhaps even storing locally using something like [`pystow`](https://github.com/cthoyt/pystow) so it doesn't need to make a request every time)

**Comment by sujaypatil96** [comment]
@sierra-moxon has tested loading schemas using raw URLs in biolink project and it works.

@cthoyt can you check if this is still an issue for you? If it works could you please close it?

**Comment by cthoyt** [comment]
@sujaypatil96 can you point to a commit where this code was updated to enable the desired functionality?

**Comment by turbomam** [comment]
Hi, @cthoyt. I don't think I have ever used `load_schema_wrap` directly, but `SchemaView`s can definitely be instantiated with a url argument. I do that all the time.

for example 

```python
from linkml_runtime import SchemaView

meta_url = "https://w3id.org/linkml/meta.yaml"
meta_view = SchemaView(meta_url)
print(meta_view.schema.name)
```

Does that address your issue? Glad to chat more if necessary.
