### ISSUE TITLE
Make needs filters to prevent metadata dates from creating extraneous updates

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1077]
The output from the generators includes dates and times.  biolinkml filtered those changes out when it did the updates in the test runner.  We need to add an intelligent copy function in make to prevent "gratuitous" metadata changes from updating the repository.

(I think that there is a comparison command line tool in (bio)linkml that at one point in time did exactly this

**Comment by pkalita-lbl** [comment]
The current recommendation is to use the `snapshot` [test fixture](https://github.com/linkml/linkml/blob/fbeaba787d90dc9dc0b8ebc69d677a8465dbc159/tests/conftest.py#L120-L146) which automatically handles this type of metadata.
