### ISSUE TITLE
Need a type identifier field

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#108]
At the moment, the loaders have to have outside knowledge of a model instance type in order to start the loading process.  We need the ability to supply the type _within_ an instance that tells the loader what a YAML/RDF/JSON/ ... represents.

This is needed both for loaders that don't have a single root in the model (SchemaDefinition is the single root for LinkML) and whenever we get a choice implemented in range.

Before proceeding it would be worth discussing what we should call this.  `type` seems too general `resourceType` too specific.... (see JSON-LD for other naming possibilities)

**Comment by cmungall** [comment]
linkml:tree_root should do it?

**Comment by nlharris** [comment]
Is this resolved?

**Comment by cmungall** [comment]
We have `tree_root` to indicate the top level, and `type_designator` for arbitrary types
