### ISSUE TITLE
Upper casing defined data types is confusing

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#1081]
Having the datatypes appear upper cased (first letter), is confusing. I want to simply copy values from the index page into my model, and I kept getting errors that `Uriorcurie` does not exist (should have been `uriorcurie`)..

![image](https://user-images.githubusercontent.com/7070631/134580851-3084252d-8814-4a19-b10f-4c2e3e997222.png)

**Comment by sierra-moxon** [comment]
Hi @matentzn - I am going to close this ticket with Chris's addition of the documentation, but please do feel free to reopen if its unsatisfactory :).  Trying hard to triage the issues here, but sometimes I get it wrong. :)
