### ISSUE TITLE
Anything we should add to linkml-tutorial repo from the ICBO workshop?

### ISSUE THREAD

**Issue by nlharris** [linkml/linkml#1097]
This slide presentation was made for the LinkML workshop at ICBO 2022:
https://docs.google.com/presentation/d/1U1acY1czwWt8KlwrCjY_zE_2eg6sV6BC9D0T5xcs1Zo/edit

Should we link to it from this documentation site? Or incorporate any of the figures into this documentation?

**Comment by dalito** [comment]
This https://github.com/linkml/linkml-tutorial/issues/14 is somewhat related. Based on the video the windows users had some trouble following.

**Comment by nlharris** [comment]
I I think https://github.com/linkml/linkml/pull/2245 will satisfy this request
