### ISSUE TITLE
Question concerning is_a inheritance, designates_type metamodel slot usage

### ISSUE THREAD

**Issue by j-simmons-phd** [linkml/linkml#1099]
If I have a schema like the one shown in https://linkml.io/linkml/intro/tutorial07.html#inheritance where `Person` and `Organization` both inherit from `NamedThing`, can I create a multivalued slot `things` with Range of `NamedThing` and add `Person` and `Organization` objects to the slot `things`?  Something like this:

```
# schema addition
Container:
    tree_root: true
    attributes:
      things:
        multivalued: true
        inlined_as_list: true
        range: NamedThing
```
```
# data file
things:
  - id: ORCID:1234
    full_name: Superman
    has_organizational_relationships:
      - related_to: ROR:1
        relationship_type: MEMBER_OF
  - id: ROR:1
    full_name: Justice League
```

I tried a version of this with one of my own schemas and got a validation error about one of the additional slots being unknown when I tried to create one of the subclasses as an item in the list (e.g. has_organizational_relationships).  Error message below.  Note, not all of this code is committed yet.  

If this sounds like something that *should* work I can refile this as a bug with fully committed code backing it up. 

```
[~/Repos/m30ml]$ linkml-validate -s dist/m30ml.yaml src/data/examples/009-MixedElements.yaml 
Traceback (most recent call last):
  File "/usr/local/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/linkml/validators/jsonschemavalidator.py", line 114, in cli
    obj = loader.load(source=input, target_class=py_target_class, **inargs)
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/loaders/loader_root.py", line 85, in load
    results = self.load_any(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/loaders/yaml_loader.py", line 25, in load_any
    return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/loaders/loader_root.py", line 66, in load_source
    return target_class(**data_as_dict)
  File "<string>", line 8, in __init__
  File "test", line 123, in __post_init__
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/utils/yamlutils.py", line 97, in _normalize_inlined_as_list
    self._normalize_inlined(slot_name, slot_type, key_name, keyed, True)
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/utils/yamlutils.py", line 182, in _normalize_inlined
    cooked_obj = slot_type(**as_dict(list_entry))
  File "<string>", line 7, in __init__
  File "test", line 91, in __post_init__
  File "/usr/local/lib/python3.8/dist-packages/linkml_runtime/utils/yamlutils.py", line 48, in __post_init__
    raise ValueError('\n'.join(messages))
ValueError: File "<file>", line 7, col 5:  Unknown argument: color = 'red'
```

**Comment by cmungall** [comment]
Great question, thanks!

This is definitely a use case we want to support. The challenge is that when serializing to json/yaml(*) from Python, by default you lose the typing information. There is no way for a deserializer to know ROR:1 is an organization.

The solution here is to introduce a `designates_type` slot.

See:

 - #1008 

cc @joshmoore, are you still interested in working on a PR for this?

**Comment by joshmoore** [comment]
This temporarily moved to my backburner, @cmungall (my ring buffer filled up), but it will be coming back around. Happy to discuss more concrete next steps, though I felt as if I was _close_ to a solution that wouldn't need `designates_type` (at least for my particular use case).

**Comment by j-simmons-phd** [comment]
Thanks @cmungall for the quick reply.  The project that triggered my posting of this issue is one I am working on with @capsulecorplab.  We are both interested in assisting with the `designates_type` slot approach from #945.  How can we best get started?

**Comment by kervel** [comment]
hello, i'm trying to do the same.

i have this (only relevant part included) linkml model, where a `LocatedNetEntity` can have multiple locations, all inheriting from BaseLocation:

```yaml
  BaseLocation:
    description: >-
      A RSM base location
    is_a: BaseObject
    class_uri: RSM:#EAID_5CC96D2F_0D85_427c_8DC1_668074F7EE1A
    attributes:
      baseLocationKind:
        range: string
        designates_type: true

  LinearLocation:
    is_a: BaseLocation
    description: >-
      Linear Location

  AreaLocation:
    is_a: BaseLocation
    description: >-
      Area Location

  SpotLocation:
    is_a: BaseLocation
    description: >-
      Spot Location
    attributes:
      - associatedNetElements:
          multivalued: true
          range: AssociatedNetElement
          slot_uri: RSM:#EAID_D025945C_27E7_4b73_87D4_3BB8A647B836
          inlined: true
      - coordinates:
          multivalued: true
          inlined: true
          range: GeometricCoordinate
          any_of:
            - range: GeographicCoordinate
            - range: CartesianCoordinate
            - range: LinearCoordinate

  LocatedNetEntity:
    description: >-
      A located net entity
    is_a: NetEntity
    class_uri: RSM:#EAID_55DDBCD9_DA3C_4baf_8CBF_21BD9481BE3C
    attributes:
      - locations:
          slot_uri: RSM:EAID_43382C11_960E_40e0_B6E0_198963C97DF8
          inlined_as_list: true
          range: BaseLocation
          multivalued: true
          any_of:
            - range: LinearLocation
            - range: SpotLocation
            - range: AreaLoccation
```
i tried the standard cruft/cookiecutter template, which includes a standard test, which uses the yaml_loader. My data looks as follows:

```yaml
# Example data object
id: http://some/52ce9b66-e843-4544-9040-55b834f50e0b
name: A1223
refersToLocatedNetEntity:
  name: A1223
  locations:
    - baseLocationKind: test:SpotLocation
```

the loader doesn't seem to use the `baseLocationKind` to determine that it should create a SpotLocation instead of a BaseLocation (if i look at the object created, there is still a BaseLocation)

i'm at a loss a bit now, no idea what i'm doing wrong.

**Comment by samwalrus** [comment]
I would also like to be able to do this.
I do not follow how to use a 'designates_type' slot, that Chris mentions as a solution.

**Comment by kervel** [comment]
In the original example, both Person and Organisation inherit from NamedThing, so when loading an element from the list, one needs to know whether this item is a Person or an Organisation. this can be done in two ways:

* using a type designator: there is a field that has the type of the thing, so just looking up this field is enough
* using validation (pydantic can do this, but the pydantic generator doesn't emit the necessary info yet): basically, it tries first to convert the json in a Person, and if that doesn't work, it tries an Organisation in stead.

for me the type designator is the more robust approach, because the validation based approach would fail if a Person and an Organisation happen to have the same set of attributes.

The PR i did uses the type designator to do that (in the PR i linked a closed pydantic issue that shows how pydantic can use type designators for polymorphic loading).

**Comment by samwalrus** [comment]
So with your PR version would this be the right way to write a schema and data:

https://gist.github.com/samwalrus/494d6f01e4bc8d2daf4067e280679310 

So that it would pass the validator ?

**Comment by kervel** [comment]
hello @samwalrus
i tried your example and the result is not too good yet https://gist.github.com/kervel/5591569829abf640dea839204398efcd

as you can see the type annotations for the list in the collection don't make sense at all
not sure why. I think `inlined_as_list` is still buggy. If i try `inlined` instead it makes more sense.

```python
class Container(ConfiguredBaseModel):
    
    things: Optional[Dict[str, Union[NamedThing,Person,Organisation]]] = Field(default_factory=dict)
```

**Comment by kervel** [comment]
i updated my PR. now the output is:

```shell
class Container(ConfiguredBaseModel):
    
    things: Optional[List[Union[NamedThing,Person,Organisation]]] = Field(default_factory=list)

```

i added the following line:
```
print(Container.parse_file("data.json"))
```

and then i created `data.json` as 
```
{
  "things": [
    {
      "id": 1,
      "type": "http://example.org/test-schema/:Person",
      "full_name": "phoebe",
      "height": 10
    },
    {
      "id": 2,
      "type": "http://example.org/test-schema/:Organisation",
      "full_name": "University of Earth",
      "number_of_employees": 2
    }
  ]
}
```

the output i got was
```
things=[Person(id='1', full_name='phoebe', type='http://example.org/test-schema/:Person', height=10), Organisation(id='2', full_name='University of Earth', type='http://example.org/test-schema/:Organisation', number_of_employees=2)]
```

so i guess that's what one wants. the URIs however are weird (what is the `:`  doing there?). i would expect the type designators to be ```http://example.org/test-schema/Person``` , so something still goes wrong with curie expansion.

**Comment by kervel** [comment]
another update: i tried to create python dataclasses support [here](https://github.com/Kapernikov/linkml/tree/polymorphism_dataclasses)

it generates a __new__ function that instantiates a subtype based on the type designator.
but, not there yet. linkml-validator also uses json schema which also misses support for this :-(

```python
@dataclass
class NamedThing(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = TEST.NamedThing
    class_class_curie: ClassVar[str] = "test:NamedThing"
    class_name: ClassVar[str] = "NamedThing"
    class_model_uri: ClassVar[URIRef] = TEST.NamedThing

    id: Union[str, NamedThingId] = None
    full_name: Optional[str] = None
    type: Optional[str] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self._is_empty(self.id):
            self.MissingRequiredField("id")
        if not isinstance(self.id, NamedThingId):
            self.id = NamedThingId(self.id)

        if self.full_name is not None and not isinstance(self.full_name, str):
            self.full_name = str(self.full_name)

        self.type = "http://example.org/test-schema/NamedThing"

        super().__post_init__(**kwargs)


    def __new__(cls, *args, **kwargs):
        mappings_type = {
            "http://example.org/test-schema/NamedThing": NamedThing,
            "http://example.org/test-schema/Person": Person,
            "http://example.org/test-schema/Organisation": Organisation,
        }

        type_designator = "type"
        if not type_designator in kwargs:
            return super().__new__(cls,*args,**kwargs)
        else:
            return super().__new__(mappings_type[kwargs[type_designator]],*args,**kwargs)
```

**Comment by cmungall** [comment]
Once #1617 is merged we will have support for type designators in dc, pydantic, jsonschema
