### ISSUE TITLE
Integrate biothings explorer generator code

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#11]
Talking with @newgene 

@kevinxin90 wrote some nice code for converting the bilinkml yaml to the CD2H format, biolink-model here:

http://discovery.biothings.io/bts/

This is nice! We could link this from the main biolink-model site

Would be good to explore integration of code. I think Kevin used the yaml directly and didn't use the biolinkml framework. I also think he hardcoded some filtering, e.g associations don't show up.

It looks like Kevin is missing quite a bit, e.g. http://discovery.biothings.io/bts/ProteinIsoform doesn't show inherited mixins - this is why it's good to use the biolinkml python framework rather than trying to figure the yaml semantics for yourself!!

**Comment by cmungall** [comment]
Hi @kevinxin90 and @newgene

We would be interested in discussing your needs further

You may be interested in the new docs https://linkml.io/linkml/

See the developer docs for use of schemaview

**Comment by newgene** [comment]
@cmungall @hsolbrig certainly! DDE (https://discovery.biothings.io) can consume a schema.org style schema definition file. If you already have a schema.org format output for biolinkml, we can register the correct schema file, so it will be updated automatically. 

I believe @kevinxin90 previously create a schema.org file based on an old snapshot of the biolink model.

Also the correct example URL should be https://discovery.biothings.io/view/bts/ProteinIsoform

**Comment by nlharris** [comment]
Sierra and I assume this is now obsolete. Please reopen if needed.
