### ISSUE TITLE
`linkml-lint` not included in docker image pulled from dockerhub

### ISSUE THREAD

**Issue by capsulecorplab** [linkml/linkml#1101]
**Describe the bug**
`linkml-lint` service doesn't appear to be included in the [linkml docker image published on dockerhub](https://hub.docker.com/r/linkml/linkml)

See https://github.com/Mach30/m30ml/actions/runs/3441020405/jobs/5740127918#step:3:68

**To Reproduce**
1. run `docker run  -v $PWD:/work -w /work -ti linkml/linkml linkml-lint --help`
2. See error

**Expected behavior**
Should print a help text

**Additional context**
It appears `linkml-lint` was added [Aug 16, 2022](https://github.com/linkml/linkml/commit/c572e5049b3c95bdc788898dad9e72a2696ebcde), but the last docker image was published [Jul 6, 2022](https://hub.docker.com/layers/linkml/linkml/latest/images/sha256-7b16f6618608ce2f57fe789b85e378cbf7aa04bca7978622788c95601e9eab37?context=explore); i.e., a more recent version of the docker image just needs to be built and published on dockerhub

**Comment by cmungall** [comment]
There is a 1.3.9 up on Dockerhub now: https://hub.docker.com/r/linkml/linkml/tags

This includes linkml-lint

I made an issue to auto-release to dockerhub so we don't end up trailing behind again:

- https://github.com/linkml/linkml/issues/1102
