### ISSUE TITLE
Add association link to mermaid diagram

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#1116]
Currently, the only relationship highlighted in the mermaid diagram is the `is_a` relationship. We have the mermaid diagram wishlist here #931.

We can start by adding the [association](https://www.uml-diagrams.org/association.html) relationship for a class, that _associates_ a class with other classes and slots.

Previously, the yumlgen module produced association relationships for a class in consideration and other elements in the following manner:
* class in consideration and other classes in the `domain_of` slots related to the class in consideration
* mixins used in the class
* classes that use the class in consideration as a mixin
* children
* parents

Can we highlight other use cases that I might have missed?

CC: @cmungall @sierra-moxon @turbomam

**Comment by sujaypatil96** [comment]
Thank you for the guidance on this issue @cmungall.

Awesome, that sounds like a great first step to adding the `association` UML relationship to the mermaid diagrams.

For the benefit of readers, the workflow to adding this feature will be:
* look through global `slots` declarations to see if a class is asserted in the range of any of those slots
* look through `attributes` of a class to see any attributes have the class in their range
* look through `slot_usage` modifications of a slot on the class in consideration to see if they assert the given class in their range

**Comment by sujaypatil96** [comment]
Nit: note issue created by @hsolbrig on mermaid issue tracker https://github.com/mermaid-js/mermaid/issues/3816

**Comment by sujaypatil96** [comment]
To start work on this issue, follow below workflow:

* Look at yumlgen.py code for reference, https://github.com/linkml/linkml/blob/main/linkml/generators/yumlgen.py#L178-L197
* Loop through all slots and check if domain of slot is the class under consideration, and the range of the slot is a class
  * use [class_slots()](https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/utils/schemaview.py#L1003) for this
* For all the filtered slots, draw an association arrow between them using appropriate mermaid syntax for an association relationship

Note: make sure to check that the range class has not already been generated

**Comment by hsolbrig** [comment]
Note: yumlgen adds cardinality to inline slots and some decorators ("(i)" for inherited as an example).  We need to:
1) See how mermaid handles inline cardinality "age: int[0..*]" as well as whether it will support some sort of non-uml decorators.  If not, discuss what to do instead.

**Comment by amc-corey-cox** [comment]
I just wanted to mention that I have not started any work on this issue. I have briefly discussed doing so with Sujay but I'm working on a different issue first. I'll hold this in my Projects cue to work on next if someone doesn't get to it first.

**Comment by turbomam** [comment]
Lert's revisit this issue with mermaid

**Comment by sujaypatil96** [comment]
Addressed by PR #1327
