### ISSUE TITLE
`linkml-ws` not generating a project scaffold

### ISSUE THREAD

**Issue by capsulecorplab** [linkml/linkml#1117]
**Describe the bug**
Generating a project scaffold, s.a., using `linkml-ws new pizza-ontology` yields an error in linkml v1.3.13

**To reproduce**
1. `pip install linkml`
2. `linkml-ws new pizza-ontology`

**Expected behavior**
Should generate a project scaffold without errors

**Screenshots**

![Screenshot from 2022-11-18 09-32-55](https://user-images.githubusercontent.com/14095576/202755573-54c46985-74ee-4136-afe0-6591b2e3a6c1.png)

**About your computer (if applicable, please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
Also tested in v1.3.3 and v1.3.8. Seemed to work in v1.3.3, but encountered the aforementioned issue in v1.3.8

**Comment by capsulecorplab** [comment]
Thanks, @sierra-moxon, I'll give the cookiecutter template a try. Though, unless the `linkml-ws` tool itself is being deprecated, I feel like this issue should be kept open until the error itself is resolved.

As a linkml user, I'd also add I personally find more utility being able to work natively in the command line, being that much of the toolchain (s.a., the validators and generators) are also command line based, rather than having to switch over to a web-based solution.

**Comment by capsulecorplab** [comment]
So, I got the cookie cutter approach to work, but it took me far more steps (including having to update my local python version) than I would've preferred. While I can see the approach probably encourages decent devops practices (s.a., using a virtual environment and a projects folder configured with a pyproject.toml - though, this is the first time I've seen the latter), it seems a bit abrasive just for generating a project scaffold.

**Comment by sierra-moxon** [comment]
Hi @capsulecorplab - we have archived linkml-project-template (and we have stopped development on linkml-ws).  We are focusing on the cookie-cutter template.  Beyond the devops reasons you list above, we also like the integration of 'cruft' which allows users of the template to keep up with changes with a simple `cruft update` command.

**Comment by sierra-moxon** [comment]
documentation update ticket: https://github.com/linkml/linkml/issues/1129

**Comment by capsulecorplab** [comment]
@sierra-moxon Got it. Thanks for the update! (And apologies for all the noise). Will focus on using the cookiecutter template for generating any project scaffolds moving forward~
