### ISSUE TITLE
"see also" metamodel component should be promoted to the top of the documentation page and hyperlinked to its value.

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#112]
It would be good to see the seeAlsos higher up on the page than tucked on the bottom, also hyperlinked

E.g.

https://cmungall.github.io/knowledge-graph-change-language/Unobsoletion/

this is buried:

  |   |  
-- | -- | --
See also: |   | http://wiki.geneontology.org/index.php/Restoring_an_Obsolete_Ontology_Term

**Comment by joeflack4** [comment]
I'll keep this one open for now, but added to: #245

**Comment by sujaypatil96** [comment]
Similar functionality needs to be propagated into docgen as well. PR coming up soon.
