### ISSUE TITLE
Minor copy/paste error in specification

### ISSUE THREAD

**Issue by vincentvialard** [linkml/linkml#1123]
In the [Analogies to other modeling frameworks](https://linkml.io/linkml-model/docs/specification/03schemas/#analogies-to-other-modeling-frameworks) section, the second "EnumDefinitions are analogous to:" bullet point should be "TypeDefinitions are analogous to:"

**Comment by nlharris** [comment]
I was going to try to fix this, but I find three different files that have the same text found on the [Analogies to other modeling frameworks](https://linkml.io/linkml-model/docs/specification/03schemas/#analogies-to-other-modeling-frameworks) page:
https://github.com/search?q=%22think+about+analogous+structures+in+other+frameworks%22&type=code
Not sure which one to fix (maybe some pages are generated from one of the others?).

**Comment by vincentvialard** [comment]
The markdown file must be the source here: https://github.com/linkml/linkml-model/blob/eea96aba18121ca14d8b43b10962c144035030db/specification/03schemas.md

**Comment by vincentvialard** [comment]
Will fix this and make a PR.

**Comment by vincentvialard** [comment]
Fixed with PR https://github.com/linkml/linkml-model/pull/133
