### ISSUE TITLE
Minor typo in the description of the rule for derived attributes in the specification

### ISSUE THREAD

**Issue by vincentvialard** [linkml/linkml#1125]
In the [Rule: Derived Attributes](https://linkml.io/linkml-model/docs/specification/04derived-schemas/#rule-derived-attributes) section of the specification the slotname is missing:

> Derived attributes can be calculated for every *applicable* slot name for any class `c`

should be:

> Derived attributes can be calculated for every *applicable* slot name `s` for any class `c`

**Comment by nlharris** [comment]
Thanks for reporting this, Vincent. If you see typos, please go ahead and make a pull request to fix them -- probably less effort overall than making an issue!

**Comment by vincentvialard** [comment]
Will do!

**Comment by vincentvialard** [comment]
Fixed with PR https://github.com/linkml/linkml-model/pull/133
