### ISSUE TITLE
Add command line tool: linkml-schema-validate

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1148]
Currently we get schema validation indirectly, whenever any command in the gen-X suite is executed, but it would be good to have a more direct command, `linkml-schema-validate`

This would be a convenience wrapper for running `linkml-validate` on the schema, using the version of the metamodel distributed with linkml-runtime (there could be an option for passing an explicit metamodel version but then this becomes nearly identical to the generic linkml-validate)

We may still want to include some of the procedural checks that are performed by SchemaLoader right now, but ultimately these should all be translated to declarative form in the metamodel.

**Comment by pkalita-lbl** [comment]
I could see this being part of the `linkml-lint` command. It already sort of does it, but it only gives a very generic "not a valid schema" message when the schema doesn't conform to the metamodel. I could see:

1. Doing a better job at getting informative messages about why the schema doesn't conform
2. Adding an option like `--validate-only` to the `linkml-lint` CLI for users who don't care about the stylistic rules
