### ISSUE TITLE
w3id and purl correct set up to point at my linkml generated data.

### ISSUE THREAD

**Issue by samwalrus** [linkml/linkml#1149]
When I set up my linkml cookie cutter it made a w3id.
I was not sure exactly how to set this up and if I needed to have https for my lod server. I did follow the instruction to send an email to [public-perma-id@w3.org](http://lists.w3.org/Archives/Public/public-perma-id/) but I dont think that has been set up yet.
Meanwhile I have tried using a purl set up.
I changed my linkml schema and remade my rdf, I then set up a purl to go from
`http://purl.org/alspac/alspac-data-catalogue-schema/`  to `http://samneaves.ddns.net/rdf`
I have set a lod server to serve my rdf at `http://samneaves.ddns.net/rdf`.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/3585702/205112796-4e09af82-2b21-4821-9ff1-042292875874.png">

But it seems I need to set up a redirect for every resource with purl rather than it redirect everything to the correct location?

So
`http://purl.org/alspac/alspac-data-catalogue-schema/ge_ht12_g1` goes to `http://samneaves.ddns.net/rdf/ge_ht12_g1 `because I have made an explicit rule, but  `http://purl.org/alspac/alspac-data-catalogue-schema/ge_ht12_g1_2015-11-02` does not go to `http://samneaves.ddns.net/rdf/ge_ht12_g1_2015-11-02`. Is this right ? How should these things be set up? 

(This is cross posted from https://swi-prolog.discourse.group/t/setting-up-cliopatria-docker-as-lod-server-with-w3id/5982/3) 
Thanks for any help here.

**Comment by turbomam** [comment]
Wow, great progress.

What do you mean by 

> When I set up my linkml cookie cutter it made a w3id.

I think the extent of w3id integration is just suggesting an expansion for you default prefix. That doesn't mean that the prefix has been reserved in the w3id system, or that any redirection rules have been created there.

That means that you can use any persistent web-based ID resolver that you want, and only have to update the prefix expansion in your schema to match the purl system you have chosen.

**Comment by samwalrus** [comment]
Yes that what I thought, so I have tried to set up the redirect by emailing [public-perma-id@w3.org](http://lists.w3.org/Archives/Public/public-perma-id/) asking them to put a redirect in place as mentioned at https://w3id.org/ instead of writing the .htaccess file and sending a git pull as I am not familiar with these and because at the moment my server is serving http rather than https I was not sure if it would work.  I understand the idea behind the redirect/purl services but not the practical step of getting them to work, what different services are available and the benefits drawback of each one. The purl one seems to kind of work but it is not practical to have to set up a redirect for every entity in my graphs? I feel like I am missing a * option..

**Comment by samwalrus** [comment]
Thanks I will carry on experimenting with wid3 but for now I have got it working with purl by setting the type to 'partial'.  See https://purl.archive.org/help this was also helpful http://bibpurl.oclc.org/faq.html
