### ISSUE TITLE
Join the LinkML community channel!

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1164]
To join go to
https://obofoundry.org/

click on participate to join the OBO workspace, where you will find #linkml-community

**Comment by samwalrus** [comment]
I was not able to join the workspace not sure if it is meant to be open for anyone?  "xxx doesn’t have an account on this workspace."

**Comment by nlharris** [comment]
@samwalrus, I think you need to create an account in that Slack workspace, but anyone should be able to do so. I tried going to https://obo-communitygroup.slack.com/ in an incognito window and got

> Sign in to obo-community
> [Sign in with Google]
> [Sign in with Apple]
> OR
> name@work-email.com

You'll need to create an account (via one of those mechanisms) even if you have accounts in other Slack workspaces -- they're all separate.

**Comment by samwalrus** [comment]
It does not give me an option to create an account.  I try and sign in and I get an error for not having an account. If I try google I get:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/3585702/208541226-5e019c67-cbc3-4464-a3a2-7d6cdce20b79.png">

And if I try using sign in with email option. It asks for a magic code but the email I get simply says:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/3585702/208541376-845d565f-2e69-4d5c-b168-cf538a33b432.png">

**Comment by nlharris** [comment]
Ok, I see what you mean: it's a sign-in page, not a sign-up page.

And if I try going to https://obo-communitygroup.slack.com/signup, it says "This team's administrator has not enabled email signups.
Ask your administrator to send you an invitation."

@matentzn how have you enabled previous people to join the workspace? Did you explicitly send them an invitation? We can of course send an invitation to sam.neaves@gmail, but I'm wondering how we want to configure workspace registration moving forward.

**Comment by matentzn** [comment]
@nlharris you are a workspace owner - feel free to change the setting to sign up! I still think there should be some kind of review for new sign ups, and I don't even know if slack free edition even allows them.

**Comment by nlharris** [comment]
@samwalrus I sent you an invitation to join.
Re "click on participate to join the OBO workspace", we should clarify that what you need to do is ask the Slack admins to invite you. I guess you can do that by asking in this ticket (or creating a new one).

**Comment by dalito** [comment]
The slack page says "Ask your administrator to send you an invitation." - but there is no email or contact form. Sam posted his email address here but not everyone likes to do this.

**Comment by nlharris** [comment]
True. @matentzn how has this been handled in the past?

**Comment by matentzn** [comment]
It has never been properly handled!

**Comment by cmungall** [comment]
So we now have a route for this, people join the mail list first

we can close this issue when we add links to these docs:

https://linkml.io/linkml/contributing/contributing.html
https://linkml.io/linkml/faq/contributing.html

**Comment by ml-evs** [comment]
Could I grab an invite to the slack too (slack@ml-evs.science)? I joined the OBO mailing list expecting to get an invite as a welcome, but would rather spam this small subset of people than the whole list 😁 

In case it is useful, you can now create Slack invite links that never expire via the desktop app [maybe also web] This comes with its own dangers, I guess...

**Comment by nlharris** [comment]
@ml-evs thanks for the nudge! I created a permanent Slack invite link and added it in PR #1289. I also directly invited you to the channel.
