### ISSUE TITLE
Documentation of linkml-model not rebuilt after last release

### ISSUE THREAD

**Issue by dalito** [linkml/linkml#1165]
The [generated linkml-model documentation](https://linkml.io/linkml-model/docs/) is outdated. The doc-build seems to be triggered only if the docs change but not for a new release tag. The build failed after the last change, see https://github.com/linkml/linkml-model/actions/runs/3493410175 so the documentation is still the old one.

I recognized this because the [fix in linkml-model #130](https://github.com/linkml/linkml-model/pull/130) is still not in the docs after the new Release v1.3.1.

When trying to figure out if the docs are up-to-date, I also looked for a version number but did not see one. It seems to be missing.

**Comment by sierra-moxon** [comment]
recipe:
```
poetry update linkml

# get the rest of the doc 
make gen-project

mkdir target/docs/specification
cp specification/*md target/docs/specification/

poetry run mkdocs build --dirty
```
