### ISSUE TITLE
Request: Flag to make `required` LinkML fields optional

### ISSUE THREAD

**Issue by joeflack4** [linkml/linkml#1173]
## Overview
I had an issue where I had an invalid Obograph that crashed LinkML, and Chris already [put in a fix](https://github.com/linkml/linkml/issues/1156) to change this field from required to optional. There's also [further discussion at Obographs](https://github.com/geneontology/obographs/issues/89) about changing it to optional in the spec as well, I believe.

@cmungall  [had suggested](https://github.com/linkml/linkml/issues/1156#issuecomment-1354017776) that we could potentially add a flag to make required fields optional, and that I should open up an issue.. It seems similar to a "strict/non-strict mode" I was thinking about. I hope I'm indeed understanding what you are suggesting, Chris.

Chris wrote: 
> Currently the genusId is stated as required in the OAK obographs schema, so the linkml runtime framework is doing the correct thing in not instantiating these objects.
> To change this behavior let's make an issue in the OAK repo - or you could even do the PR directly, remembering to tag [geneontology/obographs#89](https://github.com/geneontology/obographs/issues/89)

## Related
- https://github.com/linkml/linkml/issues/1156
- https://github.com/geneontology/obographs/issues/89

**Comment by sierra-moxon** [comment]
Discussed at linkml dev meeting this week: closing for now as "won't do", maybe there is another way to get at what is needed here (I read the accompanying issues and it seems like there is at least a workaround for the original concern)?

**Comment by joeflack4** [comment]
That's fine, Sierra. That is correct too, that we put in a workaround, so no immediate use case for this.
