### ISSUE TITLE
markdowngen: order of slots should be preserved

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#118]
E.g. in https://cmungall.github.io/ontology_associations/GafAssociation/

which is generated from https://github.com/cmungall/ontology_associations/blob/main/src/schema/gaf.yaml

the order should be preserved. while there is no semantic relevance to the ordering,

 - there is a fix-field TSV format that corresponds to this, in this case
 - in the general case, there may be reasons to preserve ordering, eg to lessen surprise for users

**Comment by sierra-moxon** [comment]
I believe we have methods in schemaview that allow the user to pass in ordering (either by rank, preserve - the ordering in the schema yaml, or alphabetically).  We also have jinja specifications and examples and code in docgen specifically to handle this.  Closing for now; please reopen if we need to port this functionality to markdowngen
