### ISSUE TITLE
creating a visitor for json data with model information available (diff two json files)?

### ISSUE THREAD

**Issue by kervel** [linkml/linkml#1186]
Hello, (i can't put the "question" label on this issue)

i have a model in linkml, and i'd like to create some python code that goes over the data, but where i have for every object/field/list... i process in json, i have the associated linkml metadata available.

my usecase: i want to create a differ so i can compare two json files. This differ would need some directions (eg it can ignore certain fields, sometimes there are special rules, the order of elements in a list could matter or could not matter, ...). I would like to store these directions as annotations in my linkml datamodel.

i wonder what would be the best approach for doing this. I'd like to avoid converting my model to dataclasses or pydantic classes because i'd like to have my differ as a reusable component that would not require code (re)generation when i want to apply it to another version of the model.

thanks!
Frank

**Comment by sierra-moxon** [comment]
Hi @kervel - great questions, I don't have exact answers for you yet, but I would point to  https://github.com/linkml/linkml-dataops/blob/main/tests/test_differ.py for some examples.  
And a change language that @cmungall is developing to help standardize difference checking: https://github.com/INCATools/kgcl

Let's put this on the community agenda for just after the holidays.

**Comment by kervel** [comment]
Ow very nice! i didn't know so much existed already. The test_differ looks nice, it has the caveat of requiring the generation of the python data classes. I use polymorphism using type designators now (see my other pull request) so i would have to at least do the same PR for the dataclasses for this to work. My idea was that i could load the schema at runtime without having to generate python classes, and this way i could support any schema i have a yaml for.


this is where i was at now:
![image](https://user-images.githubusercontent.com/154455/208960922-945e0f98-350d-47f9-b788-5fa170118b7d.png)

**Comment by sierra-moxon** [comment]
Discussed at 1/19/2023 community call. 
We like the idea of specifying the "diff" parameters inside the schema and a PR for standardizing this in the linkml-model (perhaps outside of annotations? TBD) would be welcome. 
We'd like more examples of a getting schema metadata about instance-level classes in python dataclasses and/or pydantic.  In particular, an example of walking the object tree, but holding a schemaview instances as well.

**Comment by kervel** [comment]
i think for us it would not be a problem to keep the metadata as annotations until it matures enough, i think annotations are perfectly fine for that. we'll have a go at implementing a differ using the annotations.

**Comment by kervel** [comment]
i was playing with the idea of creating a linkml "box" for dictionaries and lists. below is a prototype that allows me to walk a json structure and get the class and slot info for all values. Still lots of functionality missing, but kinda works.

```python
from dataclasses import dataclass
from typing import Union, Dict, List, Optional, Any
from functools import lru_cache, cache
from linkml.generators.common.type_designators import get_type_designator_value
from linkml_runtime.utils.schemaview import SchemaView
from linkml_runtime.linkml_model.meta import ClassDefinition, SlotDefinition

import functools
import weakref



@dataclass
class LinkmlBox():
    lml_schemaview: SchemaView
    lml_parent: Optional["LinkmlBox"]
    lml_key_at_parent: Optional[str]

    def get_lml_class(self) -> Optional[ClassDefinition]:
        raise Exception("not implemented")
    
    @my_lru_cache
    def get_lml_slot(self) -> Optional[SlotDefinition]:
        ky = self.lml_key_at_parent
        if isinstance(self.lml_parent, LinkmlBoxList):
            # is a multivalued attribute, so we need to descend one level deeper to get to the level where the actual slot was defined
            ky = self.lml_parent.lml_key_at_parent

        slot = self.lml_schemaview.get_slot(ky)
        if slot is None:
            raise Exception(f"cannot find slot with name {ky} {self.lml_key_at_parent}")
        return slot

    def _box_child(self, item, key_at_parent: Optional[str]):
        if isinstance(item, dict):
            return LinkmlBoxDict(unboxed_dict=item, lml_schemaview=self.lml_schemaview, lml_parent=self, lml_key_at_parent=key_at_parent)
        elif isinstance(item, list):
            return LinkmlBoxList(unboxed_list=item, lml_schemaview=self.lml_schemaview, lml_parent=self, lml_key_at_parent=key_at_parent)
        else:
            return LinkmlBoxValue(unboxed_value=item, lml_schemaview=self.lml_schemaview, lml_parent=self, lml_key_at_parent=key_at_parent)


@dataclass
class LinkmlBoxValue(LinkmlBox):
    unboxed_value: Any

@dataclass
class LinkmlBoxDict(dict, LinkmlBox):
    unboxed_dict: Dict

    @my_lru_cache
    def get_lml_class(self) -> Optional[ClassDefinition]:
        slot = self.get_lml_slot()
        tp_designators = [x for x in self.lml_schemaview.class_induced_slots(slot.range) if x.designates_type]
        if len(tp_designators) > 0:
            tp_designator = tp_designators[0]
            tp_val = self.unboxed_dict[tp_designator.name]
            if tp_val  is not None:
                for cls in self.lml_schemaview.class_descendants(slot.range):
                    dv = get_type_designator_value(self.lml_schemaview, tp_designator, cls)
                    if tp_val == dv:
                        return cls
        return self.lml_schemaview.get_class(slot.range)
    


    def __getitem__(self,key):
        unboxed = self.unboxed_dict[key]
        return self._box_child(unboxed,key)


@dataclass
class LinkmlBoxDictRoot(LinkmlBoxDict):
    lml_clz: ClassDefinition

    def get_lml_class(self) -> Optional[ClassDefinition]:
        return self.lml_clz
    
    def get_lml_slot(self) -> Optional[SlotDefinition]:
        return None


@dataclass
class LinkmlBoxList(list, LinkmlBox):
    unboxed_list: List

    def __getitem__(self,key):
        unboxed = self.unboxed_list[key]
        return self._box_child(unboxed,key)



def box_object(l: Union[List, Dict, Any], sv: SchemaView, class_or_slot_name: str) -> LinkmlBox:
    if isinstance(l, Dict):
        return LinkmlBoxDictRoot(lml_schemaview=sv, unboxed_dict=l, lml_parent=None, lml_clz=sv.get_class(class_or_slot_name),lml_key_at_parent=None)
    raise Exception("not implemented")

def box_get_slot(b: LinkmlBox):
    return b.get_lml_slot()

def box_get_class(b: LinkmlBox):
    return b.get_lml_class()


```

**Comment by sierra-moxon** [comment]
closing as complete; thank you for the brilliant example @kervel!
