### ISSUE TITLE
linkml-model.linkml_files.py needs a once over

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1190]
Linkml_files.py was intended to:
a) Provide a handy set of constants
b) Accomodate verisioning access
c) Cache github.io type accesses

It needs a review, rethink and documentation

**Comment by cmungall** [comment]
This is the file: https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/linkml_model/linkml_files.py

**Comment by sierra-moxon** [comment]
handled here: https://github.com/linkml/linkml-runtime/commit/fc72e337b0499b58f1b0217faefb066768709fa5 closing as complete.
