### ISSUE TITLE
poetry version 0.0.0 causes problems on non pypi imports

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1195]
Importing a linkml-module from github or from a submodule doesn't work because the current version identifier is set to "0.0.0"

The `PBR` module that was used prior to the poetry upgrade did a reasonable job of incrementing the current version and adding a "devN" tag when necessary.  Might there be an equivalent in poetry?

**Comment by hrshdhgd** [comment]
The reasoning behind `0.0.0` is that when we publish the package to `PyPI` via GitHub, poetry looks at the GitHub versioning and reflects it in `PyPI` and hence 2 different places (`pyproject.toml` file and GitHub itself) will not show different versions (only 1 non-zero version). This change was fairly recent based on @cmungall 's request.

**Comment by hrshdhgd** [comment]
> Importing a linkml-module from github 

I do not follow what you mean. Could you please elaborate?

**Comment by dalito** [comment]
The version look-up code had a bug.

Another reason may be that the install step was skipped and the checked-out package was just added to python-path and imported. In this case no version-specifier is present because it is only generated during the install step (by the dynamic-versioning plugin).

**Comment by hsolbrig** [comment]
The situation where this bug occurs is that I want to include the latest version of a specific branch (e.g. "main") in an integration test module.  The approach that I'm taking at the moment is to create the following directory structure:

    linkml-integration:
        ...
       submodules:
           linkml: 
              ...
           linkml-runtime:
              ...
       pyproject.toml


I can then use the git submodule functions to pull whatever specific branch / version I want into the testing. The pyproject.toml includes:
```
[tool.poetry.dependencies]
python = "^3.9"
linkml-runtime = { path = "submodules/linkml-runtime", develop = false}
linkml = { path = "submodules/linkml", develop = false}
```

This doesn't appear to work, however, because the version isn't filled in.

**Comment by dalito** [comment]
As far as I understand the github submoldules are not installed and thus get no version assigned. Could you (instead of using git submodules) add the github-location as a dependency of the `linkml-integration` project? e.g. 

`poetry add git+https://github.com/linkml/linkml.git#v1.4.0` (to set a specific version, see poetry-docs for [more examples](https://python-poetry.org/docs/cli/#add))

Then poetry would install the dependency from github and set its version.
