### ISSUE TITLE
windows testing on PR does not register errors

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#1200]
**Describe the bug**
Running tests on windows platforms via github actions register "successful" even when tests fail on windows.

An example: https://github.com/linkml/linkml/actions/runs/3832945778/jobs/6523847485 

Note the exact same failures in the ubuntu version of this PR:
https://github.com/linkml/linkml/actions/runs/3832945778/jobs/6523847298

but the coverage report is still generated in windows tests instead of erroring out on the test failures, which leads to a "green check" in github actions interface. 
<img width="444" alt="Screen Shot 2023-01-03 at 2 42 18 PM" src="https://user-images.githubusercontent.com/4561292/210453412-3f2cfaff-46f8-4e39-a1d0-1eabb847f882.png">

**Expected behavior**

windows OS github action fails when tests fail on windows platform via github actions.
it might be that we just need to capture a different error code on the windows platform than is being captured on ubuntu?

**Comment by dalito** [comment]
The exit code is correctly forwarded from unittest over coverage to poetry:

```
(.venv) PS C:\Users\david\MyProg\exit-code-testing> poetry run coverage run -m unittest discover
F.
======================================================================
FAIL: test_add (tests.test_me.SomeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\david\MyProg\exit-code-testing\tests\test_me.py", line 5, in test_add
    assert 2 + 2 == 5
AssertionError

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
(.venv) PS C:\Users\david\MyProg\exit-code-testing> echo $LastExitCode
1
```
So a failing test should fail the pipeline on Windows, too.

But it may be this bug in github actions: https://github.com/actions/runner-images/issues/6668
