### ISSUE TITLE
ER diagrams do not show up in mkdocs as mkdocs is using an old mermaid.js

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1207]
The latest release has a mermaid ER generator:

- #1204 

The mermaid renders fine in pages here. Example below.

However, these do not show up in sites made with mkdocs.

It looks like the generated website uses 

```html
<script src="https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"></script><script>mermaid.initialize({});</script><script>
```

which is ER-unaware

changing this to

```html
<script src="https://unpkg.com/mermaid@9.3.0/dist/mermaid.min.js"></script><script>mermaid.initialize({});</script><script>
```

fixes the issue. This could be done with an ugly pre-processing step but maybe there is a better way to do this from within mkdocs? Or maybe there just needs to be a new release of https://github.com/fralau/mkdocs-mermaid2-plugin?

```mermaid
erDiagram
Recipe {
    string label
    string description
}
Step {

}
FoodItem {
    string id
    string label
}
Action {
    string id
    string label
}
Ingredient {
    string quantity
}
RecipeCategory {
    string id
    string label
}

Recipe ||--}o RecipeCategory : "category"
Recipe ||--}o Ingredient : "ingredients"
Recipe ||--}o Step : "steps"
Step ||--|o Action : "action"
Step ||--}o FoodItem : "inputs"
Step ||--}o FoodItem : "outputs"
Ingredient ||--|o FoodItem : "food_item"

```

**Comment by cmungall** [comment]
fixed by

```yaml
plugins:
  - search
  - mermaid2:
      version: 9.3.0
```

how do we coordinate this change? Shall we put this in the cookiecutter? Ideally they would use the latest version in the plugin

**Comment by sierra-moxon** [comment]
4/21/2023 - we should probably migrate to the mermaid generator and have a better way of embedding the images in pages vs. doing it via jinja templates.  I see the last release of the plugin we're currently using is in 2021.
