### ISSUE TITLE
linkml-run-examples can't find schema modules to be imported

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1219]
- `schema.yaml` has the path `/path/to/schema.yaml`
- `schema.yaml` imports `import.yaml`
-  `import.yaml` is also located in `/path/to/`
-  `linkml-run-examples` is run from `/`, as follows

```shell
linkml-run-examples \
  --schema /path/to/schema.yaml
  --input-directory <VALIDS_PATH> \
  --counter-example-input-directory <INVALIDS_PATH> \
  --output-directory <OUTPUT_PATH>
```

gives an error message like 

> FileNotFoundError: [Errno 2] No such file or directory: '/import.yaml'

**Comment by turbomam** [comment]
See also 
- #1218

**Comment by cmungall** [comment]
I've been unable to represent this in other projects that use imports

**Comment by turbomam** [comment]
represent or repeat?

**Comment by cmungall** [comment]
Managed to replicate, made a separate issue #1228
