### ISSUE TITLE
Nested generators do not preserve relative schema path, which breaks imports

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1228]
Background:

Generators can take any of the following as initialization arguments:

1. path to a schema yaml file
2. a schema yaml string
3. a schema object

In cases 1 and 2, a schema object is created by parsing the yaml.

In case 1, the path is preserved, which allows for relative imports to work

For example, if we call:

```PythonGenerator("/path-to/my-schema.yaml")```

And if we have a folder structure

- path-to
     - my-schema.yaml
     - core.yaml

And my-schema.yaml has `imports: ['core']` then the imported module is resolved via a relative path. This is persisted if `SchemaDefinition.source_file` contains the absolute path to `my-schema.yaml`

`source_file` is set by the SchemaLoader, but *not* by SchemaView

So if we have:

```PythonGenerator(my_schemaview.schema)```

Then the import routine has no way of knowing where to find `core.yaml`

The fix is to have schemaview set `source_file`

**Comment by sneakers-the-rat** [comment]
This problem also is present when resolving the `imports_closure` in SchemaView when traversing >1 levels of import.

Eg. i have 
```
patha/pathb/schema_1.yaml
pathc/pathd/schema_2.yaml
pathc/pathd/subschema.yaml
```

where `schema_1.yaml` imports `../../pathc/pathd/schema_2`, and `schema_2.yaml` imports `subschema`

The iteration just uses the imported name: https://github.com/linkml/linkml-runtime/blob/8a8ee69db780eebf571d7344260b0e9bbfd88335/linkml_runtime/utils/schemaview.py#L235

This extremely janky fix resolves my problems for now:

```python
def imports_closure():
    # ...
    for i in s.imports:
        if sn.startswith('.') and ':' not in i:
            # prepend the relative part
            i = '/'.join(sn.split('/')[:-1]) + '/' + i
        if i not in visited:
            todo.append(i)
     # ... 
```
