### ISSUE TITLE
Consider separate LinkML runtime

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#125]
A goodly portion of the generator code won't be needed once one has built a model.  We should consider splitting this repository into two parts:

* **runtime**: The libraries and tools that are needed to load, transform and serialize data that conforms to a particular schema
* **compile**: The libraries and tools needed to generate and update schema's defined in LinkML

As an example, the `biolinkml/generators` directory would belong to **compile** -- they have no purpose in **runtime**  The `biolinkml/util` directory would be divided - `yamlutils.py`, as an example, would belong to **runtime**, while `schemaloader` would be **compile**.

Note that the `loaders` and `dumpers` directories in the [loaders branch](https://github.com/biolink/biolinkml/tree/loaders) would be in **runtime**

**Comment by cmungall** [comment]
I think this can be closed?
