### ISSUE TITLE
terminusdbgen.py has unresolved external: terminusdb_client.woqlquery

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#1271]
**Describe the bug**
terminusdbgen.py has unresolved external

**To reproduce**
```python
import linkml.generators.terminusdbgen
```
```text
  File "linkml/linkml/generators/terminusdbgen.py", line 10, in <module>
    from terminusdb_client.woqlquery import WOQLQuery as WQ

ModuleNotFoundError: No module named 'terminusdb_client'
```

**Comment by cmungall** [comment]
hmm, must have dropped from the pyproject... I guess we don't have tests for it!

https://pypi.org/project/terminusdb-client/

**Comment by dwinston** [comment]
I'd like to update `TerminusdbGenerator` to roughly the content at <https://github.com/microbiomedata/nmdc-runtime/blob/9fd275a69e3d5c52a0b20ace8a1d60ab06abddd0/nmdc_runtime/site/terminusdb/generate.py>, which is (1) more up-to-date and (2) does not require the `terminusdb_client` package as a dependency. And I suppose I will include tests this time around. :)

**Comment by cmungall** [comment]
Thanks Donny!
