### ISSUE TITLE
docgen.py index.md not respect --no-mergeimports

### ISSUE THREAD

**Issue by noelmcloughlin** [linkml/linkml#1282]
**Describe the bug**

DocGenerator does not use value of self.mergeimports 

I  expect `poetry run gen-doc --no-mergeimports -d docs src/myschema/schema/myschema.yaml` to only list classes, slots, types from  "myschema" on index page (generated by make serve) but I see imported classes listed too. 

**To reproduce**

```poetry run gen-doc --no-mergeimports -d docs src/myschema/schema/myschema.yaml ```

**Expected behavior**

**Additional context**
```
$ pip freeze | grep linkml
linkml==1.3.17
linkml-dataops==0.1.0
linkml-runtime==1.4.3```

**Comment by sujaypatil96** [comment]
Hm, the latest version of docgen in linkml does respect `--mergeimports`. The fix came in a v1.4.x release of linkml, perhaps you could upgrade to the latest version and test documentation generation with that? Let me know if it still doesn't work and I'll look into it.

**Comment by noelmcloughlin** [comment]
I am using cookiecutter and noticed packages are old so I upgraded linkml to latest version (see also https://github.com/linkml/linkml-project-cookiecutter/pull/44)

I  expect `poetry run gen-doc --no-mergeimports -d docs src/myschema/schema/myschema.yaml` to only list classes, slots, types from  "myschema" on index page (generated by make serve) but I see imported classes listed too. 

So after experimenting I found #1283 worked best in achieving correct index page.

**Comment by turbomam** [comment]
see also
- https://github.com/linkml/linkml-project-cookiecutter/pull/44

**Comment by noelmcloughlin** [comment]
See https://github.com/linkml/linkml/pull/1283#issuecomment-1435409515

**Comment by sujaypatil96** [comment]
See PR #1309

**Comment by noelmcloughlin** [comment]
Currently not fixed by https://github.com/linkml/linkml/pull/1309
