### ISSUE TITLE
ranges that appear in gen-doc pages should be hyperlinked to that type's or class' page

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1286]

**Comment by sujaypatil96** [comment]
@turbomam could you clarify what _ranges_ in the doc pages are not hyperlinked?

**Comment by sujaypatil96** [comment]
@turbomam ranges being displayed on class documentation pages, for example the NMDC schema's _Biosample_ class documentation page: https://microbiomedata.github.io/nmdc-schema/Biosample/ has the ranges appearing in the [slots table](https://microbiomedata.github.io/nmdc-schema/Biosample/#slots) hyperlinked.


The ranges displayed in the [Properties](https://microbiomedata.github.io/nmdc-schema/host_disease_stat/#properties) section of slot documentation pages, for example [host_disease_stat](https://microbiomedata.github.io/nmdc-schema/host_disease_stat/) are also hyperlinked.

My guess is that this issue can be closed. Let me know if I am missing something.

**Comment by sujaypatil96** [comment]
Feel free to reopen if you think I'm missing interpreting the point of the issue.
