### ISSUE TITLE
Add normalizer to pydanticgen for inlined dicts and lists

### ISSUE THREAD

**Issue by kevinschaper** [linkml/linkml#1304]
Pydantic data classes don't yet know how to serialize a data file with a list into a model that expects a dictionary, an important (and very user friendly!) feature of linkml. The details of the test failure are described in https://github.com/linkml/linkml/pull/1273#issuecomment-1435306134

Pythongen uses this method in linkml_runtime: https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/utils/yamlutils.py#L102

As @kervel noted recently, a benefit of the pydantic data classes is the smaller import footprint, so it might be better not to to re-use the linkml-runtime method here, and instead add a re-usable validator to the model template code that is defined once per model. 

https://docs.pydantic.dev/usage/validators/

**Comment by cmungall** [comment]
Yes, let's keep the footprint minimal. Also the normalization code here will do lots of repair magic which I'd rather keep out of pydanticgen

**Comment by kevinschaper** [comment]
Sounds good that we don't need to do this

**Comment by cmungall** [comment]
I think we *do* need something here to make it easier to instantiate a CompactDict
