### ISSUE TITLE
Allow running testsuite faster

### ISSUE THREAD

**Issue by WolfgangFahl** [linkml/linkml#1306]
**Is your feature request related to a problem? Please describe.**
Currently the test suite run quite slow (100-1000 secs)

**Describe the solution you'd like**
* Allow to select a subsuite that does the most relevant tests but quicker.
* Allow parallel execution #1305 

**How important is this feature?** Select from the options below:
• Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
Shorter release cycles and PR requests will be possible.

For a start I'd profile tests e.g. with the base class such as
https://github.com/WolfgangFahl/pysotsog/blob/main/tests/basetest.py

**Comment by nlharris** [comment]
Note that Wolfgang has identified this as a "blocker".

**Comment by dalito** [comment]
With pytest as test runner selecting subgoups of tests or automatically repeating the last failing test is possible. It is not a solution but may help a little in the meantime.

**Comment by cmungall** [comment]
We have made a lot of progress with switching to pytest and improving speed

**Comment by sneakers-the-rat** [comment]
tests now run in <5m :)
