### ISSUE TITLE
add antonymy to the meta model to allow tagging of 'opposites' in biolink-model?

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#131]
It would be convenient to have a way to specify that a particular slot was the "opposite" (probably with room to declare things on a gradient of opposition) of another (see use cases in https://github.com/biolink/biolink-model/issues/657, and the parent issue https://github.com/biolink/biolink-model/issues/656).

**Comment by cmungall** [comment]
Recommend to use annotations for now
