### ISSUE TITLE
docgen.py no-mergeimports creates incorrect docs

### ISSUE THREAD

**Issue by noelmcloughlin** [linkml/linkml#1311]
**Describe the bug**

The script `docgen.py` generates incorrect `index.md` by populating merged imports even though `--no-mergeimports` should be respected.

The code  fails to generate <parentclass>.md pages because `--no-mergeimports` is respected (but should be ignored) for everything except index.md.

**To reproduce**
Create a parent schema.
Create a subschema and import parent schema.
Run `docgen.py --no-mergeimports subschema.yaml` and `make serve` and notice how parent classes/slots/types/subsets are included in index.md

**Expected behavior**
Index.md should list subschema classes/types/slots/subsets only not everything.

**Additional context**

The parameter `self.mergeimports` should be passed to lines 660, 672, 684, 696, 708 to fix `index.md` and should not be passed to lines 196, 205, 189, 215, 224, 234 to ensure <class>.md is generated for referenced parent classes (i.e. self.mergeimports must be ignored).

**Comment by sujaypatil96** [comment]
Great catch @noelmcloughlin. Agreed that the `self.mergeimports` must be passed to the relevant jinja processing methods in docgen too. I'll make a PR for that soon.

But to your second point, could you clarify what you mean by _referenced parent classes_? Because it seems to be creating Markdown pages for our [test schema](https://github.com/linkml/linkml/blob/main/tests/test_generators/input/kitchen_sink.yaml) pretty accurately.

**Comment by noelmcloughlin** [comment]
It should generate Markdown pages for all classes, including referenced/imported parent classes, so we can walk up and down the inheritance tree in the web browser.  At the moment I see 404 because referenced/parent classes markdown is not generated.  My original aim is to fix `index.md` only - the rest of `docgen.py` behaves correctly regardless of `mergeimports` value.

**Comment by sujaypatil96** [comment]
My apologies, I was having some poetry cache issues and there was some incorrect output I was seeing. I understand what you mean, and I'll have this issue fixed.

**Comment by sujaypatil96** [comment]
Your original PR where you made changes to just the jinja processing methods was perfectly right, my apologies for making you work through so many other PRs and other discussion items to get this fixed.

**Comment by sujaypatil96** [comment]
I'll make a new PR to address this and we can get it merged in.
