### ISSUE TITLE
as of linkml-runtime 1.4.7, schemaview can't build a  view of a root schema and it's imports from a URL

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1317]
For example, trying to make a view of https://raw.githubusercontent.com/linkml/linkml-model/main/linkml_model/model/schema/meta.yaml

> urllib.error.HTTPError: HTTP Error 404: https://w3id.org/home/mark/.cache/pypoetry/virtualenvs/submission-schema-DC6HKp4p-py3.9/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/units.yaml

I works with linkml-runtime 1.4.5

On my Ubuntu 20 system, I am told that

> Because submission-schema depends on linkml-runtime (1.4.6) which doesn't match any versions, version solving failed.

**Comment by cmungall** [comment]
likely culprit: https://github.com/linkml/linkml-runtime/pull/248

**Comment by turbomam** [comment]
I continue to have this problem in linkml-runtime > 1.4.7

**Comment by turbomam** [comment]
@cmungall this is what we just discussed in our 1-on-1 meeting
