### ISSUE TITLE
Live information collaboration with linked data

### ISSUE THREAD

**Issue by gsvarovsky** [linkml/linkml#1336]
Hi LinkML community, our project [**m-ld**](https://m-ld.org/) is a software component for solving the hard problem of ensuring consistency during live collaboration on structured data. It's fundamentally a Conflict-free Replicated Data Type (CRDT) over Linked Data.

We've recently started building an extension to apply a (a subset of) SHACL for [constraining data](https://github.com/m-ld/m-ld-spec/discussions/103) in **m-ld**. Our "constraints" go beyond the normal "validation" use-case because of our additional need to provide convergence guarantees when operations are concurrent.

We see a lot of value in LinkML, especially at application design-time, where both programming language-native types and runtime shapes are needed. See [this thought article](https://gist.github.com/Peeja/0212d1a299d78d92ddf3d5563e6bd1f9#:~:text=Further%2C%20we%20will%20develop%20and%20demonstrate%20patterns) for more details.

We have many use-cases in mind for our tech, including making existing web applications more collaborative, and also in being a mediator between siloed applications. It would be great to have a chat about where our projects intersect!

**Comment by nlharris** [comment]
Hi @gsvarovsky, thanks for reaching out! We're glad you're interested in LinkML. Our developers are super-busy right now but someone will get back to you soon. Do you have any specific questions?

**Comment by sierra-moxon** [comment]
Hi @gsvarovsky - thanks for reaching out, please do come to our community meeting with more questions and/or to present your work!  Happy to coordinate.  I'm going to close this issue for now; please reopen if there are specific bugs/features you need. :)
