### ISSUE TITLE
Add option to pass file delimiter for linkml-validate

### ISSUE THREAD

**Issue by Shalsh23** [linkml/linkml#1339]
**Is your feature request related to a problem? Please describe.**
`linkml-validate` accepts csv files as input but treats csv and tsv synonymously, leading to unexpected validation output. It would be useful to have an option to explicitly pass the delimiter on command line. 

As per discussion with @cmungall , it would also be useful if files and suffix headers are used to guess the delimiter even when it is not explicitly passed.

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Comment by pkalita-lbl** [comment]
As of v1.5.6 the `linkml-validate` command should correctly differentiate between CSV and TSV files. There is no option to explicitly set the delimiter. Rather, it's just based on the filename extension.
