### ISSUE TITLE
github actions failing at poetry install step

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1354]
See https://github.com/linkml/linkml/actions/runs/4495836273/jobs/7909897420?pr=1353

```
• Installing linkml-dataops (0.1.0)
  • Installing myst-parser (1.0.0)

  _WheelFileValidationError

  ["In /home/runner/.cache/pypoetry/artifacts/36/32/40/7ac8bc4a2e0e3e0c22dd65eff985311f99f161dfc91ec1b64b6d9ec9ad/furo-2022.12.7-py3-none-any.whl, hash / size of furo/__init__.py didn't match RECORD", "In 
```

this seems to be the issue:

- https://github.com/python-poetry/poetry/issues/7691

@hrshdhgd and @pkalita-lbl  encountered this in other repos, this was their fix:

https://github.com/linkml/linkml-runtime/commit/862e760569b7494e89579893ed307c62343863db

**Comment by hrshdhgd** [comment]
For this particular error, pinning poetry to v1.4.0 in the GitHub workflow worked!

**Comment by nlharris** [comment]
Can this be closed as fixed?

**Comment by pkalita-lbl** [comment]
No, it hasn't been resolved for this repo yet. I can open a quick PR though.
