### ISSUE TITLE
gen-json-schema -> Unrecognized prefix: xsd

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#138]
I copied the sample model from https://github.com/biolink/biolinkml#examples into myclipboard and the cat'ed it to a file `https://github.com/biolink/biolinkml#examples`

Then I did `pipenv run gen-json-schema linkml-tutorial.yaml > linkml-tutorial.schema.json` but got 
> WARNING:JsonSchemaGenerator:File "/home/mark/linkml-tutorial/linkml-tutorial.yaml", line 7, col 10: Unrecognized prefix: xsd

linkml-tutorial.schema.json **was** created

Am I causing this problem myself by running this exercise in some random directory as opposed to within my local `biolink/biolinkml` project folder?

Or maybe defining the xsd prefix is part of the tutorial and I just skipped over that?

**Comment by sujaypatil96** [comment]
Based on this [commit](https://github.com/biolink/biolinkml/commit/86e182df3bf2354816770c7c7feed51f24196f78), has this issue been resolved @turbomam?

**Comment by cmungall** [comment]
Is this resolved @turbomam?
