### ISSUE TITLE
Tutorial 7 example file throws slot_usage error

### ISSUE THREAD

**Issue by sooyounga** [linkml/linkml#1383]
**Describe the bug**
When running gen-yuml command for the example file provided in tutorial 7: https://linkml.io/linkml/intro/tutorial07.html#customizing-slots-in-the-context-of-classes-slot-usage 
We run into the following errors:
`ERROR:root:slot_usage for undefined slot: related_to
ERROR:root:slot_usage for undefined slot: relationship_type
ERROR:root:slot_usage for undefined slot: related_to
ERROR:root:slot_usage for undefined slot: relationship_type`
The figure is still generated but we are unsure how to resolve the above errors.

**About your computer (if applicable, please complete the following information):**
 - OS: [e.g. iOS] X
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] linkml 1.5.0

**Comment by cmungall** [comment]
Thanks! It looks like the schema uses a non-recommended shortcut, we should fix this!

**Comment by HendrikBorgelt** [comment]
I have faced a simillar log report in an attempt to use a python script to perform the data validation of tutorial 7. As i think the problems are related, i have not opened a new issue but just added to this. 

As code i use:

```from linkml_runtime.loaders import yaml_loader
from linkml.generators.pythongen import PythonGenerator
import yaml
from slot_usage_example import Container

with open("./slot_usage_example.yaml") as file:
    data = file.read()

gen_ser = PythonGenerator(data).serialize()

with open("./slot_usage_example.py", 'w') as outfile:
    outfile.write(gen_ser)

test_class = yaml.load(data, Loader=yaml.FullLoader)

with open("./data.yaml") as file:
    data2 = file.read()

model = yaml_loader.load(data2, target_class=Container)
```

which results in this output: 
```
ERROR:root:slot_usage for undefined slot: related_to
ERROR:root:slot_usage for undefined slot: relationship_type
ERROR:root:slot_usage for undefined slot: related_to
ERROR:root:slot_usage for undefined slot: relationship_type
```
I use the unmodified "files" as given on the website.


**About your computer (if applicable, please complete the following information):**

OS: [e.g. iOS] Windows 10
Browser: [e.g. chrome, safari] Firefox
IDE: PyCharm 
Version: [e.g. 22] python 3.11 with linkml 1.5.5
