### ISSUE TITLE
linkml documentation generation should use class specific definition

### ISSUE THREAD

**Issue by aclum** [linkml/linkml#1387]
**Describe the bug**
linkml documentation generation logic currently shows the range of a slot from its global definition rather than it’s modified class specific definition
**To reproduce**
1. Go to https://microbiomedata.github.io/nmdc-schema/Biosample/
2. Compare range of slot depth in https://microbiomedata.github.io/nmdc-schema/Biosample/#slots vs https://microbiomedata.github.io/nmdc-schema/Biosample/#linkml-source for slot elev

**Expected behavior**
slot elev for class Biosample should be 'float' based on linkml source class specific definition, not [QuantityValue](https://microbiomedata.github.io/nmdc-schema/QuantityValue/)

**Screenshots**
![Screenshot 2023-04-06 at 3 49 31 PM](https://user-images.githubusercontent.com/8196591/230512149-b89c5b57-60d4-4ab2-bbf6-b1856fa7ead5.png)
![Screenshot 2023-04-06 at 3 32 58 PM](https://user-images.githubusercontent.com/8196591/230512154-9d3cdfc9-f123-41e2-a0ee-093f209b4a1e.png)

**About your computer (if applicable, please complete the following information):**
 - OS: mac
 - Browser chrome
 

**Additional context**

**Comment by cmungall** [comment]
We discussed this on our linkml call. Good catch. This is indeed a bug, it should always show things in context. It is odd because this behavior doesn't seem to be manifesting on other linkml projects.

@sujaypatil96 will take care of this
