### ISSUE TITLE
LinkML normalizer can't seem to convert a datetime string into a date

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1389]
When provided with a LinkML schema in which slot `birth_date` has the range `date`, DataHarmnonizer collects a datetime like '2013-03-16T04:00:00.000Z'

I have raised an issue with [DataHarmonizer](https://github.com/cidgoh/DataHarmonizer/issues/389)

In the meantime, I was hoping to convert the datetime to a date with linkml-validator but that doesn't seem to work

see
- https://github.com/turbomam/examples-first-cookiecutter/issues/74#issuecomment-1501934657

**Comment by nlharris** [comment]
@turbomam assigning bugs to Chris is not a best practice, but maybe he told you to assign it to him?
