### ISSUE TITLE
Add ability to add custom data structures such as numpy arrays in pydanticgen

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1395]
For background see docs here: #1376

Example desired pydantic:

https://github.com/rly/hdmf-term-lists/blob/a5ae149c100a35aec9b5449a853e69b11247334b/src/hdmf_term_lists/datamodel/nwb_electrical_array.py#L44-L47

https://github.com/rly/hdmf-term-lists/blob/a5ae149c100a35aec9b5449a853e69b11247334b/src/hdmf_term_lists/datamodel/nwb_electrical_array.py#L75-L79

Example code to instantiate data:

https://github.com/rly/hdmf-term-lists/blob/a5ae149c100a35aec9b5449a853e69b11247334b/tests/test_nwbfile.py#L19-L43

See also:

https://github.com/cheind/pydantic-numpy

**Comment by rly** [comment]
See https://github.com/rly/hdmf-term-lists/blob/main/src/hdmf_term_lists/datamodel/nwb_electrical_array.py
and https://github.com/rly/hdmf-term-lists/blob/main/tests/test_nwbfile.py
