### ISSUE TITLE
Add generators for terminusDB schemas

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#140]
Either to WOQL.js or WOQL.json-ld

https://terminusdb.com/docs/terminushub/reference/woql

cc @polyneme

**Comment by majidaldo** [comment]
wouldn't it be better to just use their logic to generate a TDB schema via json schema? https://github.com/terminusdb/terminusdb-client-python/blob/main/terminusdb_client/schema/schema.py#L708

it's bidirectional too.

**Comment by dwinston** [comment]
The current generic 
 LinkML json schema generator does not encode hierarchy. I’m actually not sure if json schema can encode hierarchy, i.e. “inherits” relationships. TerminusDB json has an “@inherits” field for which we wouldn’t want LinkML translation to be lossy.

**Comment by dwinston** [comment]
Also, I’m pretty sure this generator needs a re-looking at. The terminus modeling language has evolved a bit. I plan to look at this in order to re-encode the NMDC’s LinkML schema as a terminusDB json-file-representation schema.
