### ISSUE TITLE
"linkml-validate" reports erroneous JSON-Schema validation error

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#1422]
**Describe the bug**
`linkml-validate` reports a JSON-Schema validation error on data that appear to be correct according manual validation

**To reproduce**
1. Create schema `test.schema.yaml` provided in the *Additional context* section
2. Generate the corresponding JSON-Schema with `gen-project -I jsonschema ./test.schema.yaml`
3. Create test data document `test.yaml` provided in the *Additional context* section
4. Convert it to JSON with `yq -o=json eval ./test.yaml > test.json`
5. Run JSON-Schema validation `check-jsonschema --schemafile ./tmp/jsonschema/test.schema.schema.json ./test.json`
6. Confirm that the validity of the data gets reported `ok -- validation done`
7. Run LinkML validation `linkml-validate --schema ./test.schema.yaml ./test.yaml`
8. Observe reported error `jsonschema.exceptions.ValidationError: "JsonObj(phone_number='0123-12345678')" is not valid under any of the given schemas` (see full output in the *Additional context* section)

**Expected behavior**

**Additional context**
LinkML schema
```
# test.schema.yaml
id: http://example.org/pattern
name: pattern
default_range: string

imports:
  - https://w3id.org/linkml/types

slots:
  phone:
    any_of:
      - range: AmericanPhone
      - range: GermanPhone

classes:
  Test:
    tree_root: true
    slots:
      - phone

  AmericanPhone:
    attributes:
      phone_number:
        range: string
        pattern: ^\d{3} \d{3} \d{4}$

  GermanPhone:
    attributes:
      phone_number:
        range: string
        pattern: ^0\d{3}-\d{8}$
```

Data
```
# test.yaml
phone:
  phone_number: 0123-12345678
```

Full `linkml-validate` error reporting:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/linkml/validators/jsonschemavalidator.py", line 166, in cli
    results = validator.validate_object(obj, target_class=py_target_class)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/linkml/validators/jsonschemavalidator.py", line 67, in validate_object
    return jsonschema.validate(inst_dict, schema=jsonschema_obj, format_checker=jsonschema.Draft7Validator.FORMAT_CHECKER)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/jsonschema/validators.py", line 1121, in validate
    raise error
jsonschema.exceptions.ValidationError: "JsonObj(phone_number='0123-12345678')" is not valid under any of the given schemas

Failed validating 'anyOf' in schema['properties']['phone']:
    {'anyOf': [{'$ref': '#/$defs/AmericanPhone'},
               {'$ref': '#/$defs/GermanPhone'}]}

On instance['phone']:
    "JsonObj(phone_number='0123-12345678')"
```

**Comment by Silvanoc** [comment]
I've been trying to find the root cause and this is what I've find out up to now:

1. In the function `load_source` the variable [`data_as_dict` shows the expected structure](https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/loaders/loader_root.py#L61): `{'phone': {'phone_number': '0123-12345678'}}`.
2. Later in the same function the [dictionary gets converted into a `YAMLRoot`](https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/loaders/loader_root.py#L66) resulting into an object that looks weird to me, but might be right (since I miss the point of the `JsonObj` class): `Test(phone="JsonObj(phone_number='0123-12345678')")`. Why is the value of `phone` a JsonObj, but not the whole content of `Test` itself?
3. The first hint of something broken that is clear to me is the [JSON object being returned by the `as_simple_dict` function](https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/utils/dictutils.py#L15): `{'phone': "JsonObj(phone_number='0123-12345678')"}` instead of `{'phone': {'phone_number': '0123-12345678'}}`.

My suspect is that the conversion into a `YAMLRoot` object mentioned in the point 2 is somehow misbehaving. But I haven't got to the root cause yet. Hopefully this information helps you getting to the root cause.

**Comment by Silvanoc** [comment]
Apparently the `any_of` of the schema is provoking the misbehavior. Wherever I put an `any_of` in the schema, I get the data converted into a `JsonObj` instead of a dictionary. If I replace the `any_of` with the option that corresponds the data being provided, then everything behaves as expected.

Unfortunately I miss the knowledge to better understand and diagnose what's going on to the to the root cause.

**Comment by cmungall** [comment]
Apologies for the late response and the confusing error message.

Now linkml-validate gives slightly more informative messages:

```
{'phone_number': '0123-12345678'} is not of type 'string' in $.phone
```

This is still confusing. There are some open issues about this behavior, when you try and override a string slot and turn it into an object slot it makes the schema unsatisfiable.

In fact, while non-monotonic overrides should be disallowed (and properly flagged), we should allow default-ranges to participate in an override.

The current fix for you is to omit

```
default-range: string
```

But this is fairly non-ergonomic, we will fix this.

**Comment by cmungall** [comment]
I'm closing this in favor of

-  #1483
