### ISSUE TITLE
linkml-validation fails with "TypeError: [...] argument after ** must be a mapping, not extended_str"

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#1446]
# Describe the bug

# To reproduce
1. Create base schema
<details>
  <summary>base.yaml</summary>

``` yaml
# base.yaml
id: https://example.org/base
prefixes:
  linkml: https://w3id.org/linkml/
  base: https://example.org/base/
imports:
  - linkml:types
default_prefix: base

classes:
  Animal:
    slots:
      - identifiers
  Human:
    is_a: Animal
  Identifier:

slots:
  identifiers:
    range: Identifier
    multivalued: true
``` 
 </details>

2. Create extended schema
<details>
  <summary>extension.yaml</summary>

``` yaml
# extension.yaml
id: https://example.org/extension
prefixes:
  extensions: https://example.org/extension/
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
  - base
default_prefix: extension

classes:
  Name:
    attributes:
      surname:
        range: string
  HumanIdentifier:
    is_a: Identifier
    slots:
      - name
      - birthday

slots:
  name:
    range: Name
  birthday:
    range: string
  human_identifier:
    range: HumanIdentifier
```
 </details>

3. Create a dummy derived schema:
<details>
  <summary>dummy.yaml</summary>

``` yaml
# dummy.yaml
id: https://example.org
prefixes:
  linkml: https://w3id.org/linkml/
  base: https://example.org/base/
  extension: https://example.org/extension/
imports:
  - extension
default_prefix: extension

classes:
  DummyName:
    is_a: Name
  DummyHuman:
    is_a: Human
    slot_usage:
      identifiers:
        range: PersonalIdentityCard
  PersonalIdentityCard:
    is_a: Identifier
    slots:
      - personal_number
  DummyHumanIdentifier:
    is_a: HumanIdentifier
    slot_usage:
      name:
        range: DummyName

slots:
  personal_number:
```
 </details>

4. Create data according the dummy schema that refers to an externaly hosted person identifier:
<details>
  <summary>person.yaml</summary>

``` yaml
# person.yaml
identifiers:
  - urn:uuid:a4fa0771-d270-4a3c-801b-f2e1e25e2581
```
 </details>

5. Try to validate the data against the schema: `linkml-validate --target-class DummyHuman -s dummy.yaml person.yaml`

6. Observe the error `TypeError: test.PersonalIdentityCard() argument after ** must be a mapping, not extended_str
`:
<details>
  <summary>TypeError</summary>

``` shell
Traceback (most recent call last):
  File "/opt/homebrew/bin/linkml-validate", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/linkml/validators/jsonschemavalidator.py", line 162, in cli
    obj = loader.load(source=input, target_class=py_target_class, **inargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/linkml_runtime/loaders/loader_root.py", line 85, in load
    results = self.load_any(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/linkml_runtime/loaders/yaml_loader.py", line 32, in load_any
    return self.load_source(source, loader, target_class, accept_header="text/yaml, application/yaml;q=0.9",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/linkml_runtime/loaders/loader_root.py", line 66, in load_source
    return target_class(**data_as_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "test", line 114, in __post_init__
  File "test", line 114, in <listcomp>
TypeError: test.PersonalIdentityCard() argument after ** must be a mapping, not extended_str
```
 </details>

# Expected behavior
Validation succeeds.

# About your computer
 - Version: 1.5.2

**Comment by cmungall** [comment]
Hi @Silvanoc 

Apologies for the delay

If you run this now, you get a bit of a better error message:

```
linkml-validate --target-class DummyHuman -s dummy.yaml person.yaml
✗ 'urn:uuid:a4fa0771-d270-4a3c-801b-f2e1e25e2581' is not of type 'object' in $.identifiers[0]
```

the induced range of `identifiers` is `PersonalIdentityCard`, which is a class; and this is not inlined, as it itself lacks an actual identifier.

This validates:

```
identifiers:
  - personal_number: urn:uuid:a4fa0771-d270-4a3c-801b-f2e1e25e2581
```

because personal_number is a slot on PersonalIdentityCard.

But in fact the value here is optional, so this odd list is also valid:

```
identifiers:
  - personal_number: 
```

I think making this change to the schema might achieve what you want:

```
@@ -28,3 +28,4 @@ classes:

 slots:
   personal_number:
+    identifier: true
```

This has the effect of de-inlining PersonalIdentityCard, allowing it to be referenced by its own identifier

this renders your original data example valid.

Does that make sense?

**Comment by Silvanoc** [comment]
Thanks for the answer!

Of course a `identifier: true` is missing 🤦🏻, good catch. With the error reporting that you're showing I would have had a better chance to realize it myself without bothering you.

Something that is still hurting me and I don't get the rational for is, that it has to be decided at schema level if an object is inlined or referenced. I would love to be able to inline objects and later on extract them to separate objects.

**Comment by cmungall** [comment]
Added a test case for this: #1756. 

I think having default predictable behavior for inline vs reference is good (writing client code that works in both cases is harder), but I also get that sometimes you may want to have flexibility instead, this would be a reasonable model extension request (in theory this can be done now via one_of, but this would be awkward)
