### ISSUE TITLE
Modeling Existing Database

### ISSUE THREAD

**Issue by timtrinidad** [linkml/linkml#1456]
Hello! I am trying to use linkml to create a data dictionary of existing MySQL databases.  A service may be made of different components and each component may have multiple data stores. I am trying to describe the tables/columns of each data store.

What's the best way to model this? The challenge is that I'm modeling both the data each table holds (the table columns) as well as the tables themselves (including connection metadata, database name, etc).

I have concluded that I need to use a class to represent each table, but I'm lost as to how to represent some of the other data. Here are some of the questions I have:

* **Grouping Tables in a DB**: How do I group classes hierarchically without inheritance? e.g. the `users` and `posts` table are both tables in the same database. How do I best group the two of those? Is there any way to have both of those classes share the same annotations (including connection information)?
* **Private vs Public**: I would like to indicate that some data is safe to export into a data mart, something like `public` vs `private`. What's the best way to indicate that information? Is there a way to extend the linkml spec to add that attribute to `SlotDefinition`? Is there a way to have this information displayed on the "slots" section of the generated `gen-doc` class pages, perhaps with a custom template?
* **Multiple Files**: How should I think about breaking this out into separate files/schemas and bringing them together with imports? Would it make sense to have one "Schema" per database?

Thank you in advance!

**Comment by sierra-moxon** [comment]
Hi @timtrinidad - I think the easiest way to answer this question is to take a look at some example schemas that make models that are intended for use in relational serialization.  Here's one: https://github.com/alliance-genome/agr_curation_schema.

- Grouping tables: 
   - In general, a LinkML model holds all the classes (tables) in your model (schema), whether they be in the same YAML file or modularized into several YAML files for the same model.  I've created models both ways; very modular like the schema above, broken down by domain of interest, or one big YAML like [Biolink](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml)  
   - In terms of sharing attributes between classes (tables) without inheritance, defining some mixins might be your best approach: https://linkml.io/linkml/faq/modeling.html#what-is-the-difference-between-is-a-and-mixins.  These are classes that you can define with a set of slots/attributes (columns) that when added to another class, allow that other class to also use the collection/set of slots you've defined on the mixin.  see: https://github.com/biolink/biolink-model/blob/cfd18406cb7b6d2d2e04935b159c03cf5fefdaeb/biolink-model.yaml#L6769 as an example.   

- Private vs Public: 
   -  LinkML doesn't currently support public/private disambiguation.  For example, there is no metamodel component you can use to signal the LinkML tooling to generate (public) or skip (private) classes or slots in your model.  You can use LinkML annotations to signal your downstream software to do this however.  Here's an example of annotations in practice: https://github.com/biolink/biolink-model/blob/cfd18406cb7b6d2d2e04935b159c03cf5fefdaeb/biolink-model.yaml#L1929. here we are using LinkML "annotations" metamodel component to specify which predicates in the model are of some defined type or subset.  You could also technically, use the metamodel component, `in_subset` to do this as well.  Then your downstream code would need to recognize these annotations or in_subset metadata and act accordingly.
These two metamodel components already exist on SlotDefinition objects and are available for you to use. :) 

- Multiple Files: 
  -  It depends on your use case and the preference of your schema developers.  I would argue that more modularity is better (especially when you want other people to be able to reuse your schema in their linkml schemas), but how you modularize is really use case dependent.  You can imagine modularizing by domain as in agr_curation_schema above, or via metamodel component (e.g. all the slots in one YAML file, all the enums in another, etc...). 

I hope this helps, please feel free to come to our community calls to present your work and ask more of these kinds of modeling questions!  We'd love to have you.

**Comment by timothy-trinidad-ps** [comment]
Thank you for the detailed answer! I'll definitely take a look at annotations. For some reason it didn't jump out at me as something I could use but looking at it again it looks like it may work. 

I'd be happy to share my work as well! Where do I find information about these community calls?

**Comment by sierra-moxon** [comment]
email me!  I'll add you to our slack and community calls.  find me here: http://phonebook.lbl.gov/ "sierra moxon"
