### ISSUE TITLE
RDF generation in examples.ipynb doesn't look right

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#147]
I'm not not getting an error upon RDF generation any more. See #139 

However: in the older `biolink/biolinkml/blob/master/notebooks/examples.ipynb`, the following RDF was generated:

```RDF
<http://example.org/people/42> a samp:Person ;
    foaf:age 43 ;
    foaf:firstName "Bob",
        "Joe" ;
    foaf:lastName "smith" .
```
But in this `link/linkml/blob/master/notebooks/examples.ipynb`, the generated RDF looks like this :

```RDF
[] a <file:///Users/solbrig/git/linkml/linkml/notebooks/Person> .
```

**Comment by cmungall** [comment]
Replaced by #314
