### ISSUE TITLE
add unit tests for owlgen close, narrow mappings 

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#149]
continuation of [this PR](https://github.com/linkml/linkml/pull/148). 
We'd like unit tests to help protect owlgen code from future changes.

**Comment by deepakunni3** [comment]
Thanks @sierra-moxon 😸

**Comment by nlharris** [comment]
Why is this PR still sitting here? Can it be merged or closed?

**Comment by cmungall** [comment]
Looks like this is an issue. We already have good owlgen test coverage via compliance tests
