### ISSUE TITLE
Refreshed design for LinkML validation

### ISSUE THREAD

**Issue by deepakunni3** [linkml/linkml#1494]
# Refreshed design for LinkML validation

This ticket serves as a way of capturing the design decisions for enhancing the validation functionality in LinkML.

The main goal of the validator is to take one (or more) object and validate against a given LinkML schema, while ensuring that the validator has a common interface, is configurable, and easy to extend.

After taking into consideration the functionalities of `linkml-validate` (LinkML's in-built validator) and linkml-validator (a prototype independent of linkml-validate), the proposed structure of this refreshed LinkML validation can be divided into 3 parts:
- **CLI**
- **Validators**
- **Plugins**

The flow of control is from CLI > Validator > Plugin where,
- A CLI utility is invoked from the command line
- Depending on the input, the CLI calls the appropriate validator instance
- Validator calls one or more plugins
- Each plugin generates one or more validation results
- Validator is responsible for collecting all validation results into a validation report
- Validator emits the validation report after all checks are completed for that object

## CLI

A CLI utility that enables validation via the command line. This will be quite similar to the interface proivded by `linkml-validate`.

This CLI utility is responsible for calling the appropriate validator and plugins based on input arguments.

### Input

- Input File, File URL or an endpoint
- Input Format (JSON, JSON Lines, TSV, CSV, RDF-Turtle, N Triples, etc.)
- Input Stream (I/O stream that contains objects in one of the above formats)
- Schema (schema file or schema URL)
- Generator Args (Arguments to the generator that will be used)
- Plugins + Plugin Args (Plugins to use and Arguments to the plugins)

### Output

- Output File
- Output Format
- Output Stream (I/O stream where validation results are streamed)

## Validators

Validator is responsible for dealing with:
- generation of an appropriate schema artifact
- fetching objects for validation (file or endpoint)
- serializing validation reports (file or stream)

Structure:
- `BaseValidator`: The base validation class
- `JsonschemaValidator`: Validating JSON against a JSONSchema
- `SparqlValidator`: Validating data from a SPARQL endpoint
- `TableValidator`: Validating data from a delimiter-separated file (CSV, TSV)
- ...

The different types of validator are to ensure that I/O and generation of schema artifacts are handled accordingly (plus any use-case specific optimization that might be required).

Each validator can have its own default choice of plugins and plugin arguments. But this can be overridden at runtime.

Methods for Validator:
- `init`: initialize the validator; Accepts a schema YAML, a generator instance, and generator arguments
- `validate`: for validating data
- `validate_file`: for validating data from a file
- `validate_endpoint`: for validating data from an endpoint
- `generate_artifact`: for generating the schema artifact which will be used to in validation; Makes use of the generator instance and generator arguments to create the appropriate schema artifact

### Validation Plugins

A validation plugin is responsible for:
- taking an object and running some rule/check on the object
- generates 1 or more validation results according to the outcome of the check
    - the validation result should conforms to `ValidationResult`
- can run some preprocessing before running the check, if needed; This is left to the plugin implementation
- can run some postprocessing after running the check, if needed; This is also left to the plugin implementation

Structure:
- `BaseValidationPlugin`: The base validation plugin
- `JsonschemaValidationPlugin`: for validating JSON against a JSONSchema
- `SparqlValidationPlugin`: for validating RDF triples fetched according to a derived SPARQL query
- ...

The upstream validator class is responsible for providing the plugin with the appropriate schema artifact.

As a rule of thumb,
- Plugins should **NOT** modify the incoming object or schema artifact
- Plugins **MAY** copy over the incoming object or schema artifact (`copy.deepcopy()`) for certain situations
- Plugins **MUST** return a list of `ValidationResult` instances
- The validation result must be descriptive and populated such that it is easy for interpretation

Methods for a plugin:
- `init`: Initialize the plugin; Accepts the schema artifact and plugin arguments
- `pre_process`: Any preprocessing will be invoked through this method
- `process`: Run the actual validation on the object
- `post_process`: Any postprocessing will be invoked through this method

### Normalization Plugins

A normalization plugin is responsible for applying one or more operations on the object before it is validated by a Validation Plugin.

> TODO:
> This will be after the validation plugins.
> Needs more discussion.

**Note:** The design is still a work in progress. This ticket is to collect inputs to understand if this would be the right way to go.

**Comment by deepakunni3** [comment]
CC'ing @pkalita-lbl @cmungall : Would love to hear your inputs on this :)

**Comment by deepakunni3** [comment]
Yes, you got it 100%.

The separation of concern is more evident when there are more than one plugin for a particular validator.

For example, lets assume there are some checks that JSON Schema cannot do but your data is still JSON.
You can write up another plugin that runs in addition to the `JsonschemaValidationPlugin`. This way, both plugins can use the same JSONSchema, operate on JSON data, and yet one of them is designed to perform validation that might be outside the scope of JSONSchema specification.

**Comment by cmungall** [comment]
Just a comment on:

> JsonschemaValidator: Validating JSON against a JSONSchema
> SparqlValidator: Validating data from a SPARQL endpoint
> TableValidator: Validating data from a delimiter-separated file (CSV, TSV)

I'd like to decouple the validator from the format a little bit.

It should be possible to:

- validate rdf by converting on the fly to json and running through the jsonschemavalidator
- validate json by converting it to rdf and running through a shacl/shex/sparql validator (e.g. this may catch referential integrity errors that can't be done for non-inlined references)

Of course, any transformations should be transparent and under the control of the user, since these can be a source of cryptic repairs/coercions, and may themselves yield their own validation messages.

And in some cases it makes sense to couple tightly

- there may be a mongo-based json schema validator that is optimized for mongo, so if my data is already in mongo it doesn't make sense to take out and dump and pass to a json schema validator
- if my data is already in a triplestore it may be inefficient to dump it all out if there is a sparql/shacl/shex validator that can use operations that are optimized by the engine, eg sparql queries

**Comment by deepakunni3** [comment]
After a think about couple of strategies on how to decouple the validation from input formats, here is the new proposed design.

The design can be divided into 5 parts:
- [CLI](#CLI)
- [Validator](#Validator)
- [Parsers](#Parsers)
- [Converters](#Converters)
- [Plugins](#Plugins)

```mermaid
sequenceDiagram
    linkml-validate->>+Validator: call and instantiate the validator
    Validator->>+Parser: sends input data to an appropriate parser
    Parser->>+Validator: returns parsed data
    Validator->>+converter: sends parsed data to an appropriate converter method
    converter->>+Validator: returns converted data
    Validator->>+Validation Plugin: sends the schema artifact and converted data to the plugin
    Validation Plugin->>+Validator: returns a list of validation results
    Validator->>+linkml-validate: prepares and returns a validation report
```


The flow of control is from CLI > Validator > Parser > converter > Plugin where,
- A CLI utility is invoked from the command line
- Depending on the input, the CLI calls the Validator
- Depending on the input format, the Validator calls the appropriate Parser
- The Parser parses the data and returns the parsed data
- If conversion is required (or specified) then Validator calls the appropriate converter method
- The converter method converts the data and returns the converted data
- Validator calls one or more plugins
- Each plugin generates one or more validation results
- Validator is responsible for collecting all validation results into a validation report
- Validator returns the validation report after all checks are completed for that object


## CLI

A CLI utility that enables validation via the command line. This will be quite similar to the interface provided by `linkml-validate`.

This CLI utility is responsible for calling the validator based on input arguments.

Has one or more commands that does a specific type of validation:

- `jsonschema-validation`: converts any input to JSON and validates against JSONSchema
    - calls the Validator and passes all the required arguments
    - Validator calls an appropriate parser based on input format
    - Validator transforms input data into JSON by calling the appropriate converter method
    - Validator generates the schema artifact from the schema YAML, in this case JSON Schema
    - Validator calls one or more validation plugins that operate on JSON
    - Validator returns the validation report
- `shacl-validation`: converts any input to RDF and validates against SHACL shapes
    - calls the Validator and passes all the required arguments
    - Validator calls an appropriate parser based on input format
    - Validator transforms input data into RDF by calling the appropriate converter method
    - Validator generates the schema artifact from the schema YAML, in this case SHACL shapes
    - Validator calls one or more validation plugins that operate on RDF
    - Validator returns the validation report
- ...


### Input

- Input File, File URL or an endpoint
- Input Format (JSON, JSON Lines, TSV, CSV, RDF-Turtle, N Triples, etc.)
- Input Stream (I/O stream that contains objects in one of the above formats)
- Schema (schema file or schema URL)
- Generator + Generator Args (Arguments to the generator that will be used)
- Plugins + Plugin Args (Plugins to use and Arguments to the plugins)

### Output

- Output File
- Output Format
- Output Stream (I/O stream where validation results are streamed)


## Parsers

A parser is responsible for parsing input data.

The parser **MAY** do some clever translations that are linkml aware
such that the incoming data can be brought into a form that can work better with validation.

Structure:
- `BaseParser`: The base parser class
- `JsonParser`: The parser for parsing JSON data
- `RdfParser`: The parser for parsing RDF data
- `SparqlParser`: The parser for fetching data from a SPARQL endpoint
- `MongoParser`: The parser for fetching data from a MongoDB instance

In addition to typical formats, parsers can also be use-case and technology specific.
Any optimizations required to fetch the data from such technology specific instances is left to parser implementation.


Methods for parser:
- `init`: initialize the parser; Accepts input file, input format, schema YAML, and parser args
- `parse`: this is where the incoming data is parsed


As a rule of thumb, parsers should support streaming. i.e. each parser is responsible for emitting one record/object/triple.


## Converter

A converter is a method responsible for converting input data into an appropriate form.

The converter should not modify the incoming data object. Instead, it should created a new object and operate on that.

The converter **CAN** do some clever transformation that are linkml-aware such that the incoming data can be brought into a form that can work better with validation, especially if the target format requires format-specific transformations.

The converter method should accept the following arguments:
- `data`
- `format`
- `schema`
- `kwargs`

## Validator

Validator is responsible for dealing with:
- generation of an appropriate schema artifact
- fetching objects for validation (file or endpoint) by calling the appropriate parser and the appropriate converter (if transformation is required)
- call validation plugins and collect validation results
- serialize validation reports (file or stream)

There is only one Validator class and this is a key interface for performing validation.

From the Validator standpoint,
- the parser is flexible
- the converter is flexible
- the generator is flexible
- the plugins are flexible 

This is because the Validator is designed to be generic and the specifics are determined by the combination of parser, converter, generator, and plugins.


Methods for Validator:
- `init`: initialize the validator; Accepts a schema YAML, a generator instance, and generator arguments
- `validate`: for validating data
- `generate_artifact`: for generating the schema artifact which will be used to in validation; Makes use of the generator instance and generator arguments to create the appropriate schema artifact


## Plugins


### Validation Plugins

A validation plugin is responsible for:
- taking an object and running some rule/check on the object
- generates 1 or more validation results according to the outcome of the check
    - the validation result should conforms to `ValidationResult`
- can run some preprocessing before running the check, if needed; This is left to the plugin implementation
- can run some postprocessing after running the check, if needed; This is also left to the plugin implementation

Structure:
- `BaseValidationPlugin`: The base validation plugin
- `JsonschemaValidationPlugin`: for validating JSON against a JSONSchema
- `SparqlValidationPlugin`: for validating RDF triples fetched according to a derived SPARQL query
- ...

The upstream validator class is responsible for providing the plugin with the appropriate schema artifact.

The plugin is not responsible for transforming incoming data into an appropriate format. This is the job of the converter.

As a rule of thumb,
- Plugins should **NOT** modify the incoming object or schema artifact
- Plugins **MAY** copy over the incoming object or schema artifact (`copy.deepcopy()`) for certain situations
- Plugins **MUST** return a list of `ValidationResult` instances
- The validation result must be descriptive and populated such that it is easy for interpretation


Methods for a plugin:
- `init`: Initialize the plugin; Accepts the schema artifact and plugin arguments
- `pre_process`: Any preprocessing will be invoked through this method
- `process`: Run the actual validation on the object
- `post_process`: Any postprocessing will be invoked through this method


### Normalization Plugins

A normalization plugin is responsible for applying one or more operations on the object before it is validated by a Validation Plugin.

> TODO:
> This will be after the validation plugins.
> Needs more discussion.

**Comment by pkalita-lbl** [comment]
The latest proposal make sense to me. 

I guess the one thing that we'll need to think about a little bit is the validation report / result objects. There are at least a few different ideas already floating around: 

* [From linkml-model](https://github.com/linkml/linkml-model/blob/0228f50c7f4377fb6ce0bcb0af5a225c1f887177/linkml_model/model/schema/validation.yaml) I'm not sure this is actually used anywhere
* [In linkml itself](https://github.com/linkml/linkml/blob/c767e2f5671a2946d79612a67b330d4da89abccd/linkml/reporting/model.py) Oddly I'm not sure where the actual schema source YAML file is, but it is used by the existing `SparqlDataValidator` class.
* [In linkml-validator](https://github.com/linkml/linkml-validator/blob/main/linkml_validator/models.py)

The first two seem a bit too geared toward RDF data. The linkml-validator one seems a little closer to what I would expect, at least as a first pass. Maybe there are more specialized report subclasses at some point in the future. 

Anyway, I think this might a good time to start a branch where I tear down the existing JSON Schema-based validation code and put it back together following the outline here.

**Comment by deepakunni3** [comment]
Yes, I think there needs to be a broader discussion about the validation reports.
But we can try something with what we have in the linkml-model specification (`validation.yaml`).

I started a first stab at this as part of a hackathon.
I'll make a draft PR soon so that you can see how the proposal maps to the implementation.
Would love to get your inputs on the draft PR once its ready :)

**Comment by pkalita-lbl** [comment]
Thanks for pushing that up. I've also started working on a branch to try and get the implementation started, but I haven't pushed it up quite yet. A lot of what's in #1514 looks familiar from https://github.com/linkml/linkml-validator 😁. I don't mean that as a negative; I've been referring to that code as well!

One thing that I was also hoping to accomplish with the refactor was to also focus on the user experience outside of the CLI, as well. In particular I was envisioning a progression from one simple (but opinionated and less configurable) function (i.e. here's my schema, here's an instance, is it valid?) all the way up to using composable classes to really fine tune the behavior. I also wanted to make sure that at the "power-user" end of that spectrum everything is based on iterators so that we keep the door open to validating very large datasets.

**Comment by deepakunni3** [comment]
Yes it is very similar to linkml-validator :D 
I wanted to pull the useful parts into the main linkml while still keeping the proposed design in mind.

+1 for user experience outside of CLI. I am also leaning in the direction you are suggesting. Yes, an opinionated and less configurable function exposed via CLI for simple use cases. But sufficiently configurable for any user for any use-case. 

And focusing on the advanced use cases can help us really think about how the base design ought to be. 

Regarding iterators - Yes, I definitely share your vision of building the validator for power users. I sort of started in that direction by ensuring that the parsers yield iterators so that it is possible to parse large input data.
Of course the same sort of design has to be done for the converters and the Validator class.

But if you have a different take on how the different components are plugging into one another then would definitely like to hear more about that :)
It is entirely possible that I am missing some use cases for validation and I don't want the design to be a limiting factor 😅

**Comment by deepakunni3** [comment]
And regarding the model for validation reports: It is quite confusing since there are 2 validation models in linkml and 1 from linkml-validator repo. The one in linkml-validator repo was written quickly for reporting JSON validation errors. It is fairly easy to work with but may not be compatible with RDF based inputs. 

The way @cmungall explained it few months ago, the validation model in linkml_runtime is the same as the one in oak (https://github.com/INCATools/ontology-access-kit/blob/main/src/oaklib/datamodels/validation_datamodel.yaml) or at least it should be.

I thought the models in https://github.com/linkml/linkml/blob/c767e2f5671a2946d79612a67b330d4da89abccd/linkml/reporting/model.py was used for ReferenceValidator for reporting errors when validating the linkml schema against the linkml specification (or I completely misunderstood the purpose of the ReferenceValidator).

I was trying my best to use the validation models (from `linkml_runtime.linkml_model.validation`) as part of this redesign.
But the dataclasses currently packaged in linkml_runtime is broken since there are missing imports in `linkml_runtime/linkml_model/validation.py` which gets in the way of using the classes. But I am sure this is a quick fix.

I think its possible to adapt the linkml_runtime validation models according to our use case. I really like your idea of specialized report subclasses.

**Comment by pkalita-lbl** [comment]
Okay I've pushed my initial attempt here: #1517 

It only covers loading JSON data and validating using a JSON Schema validator but I think that's enough to illustrate the design patterns. A few main differences from #1514:

* I replaced the terminology `Parser` with `Loader`, but they fulfill the same role. I don't know why but "Loader" just made more sense to me. Maybe because `linkml-runtime` has things called [loaders](https://github.com/linkml/linkml-runtime/tree/main/linkml_runtime/loaders). And also perhaps because looking down the road to getting data from a SQLite file or a MongoDB connection, "loader" seems more apt in that context.
* In #1514 the `Validator` class constructs plugin instances based on class name strings and argument dicts. This didn't sit quite right with me. In the changes here you pass fully constructed `ValidationPlugin` subclass instances to the `Validator`. When a particular plugin needs something that's shared between all the plugins (e.g. the schema or an artifact generated from it) it gets it from a `ValidationContext` instance which the `Validator` constructs and passes to the plugins at validation time.
* At the lowest levels (i.e. `Loader.iter_instances` and `Validator.iter_results`) everything is iterator based to keep open the possibility of validating large datasets. Higher level convenience methods (i.e. `Validator.validate`) will materialize those iterators into lists.
* A top-level `validate` function is provided to fulfill the "90% use case". Right now it just does JSON Schema validation against a dict. This is for people who don't want to think about plugin configuration, loaders, iterators and all that nonsense. It's just: here's an instance, is it valid?
* I'm punting on designing a better `ValidationResult` object for now. In fact I've made it even simpler than what's in #1514. I get the sense that Chris has some thoughts about how to standardize between this and OAK so I think we can circle back to this after we talk to him.

Hopefully the tests make it pretty clear how this stuff is intended to be used. Any feedback is appreciated!

**Comment by deepakunni3** [comment]
Sorry for the late response. Took some time to get to review your PR.

Looks great! I am super glad that the design seems to be feasible and we both have implemented it in similar manner :) 

- I like the idea of renaming Parser as Loader. This is much more in line with its intent.
- Yes, the class name string for plugins was a way to provide users to refer to the plugins via the CLI. But maybe this is not a necessary use case
- Love the idea of iterators everywhere. Definitely something we should think about from the very beginning :+1:
- Yes, the top level `validate` is definitely going to be the most commonly used scenario
- I agree with the models. We do need Chris' clarification and we do want to make sure that the validation results can be parsed or worked on via OAK (for some downstream operations)

Since there are two PRs now, lets make sure we streamline our efforts :)

Your PR is much more consistent with the overall linkml code-style at the moment. I am more than happy to retire my PR and add functionalities to the one you created.

It would be great if you and I could come up with a list of tasks such that we can distribute them amongst us. That way, we can focus on the critical components and get this redesign moving forward.

**Comment by pkalita-lbl** [comment]
> It would be great if you and I could come up with a list of tasks such that we can distribute them amongst us. That way, we can focus on the critical components and get this redesign moving forward.

Absolutely. That sounds like a great way to proceed.

> Yes, the class name string for plugins was a way to provide users to refer to the plugins via the CLI. But maybe this is not a necessary use case

I'm sure you noticed that my PR doesn't touch the CLI piece yet. I wanted to focus on having a good programmatic API first and then layer the CLI on top of that later. I'm sure, though, that the CLI will need to do some plugin construction from CLI argument strings, but hopefully that can be isolated to the CLI layer.

**Comment by cmungall** [comment]
Regarding the validation data model - I would not worry too much about adhering strictly to the OAK one. It would be good to keep the SHACL URIs for the different constraint types. I do think it would be good to open up the discussion on the validation data model, and also to ensure that it's compatible with Valve (cc @jamesaoverton)

**Comment by jamesaoverton** [comment]
I'm very happy to coordinate on this. We currently use VALVE from Rust or the CLI, but we have Python bindings in development <https://github.com/ontodev/valve.py>.

My worry with the design discussed here is that it's focused on pass/fail validation of full datasets. I need to work with messy data and guide users towards making it less of a mess.

Regarding reporting of validation results, for VALVE we currently have 

- message ID
- coordinates: we use [table, row, column] but could be [table, cell] where cell is in A1 syntax like a spreadsheet, or [subject, predicate, object] for RDF
- value: we've found it's helpful to repeat the cell value, but this is debatable
- rule: a name for the rule, preferably a CURIE
- level: ERROR, WARN, ...
- message: for the user, should be actionable

We will probably add an 'agent' column: who/what generated the message. This would be good for filtering.

I'm considering adding a datetime, but not sure.

**Comment by pkalita-lbl** [comment]
Next step tasks focused on achieving parity with existing validation classes:

- [ ] https://github.com/linkml/linkml/issues/1553
- [ ] https://github.com/linkml/linkml/issues/1554
- [ ] https://github.com/linkml/linkml/issues/1555
- [ ] https://github.com/linkml/linkml/issues/1556

**Comment by cmungall** [comment]
@pkalita-lbl your checklist is a bit buried at the bottom of the issue - and I think many should be ticked off. Are we ready to close this?

**Comment by cmungall** [comment]
Calling this one done, we may open more granular issues, e.g. for CLI and adding docs
