### ISSUE TITLE
Link is broken in docs (on https://linkml.io/linkml/data/csvs.html#container-objects)

### ISSUE THREAD

**Issue by rly** [linkml/linkml#1535]
**Describe the bug**
On this page https://linkml.io/linkml/data/csvs.html#container-objects
the link for the text "[part 2 of the tutorial](https://linkml.io/linkml/data/csvs.html#../intro/tutorial02.html)" is broken.

Related: it may be useful to add the `sphinx linkcheck` command to your CI to run nightly and/or on each PR to catch broken external links like this. See what we have done in HDMF here: https://github.com/hdmf-dev/hdmf/blob/dev/.github/workflows/check_external_links.yml

**Comment by rly** [comment]
I'm happy to fix the link and add the workflow in a PR if you all think it is a good idea.

**Comment by cmungall** [comment]
That would be awesome!
