### ISSUE TITLE
update pydantic to v2.0

### ISSUE THREAD

**Issue by ialarmedalien** [linkml/linkml#1545]
[pydantic 2.0](https://github.com/pydantic/pydantic) is now out, with various fixes and improvements, plus [some breaking changes to the API](https://docs.pydantic.dev/2.0/migration/). v1.x ships as part of v2, so it's possible to update the pydantic package to the latest version and continue to use v1 under the hood, e.g.

```py
from pydantic.v1 import BaseModel
```

That also makes incremental conversion to the full 2.0 API much easier.

Since package managers like poetry will report incompatibility in dependencies if you have packages that rely on v1 and v2, the best update policy (assuming that linkml wants to migrate to v2 at some point) would be to update all the pydantic-using/requiring linkml repos to use v2 at once, ideally with a version bump.

**Comment by cmungall** [comment]
Thanks, agreed!

linkml-runtime is now unpinned:

- https://github.com/linkml/linkml-runtime/pull/272

I think this could cause problems with repos that include generated pydantic models? This should be resolvable in the short term by those repos pinning to v1. (or by providing an easy way of modifying the imports as above)

But I think what we need to do ASAP is modify pydanticgen to allow pydantic2 natively.

It's unfortunate that the python import system forces us to walk lockstep in this way...

**Comment by sierra-moxon** [comment]
We support both v1 and v2 now; as a next step, we can set our dev default to v2, but we're not quite there yet.  Closing as complete.
