### ISSUE TITLE
Add CLI layer for new Validator class

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1554]
I think the trickiest part of this will be designing an intuitive way for users to specify what validation plugins should be used and provide any necessary plugin-specific options to them. It might make more sense for us to have a few more validation plugins in place before tackling this part of the refactor.

**Comment by cmungall** [comment]
FWIW I like the plugin mechanism in the python llm package https://llm.datasette.io/en/stable/plugins/index.html

**Comment by pkalita-lbl** [comment]
Duplicate of https://github.com/linkml/linkml/issues/1658
