### ISSUE TITLE
Design and implement new validation report and result classes for new Validator class to use

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1555]
Currently the new `Validator` and related plugin classes uses pretty simple `ValidationReport` and `ValidationResult` classes. The report simply holds a collection of results and each result has a minimal amount of information:

```python
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel


class Severity(str, Enum):
    """
    Enum to represent the severity of a validation message.
    """

    FATAL = "FATAL"
    ERROR = "ERROR"
    WARN = "WARN"
    INFO = "INFO"


class ValidationResult(BaseModel):
    """
    ValidationResult represents the results of validation
    by a plugin.
    An individual result arising from validation of a data instance using a particular rule
    """

    type: str
    severity: Severity
    message: str
    instance: Optional[Any]
    instantiates: Optional[str]


class ValidationReport(BaseModel):
    """
    ValidationReport represents the result of all types of
    validation for a given object.
    A report object.
    """

    results: List[ValidationResult]
```

This issue is to take a closer look at this and decide:

* What should be added/removed from what exists right now
* Whether certain plugins might want to yield subclasses of `ValidationResult`
* Are these compatible with other tools in our ecosystem

See prior discussions here:

* https://github.com/linkml/linkml/issues/368
* https://github.com/linkml/linkml/issues/911
* https://github.com/linkml/linkml/issues/1494

**Comment by glass-ships** [comment]
So (thanks to patrick for the explanation!) currently, a successful (no error) validation returns an empty ValidationReport, and a validation with errors returns one with a populated list. 

It may be helpful to have non-error validations still return a populated list, but with severity of INFO and a message saying "Validation successful" or "No errors found", something along those lines. 

Another option would be to add documentation that an empty list means no errors were found during validation.

**Comment by dalito** [comment]
@glass-ships - Linting (feedback on style) should be probably separate from validation. I have not yet heard of a LinkML linter.

**Comment by turbomam** [comment]
https://linkml.io/linkml/schemas/linter.html

**Comment by nlharris** [comment]
So is this done?

**Comment by pkalita-lbl** [comment]
Not specifically, but at this point I sort of feel like the ship has sailed on doing a cohesive design of the classes. We'll probably just move forward doing incremental improvements as people bring forward use cases.
