### ISSUE TITLE
Compliance tests take a long time to run using standard github actions setup

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1565]
With the introduction of the compliance tests in #1551 and the switch to activating them using pytest in  #1563, CI now takes around 1hr, which is not ideal.

Some options:

1. leave as-is and live with slow tests
2. switch off all compliance tests at CI time and leave developers to run them
4. only test a portion of the matrix at CI time
    - I suspect any generator involving rdflib may be an offender
5. make the compliance tests a bit smarter
    - run in parallel (will take some refactoring due to the in-memory caching)
    - reduce I/O
6. Have some smart triggering mechanism - e.g. if genX.py doesn't change don't rerun tests for X
    - not guaranteed to catch everything, but maybe a good compromise, we could still run the complete suite outside CI
7. Look for overall optimizations (schemaview, schemaloader are likely candidates)
8. do the full test on our own Jenkins CI (but keep integrated with actions)
9. Pay for bigger cloud CI machines

Many of these are not mutually exclusive

1 is not ideal longer term, especially as we want to add to the compliance suite. At the same time, the tests have always been slow so I figure we have a bit of time to decide, pending feedback from the whole dev team

**Comment by pkalita-lbl** [comment]
I discovered that a good chunk of time is spent doing SSL handshaking as the `linkml:types` import is processed (i.e. downloaded from `https://w3id.org/linkml/types.yaml`). Inlining those type definitions in `tests/test_compliance.helper._make_schema` reduced the runtime (on my machine) of `test_boolean_slot_compliance.py` from 32.56s to 16.61s. I'll keep profiling and see if there are other obvious hot spots.

**Comment by cmungall** [comment]
Good catch. I think this is only non sv generators. We should fix more
generally but pre merging the imports closure is definitely the best
immediate action

**Comment by cmungall** [comment]
I think this has vastly improved
