### ISSUE TITLE
Initial data.yaml doesn't validate in tutorial.

### ISSUE THREAD

**Issue by amc-corey-cox** [linkml/linkml#1570]
**Describe the bug**
In the first part of the tutorial the first data.yaml section does not validate for me. I get the error `32 is not of type 'string' in $.persons[0].age`.

**To reproduce**
1. Go to https://linkml.io/linkml/intro/tutorial01.html
2. Follow the tutorial instructions creating the schema and `data.yaml`.
3. Validate `data.yaml`: 
```
linkml-validate -s personinfo.yaml data.yaml`
```
4. See error:
```
32 is not of type 'string' in $.persons[0].age
```

**Expected behavior**
The example `data.yaml` should properly validate.

**About your computer (if applicable, please complete the following information):**
 - OS: Ubuntu 22.04, using bash command line.

**Additional context**
All that it requires is to put 32 in quotes to enforce text encoding. I'd be happy to drop a quick patch but I can't figure out where the linkml-tutorial lives within the project. If you can give me a pointer this is super easy.

**Comment by amc-corey-cox** [comment]
may be a duplicate of:
https://github.com/linkml/linkml/issues/1540

**Comment by amc-corey-cox** [comment]
This is related to https://github.com/linkml/linkml/issues/1042 but I think it is a more specific and simpler issue.

**Comment by sierra-moxon** [comment]
Hi @amc-corey-cox - tutorial lives in: 
https://github.com/linkml/linkml/blob/main/docs/intro/tutorial01.md

**Comment by amc-corey-cox** [comment]
I have a quick-fix that deals with the simple issue documented here. I haven't taken the effort to tackle the larger issue linked in #1042. I'll try to get a PR for this next week unless people think we should resolve this with the larger issue.

**Comment by amc-corey-cox** [comment]
In looking more closely. This one has actually been done! Hooray!
