### ISSUE TITLE
When generating UML fragments, utilize the inline property to determine horizon

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#158]
currently the yUML fragment generation goes "one hop" to neighboring classes.

Sometimes it can be useful to see things two hops or 3 hops away.

Setting a threshold too high will yield hairballs

However, the inline property serves as a good guide as to what to expand. Intuitively, the UML fragment will map to the fragment of JSON in an export.

**Comment by sierra-moxon** [comment]
closing for now; focus is on mermaid.
