### ISSUE TITLE
Model documentation should be more stable

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1590]
[Recently](https://github.com/linkml/linkml/pull/1587) we ran into an issue where some totally reasonable changes went into the `main` branch of `linkml-model` and that in turn caused snapshot tests in `linkml` to immediately start failing.

This was because many tests work with schemas that import `linkml:types`. This in turn fetches the type definition YAML file from `https://w3id.org/linkml/types.yaml`, which redirects to `https://linkml.io/linkml-model/linkml_model/model/schema/types.yaml`, which is deployed with the `linkml-model` documentation. That deployment happens on every commit to `main` in the `linkml-model` repo. 

Arguably we should be writing our tests to only do local imports of the metamodel, but this is not strictly a testing issue. Any schema that imports from the the `linkml` namespace is potentially exposed to unexpected changes like this. 

I would propose the following:

* `https://linkml.io/linkml-model/stable/linkml_model` is updated when a new `linkml-model` release is made and reflects the latest release
* `https://linkml.io/linkml-model/latest/linkml_model` is updated on each commit to `main` in `linkml-model`
* `https://linkml.io/linkml-model/vX.Y.Z/linkml_model` is a permalink copy of the latest and all previous releases
*  `https://linkml.io/linkml-model/linkml_model` redirects (or symlinks or is a copy of, whatever makes sense technically) of `https://linkml.io/linkml-model/stable/linkml_model`

The same scheme would apply to `https://linkml.io/linkml-model/docs` as well.

**Comment by sierra-moxon** [comment]
this echoes what we do in biolink (somewhat, at least with the 'latest' branch). 👍
