### ISSUE TITLE
Make closed state of SHACL shapes configurable

### ISSUE THREAD

**Issue by anjastrunk** [linkml/linkml#1592]
**Is your feature request related to a problem? Please describe.**
linkML generated all SHACL shapes as closed shapes, except of Mixin shapes and shapes, that have a parent class. See [shaclgen.py#L66](https://github.com/linkml/linkml/blob/main/linkml/generators/shaclgen.py#L66). Closed shapes do not allow additional attributes. However, there are uses cases, which want to allow additional attributes in shapes. 

**Describe the solution you'd like**
Extend CLI with an additional optional parameter to configure ```closed``` state of SHACL shapes.

**How important is this feature?** 
• Medium - can do work without it, by e.g. adding a post-generating procedure to remove ```sh:closed true``` from SHACL shapes
• Furthermore making closed state of SHACL shapes is a simple task

**When will use cases depending on this become relevant?**
• Short-term - 2-4 weeks

**Additional context**
I already provided a fix for this feature.

**Comment by nlharris** [comment]
Thank you for making a PR, @anjastrunk! Someone will review it soon.

**Comment by cmungall** [comment]
Thanks!

In future this kind of thing will be less necessary as we make openness/extensibility a first class metamodel element:

- #1595 

But for now this PR is very welcome!
