### ISSUE TITLE
Attribtues with classes as ranges are generated as Blank Nodes

### ISSUE THREAD

**Issue by anjastrunk** [linkml/linkml#1596]
**Describe the bug**
Assuming an attribute's range is a class, like for `persons` in class `Container` in the following example: 

```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  ex: https://w3id.org/linkml/examples/personinfo/
imports:
  - linkml:types
default_range: string
default_prefix: ex
  
classes:
  Person:
  Container:
    tree_root: true
    attributes:
      persons:
        multivalued: true
        inlined_as_list: true
        range: Person

```

Shacl generator will create Container's attribute `persons` as **Blank Node**.  `gen-shacl person.yaml` will result in 
 
<pre><code>
@prefix ex: &#60;https://w3id.org/linkml/examples/personinfo/> .
@prefix rdf: &#60;http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: &#60;http://www.w3.org/ns/shacl#> .
@prefix xsd: &#60;http://www.w3.org/2001/XMLSchema#> .

ex:Container a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:class ex:Person ;
            <strong>sh:nodeKind sh:BlankNode</strong> ;
            sh:order 0 ;
            sh:path ex:persons ] ;
    sh:targetClass ex:Container .

ex:Person a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:targetClass ex:Person .

</pre></code>

This causes validation of valid json-ld description of `Container` instances to fail. 

**To reproduce**
1. Generate Shacl shapes for person.yaml (see above). You will receive the following shacl shapes:

<pre><code>
@prefix ex: &#60;https://w3id.org/linkml/examples/personinfo/> .
@prefix rdf: &#60;http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: &#60;http://www.w3.org/ns/shacl#> .
@prefix xsd: &#60;http://www.w3.org/2001/XMLSchema#> .

ex:Container a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:class ex:Person ;
            sh:nodeKind sh:BlankNode ;
            sh:order 0 ;
            sh:path ex:persons ] ;
    sh:targetClass ex:Container .

ex:Person a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:targetClass ex:Person .

</pre></code>

2. Go to [shacl playground](https://shacl.org/playground/) and validate the following instance of class `Container`

```json
{
{
    "@context": { 
        "ex": "https://w3id.org/linkml/examples/personinfo/" },
  "@graph": [
   {
    "@id": "http://example.org/ns#container",
    "@type": ["ex:Container"],
    "ex:persons":
     {
       "@id": "http://example.org/ns#Bob",
       "@type": "ex:Person"
     }
   }   
]
}
```
You will receive a `NodeKindConstraintComponent` validation, indicating, that attribute `persons` does not have node kind `sh:BlankNode`. However. container instance is valid and MUST not result in validation errors.

```
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:NodeKindConstraintComponent ;
	sh:sourceShape _:n374 ;
	sh:focusNode <http://example.org/ns#container> ;
	sh:value <http://example.org/ns#Bob> ;
	sh:resultPath ex:persons ;
	sh:resultMessage "Value does not have node kind sh:BlankNode" ;
] .
```
**Expected behavior**
Do not set attributes with classes as range to Blank Nodes.  `gen-shacl erson.yaml` should result in 
 
<pre><code>
@prefix ex: &#60;https://w3id.org/linkml/examples/personinfo/> .
@prefix rdf: &#60;http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: &#60;http://www.w3.org/ns/shacl#> .
@prefix xsd: &#60;http://www.w3.org/2001/XMLSchema#> .

ex:Container a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:class ex:Person ;
            sh:order 0 ;
            sh:path ex:persons ] ;
    sh:targetClass ex:Container .

ex:Person a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:targetClass ex:Person .e ) ;
    sh:targetClass ex:Person .
</pre></code>

**Additional context**
I already provided a fix for this bug.

**Comment by turbomam** [comment]
Hi @anjastrunk I dislike blank nodes too but possibly for other reasons. I have almost no experience with SHACL, and I'm more used to looking at TTL instances than JSON-LD, so please excuse me if I get something wrong here.

If the Person class doesn't have a slot with `identifier: true`, then it won't be possible to generate a URI for it, so doesn't it have to be a blank node?

**Comment by anjastrunk** [comment]
@turbomam You are right. I didn't notice key `identifier`, thanks for pointing this out. I just tried to figured out, why my instances are not validated correctly. Key element `identifier` solved my problem. :-)

**Comment by cmungall** [comment]
Hi @anjastrunk did you mean to reopen? I think things are working as expected here?

**Comment by anjastrunk** [comment]
> Hi @anjastrunk did you mean to reopen? I think things are working as expected here?

No, I don't think things are working as expected. I tried to set slots to `identifier: true`. It worked well, if  a class has **ONE** attribute, which acts as identifier. But this is not always the case. Sometimes a combination of slots acts as identifier. Furthermore, there is no need for an explicitly defined identifier attribute. Objects can uniquely identified with keyword `@id`.

**Comment by vincentkelleher** [comment]
Hi @cmungall @anjastrunk @turbomam,

When looking at this issue, I would identify replacing `sh:BlankNode` by `sh:BlankNodeOrIRI` in this case.

You can try this on Shacl Playground with the following elements

**Shacl Shape**

```turtle
@prefix ex: <https://w3id.org/linkml/examples/personinfo/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:Container a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:class ex:Person ;
            sh:nodeKind sh:BlankNodeOrIRI ;
            sh:order 0 ;
            sh:path ex:persons ] ;
    sh:targetClass ex:Container .

ex:Person a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:targetClass ex:Person .
```

**IRI Data Graph**

```json
{
  "@context": {
    "ex": "https://w3id.org/linkml/examples/personinfo/"
  },
  "@graph": [
    {
      "@id": "http://example.org/ns#container",
      "@type": [
        "ex:Container"
      ],
      "ex:persons": {
        "@id": "http://example.org/ns#Bob",
        "@type": "ex:Person"
      }
    }
  ]
}
```

**Blank Node Data Graph**

```json
{
  "@context": {
    "ex": "https://w3id.org/linkml/examples/personinfo/"
  },
  "@graph": [
    {
      "@id": "http://example.org/ns#container",
      "@type": [
        "ex:Container"
      ],
      "ex:persons": {
        "@type": "ex:Person",
        "name": "Bob"
      }
    }
  ]
}
```
