### ISSUE TITLE
Does LinkML support contextual linking?

### ISSUE THREAD

**Issue by willitnot** [linkml/linkml#1628]
Would like to define a relationship between a relationship and an entity or between a relationship and another relationship. Is this supported?

**Comment by cmungall** [comment]
Strictly speaking linkml knows nothing about entities or relationships. The
data model is just instances and slot value assignments. You can model
relationships as instances. And there ways to make your intentions more
explicit… hold tight we will have some docs soon, for now you could look at
Biolink as an example

**Comment by joylix** [comment]
This is actually similar to the so-called hyperedge in rdf-star (also rdf 1.2), like:  
<<:Bob :met :Jane>> :venue :London;   :date '2008-08-08' .

**Comment by sierra-moxon** [comment]
@joylix @willitnot - can you say a little bit more (or give examples of) the domain you want to model here?  I could point you to biolink examples, or we could discuss further which serializations are most affected by relationship-relationship modeling you want to do?

I'll go ahead and close this issue if you already have found what you need? :)

**Comment by nlharris** [comment]
Since there was no response from the person who asked, I'm closing this issue - please reopen (and answer Sierra's question) if you still need an answer.
