### ISSUE TITLE
Edit buttons on https://linkml.io/linkml-registry/ go to "master" rather than "main"

### ISSUE THREAD

**Issue by nlharris** [linkml/linkml#1634]
e.g. if you click "Edit on GitHub" on https://linkml.io/linkml-registry/ it goes to https://github.com/linkml/linkml-registry/edit/master/docs/index.md (should be https://github.com/linkml/linkml-registry/edit/main/docs/index.md)

I thought this would be easy for me to find and fix, but I can't actually figure out where those "Edit on GitHub" links are being generated -- they don't seem to be in this repo. Maybe they come from readthedocs or something.

**Comment by cmungall** [comment]
See the fix for schemasheets in mkdocs.yml here https://github.com/linkml/schemasheets/issues/47
