### ISSUE TITLE
some LinkML projects intolerant of Pydantic 2:  cannot import name 'ENCODERS_BY_TYPE' from 'pydantic.json'

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1643]

**Comment by cmungall** [comment]
This works for me:

` poetry run sheets2linkml tests/input/personinfo.tsv`

**Comment by turbomam** [comment]
Thanks.

Maybe I should have said "...sheets2linkml CLIs are failing in nmdc-schema and the MIxS 6.2 RC after running `poetry update`"

**Comment by turbomam** [comment]
I can definitively say that `make all` completes in https://github.com/GenomicsStandardsConsortium/mixs6.2_release_candidate/pull/25 when importing linkml-runtime 1.5.5 but not when importing linkml-runtime 1.5.6.

This first shows up in mixs6.2_release_candidate's `write-mixs-linkml`. I'm trying to demonstrate that it effects schemasheet CLIs too now.

**Comment by turbomam** [comment]
Maybe from 

> Updating pydantic (2.4.2 -> 1.10.13)

**Comment by turbomam** [comment]
Holding pydantic back to 1.10.13 seems to the the solution for my poorly articulated problem. As in, my project will run with any  dependencies as long as pydantic is held back. I'm double checking now.

**Comment by cmungall** [comment]
#1641

**Comment by turbomam** [comment]
> #1641

OK, that's helpful to see more context.

I have been regularly deleting and reconstructing my poetry.lock files while debugging this. Should I be concerned about lockfile staleness, or is not not the relevant part of that issue in my case?
