### ISSUE TITLE
Add CLI entry point for new validator package

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1658]
The new validator infrastructure has a [CLI module](https://github.com/linkml/linkml/blob/594f2af72c9291c7e31f9a45a727fab8f7f43a88/linkml/validator/cli.py), but it is not yet connected to an [entry point](https://github.com/linkml/linkml/blob/594f2af72c9291c7e31f9a45a727fab8f7f43a88/pyproject.toml#L50). 

We should probably consider how we'd like to transition to the new CLI because it's not a drop-in replacement for the old one. Some ideas:

1. Create a new entry point (called? I don't know? Something like `linkml-validate-next`?). Then at some point in a future release the `linkml-validate` entry point gets connected to the new CLI module. 
2. Keep only one entry point (`linkml-validate`) and use an environment variable to control which module gets used under the hood. So `linkml-validate ...` continues to give you the current behavior, but `FUTURE_VALIDATOR=1 linkml-validate ...` gives you the new one.

**Comment by cmungall** [comment]
I'm less keen on environment variables changing behavior. A variant of 2 would be an option within the command that would use the old logic, e.g. `linkml-validate --legacy-mode ...`

Another option is to rename the existing one `linkml-legacy-validate` and simply drop in the new one. We may want to implement all the old options first through.
