### ISSUE TITLE
`tests/test_compliance/test_core_compliance.py` fails on Python 3.11

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1661]
Running `tests/test_compliance/test_core_compliance.py` passes with Python 3.10:

```shell
$ tox -e py310 -- tests/test_compliance/test_core_compliance.py
...
  py310: OK (25.15=setup[4.69]+cmd[1.39,19.06] seconds)
  congratulations :) (25.22 seconds)
```

Whereas with Python 3.11:

```shell
$ tox -e py311 -- tests/test_compliance/test_core_compliance.py
...
FAILED tests/test_compliance/test_core_compliance.py::test_date_types[python_dataclasses-date-20210101-False] - Failed: DID NOT RAISE <class 'Exception'>
FAILED tests/test_compliance/test_core_compliance.py::test_date_types[jsonschema-date-20210101-False] - AssertionError: Expected errors in json schema validation, but none found
```

Both failures appear to be related to parsing a date in this format: `20210101`. 

This hasn't been surfaced yet because our GitHub action testing matrix is a bit behind -- it only goes up to 3.10 while 3.11 has been stable for [about a year now](https://devguide.python.org/versions/). This might be a good opportunity to get that updated as well.

**Comment by sneakers-the-rat** [comment]
(this passes now? i think can be closed)

**Comment by pkalita-lbl** [comment]
Yes, I can't point to a specific commit where it was resolved, but we are regularly running tests in CI with Python 3.11 now. Closing.
