### ISSUE TITLE
Make it possible to change the base type of permissible values (enums)

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#1673]
**Is your feature request related to a problem? Please describe.**

https://github.com/mapping-commons/sssom/issues/323

**Describe the solution you'd like**

If I could say: my enum is a "curieoruri" instead of a "string", the RDF converters would be able to understand that my enum "owl:Class" is a CURIE in disguise that need to be expanded to an IRI.

**How important is this feature?** Select from the options below:

• Important - it's a blocker and can't do work without it. I introduced a bad enum into a LinkML model (sssom model) and I need to fix it.. My only other option would be to not use enum, make the slot have `EntityReference` range and add a "anyOf" or regex constraint..

**When will use cases depending on this become relevant?** Select from the options below:

It is already relevant. 

**Additional context**

**Comment by nlharris** [comment]
How hard would this be to add?

**Comment by cmungall** [comment]
Let's discuss on the Friday call, I looked at the linked sssom issue and I don't understand the problem with simply adding `meaning`

**Comment by matentzn** [comment]
I made a comment on the thread in slack you yourself raised leading to this discussion..

**Comment by cmungall** [comment]
Looking back at the sssom thread, I don't think there is any linkml request here?

We do need to better document meanings + rdf serialization here https://linkml.io/linkml/schemas/enums.html#mapping-permissible-values-to-ontologies

**Comment by matentzn** [comment]
Ok, I am not 55% satisfied to leave enums be fairly type agnostic, but it does irk me that I cant express that the value of an enum _is_ an RDF resource rather than "should be interpreted as one during conversion to RDF" -> in any case, given the explanations you gave in the SSSOM thread, I am happy to drop it for now!
