### ISSUE TITLE
Yuml gen does not seem to render .png file on windows systems.

### ISSUE THREAD

**Issue by HendrikBorgelt** [linkml/linkml#1676]
**Describe the bug**
The command `gen-yuml -f png personinfo.yaml  > personinfo.png` in the linkML tutorial [Part 2: Adding a container object - Visualizing](https://linkml.io/linkml/intro/tutorial02.html#visualizing) does not create a a correctly rendered .png-File on my windows System, but rather a plain text file containing the generated yuml address for the image `https://yuml.me/diagram/nofunky;dir:TB/class/[Container]++- persons 0..*>[Person|id:string %3F;full_name:string %3F;aliases:string %3F;phone:string %3F;age:string %3F],[Container]`. Thus the .png file can not be opened with most explorers.

**To reproduce**
Sorry for the shortcut, but me and two students of mine just followed the tutorial with different versions of LinkML installed, starting from 1.5.2 to the current linkml-1.6.1with linkml-runtime-1.6.0, and as the tutorial is already a tutorial I hope it is sufficient.

**Expected behavior**
I expect to get a rendered Image that could be opend with e.g. Windows Picture Viewer.

**Screenshots**
![grafik](https://github.com/linkml/linkml/assets/84382772/8c5d3718-61a4-4683-840d-7bb9316cbfd1)
![grafik](https://github.com/linkml/linkml/assets/84382772/9f16ac60-2fca-406c-8309-52ddd09ad6c1)
Sorry for the German error message in Windows Picture Viewer but I think the translation should be sufficient.

**About your computer (if applicable, please complete the following information):**
 - OS: Win 10 Educational
 - linkml executed via basic cmd, not power-shell, with python 3.11.3

**Comment by dalito** [comment]
Spaces should be encoded as %20. They are illegal in urls. If you insert the above url (with spaces) into Firefox or Edge the browsers convert the space to %20 automatically and show the visualization. However, the windows file explorer does not do this conversion. 

gen-yuml should not generate invalid urls. It is a general bug (not specific for windows).

**Comment by dalito** [comment]
If I understand https://github.com/linkml/linkml/issues/522 correctly, the format option to create png-output is not implemented.

**Comment by dalito** [comment]
In order to generate a png file with `gen-yuml` the output directory has to be given. If it is missing the generator falls back to generating a url. So to get a png file in the current director the command is: `gen-yuml -f png -d . personinfo.yaml`.
