### ISSUE TITLE
schema elements lack names in generated ttl

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#169]
`linkml:name` (slot_uri rdfs:label) is a required field for schema elements, however it is not generated in the turtle. This is illustrated on the schema .ttl itself:

```yaml
linkml:name a linkml:SlotDefinition ;
    OIO:inSubset linkml:owl ;
    rdfs:seeAlso <https://en.wikipedia.org/wiki/Data_element_name> ;
    skos:definition "the unique name of the element within the context of the schema.  Name is combined with the default prefix to form the globally unique subject of the target class." ;
    skos:inScheme linkml:meta ;
    skos:mappingRelation schema:name,
        rdfs:label ;
    linkml:definition_uri linkml:name ;
    linkml:domain linkml:Element ;
    linkml:domain_of linkml:Element ;
    linkml:identifier true ;
    linkml:owner linkml:Element ;
    linkml:range linkml:string ;
    linkml:required true ;
    linkml:slot_uri rdfs:label .
```

i.e. name is required, but name does not name itself, thus putting itself in violation of its own schema...

**Comment by hsolbrig** [comment]
skos:exactMatch <https://w3id.org/biolink/vocab/SIO:000984>,
        <https://w3id.org/biolink/vocab/SO:0001026>,
        <wikidata:Q7020> ;

(3594 in Linkml unit test)

**Comment by sierra-moxon** [comment]
closing as complete; reopen if necessary as usual :)
