### ISSUE TITLE
Add pattern/regexp validation for pydanticgen

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1696]
pydantic supports regexes/patterns:

https://docs.pydantic.dev/latest/concepts/fields/#string-constraints

We should generate this in pydanticgen

Should this be optional, to avoid potentially expensive checks at time of object generation?

This issue should be closed by removing PYDANTICGEN from:

https://github.com/linkml/linkml/blob/5c0dfa25f65b7170768b52c94f67ec609afeb745/tests/test_compliance/test_pattern_compliance.py#L57-L59

**Comment by nlharris** [comment]
(Ignore the "mention" above; that was the wrong issue #. Now fixed.)
