### ISSUE TITLE
metamodel overloads linkml:slots

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#170]
currently it is possible to have two distinct slots map to the same URI, i.e

 * `s1 slot_uri uriX`
 * `s2 slot_uri uriX`

It seems that doing this has negative repercussions for roundtripping - if we go from yaml to rdf, and back, how do we know which slot to map back to?

Interestingly, the metamodel has one case of this, with the `slots` slot which is used two different ways:

 - to provide an inline dict of slots at the level of a schema
 - to provide list of slot names at the level of a class

It looks like the yaml parser maps the first to `slot_definitions` but uses `slots` as an alias, and slot_uris are made from aliases...

```turtle
linkml:slot_definitions a linkml:SlotDefinition ;
    skos:definition "slot definitions" ;
    skos:inScheme linkml:meta ;
    linkml:alias "slots" ;
    linkml:definition_uri linkml:slot_definitions ;
    linkml:domain linkml:SchemaDefinition ;
    linkml:domain_of linkml:SchemaDefinition ;
    linkml:inlined true ;
    linkml:multivalued true ;
    linkml:owner linkml:SchemaDefinition ;
    linkml:range linkml:SlotDefinition ;
    linkml:slot_uri linkml:slots .

linkml:slots a linkml:SlotDefinition ;
    skos:definition "list of slot names that are applicable to a class" ;
    skos:inScheme linkml:meta ;
    skos:note "This defines the set of slots that are allowed to be used for a given class. The final list of slots for a class is the combination of the parent (is a) slots, mixins slots, apply to slots minus the slot usage entries. Formally," ;
    linkml:definition_uri linkml:slots ;
    linkml:domain linkml:ClassDefinition ;
    linkml:domain_of linkml:ClassDefinition ;
    linkml:multivalued true ;
    linkml:owner linkml:ClassDefinition ;
    linkml:range linkml:SlotDefinition ;
    linkml:slot_uri linkml:slots .
```

this means that linkml:slots is used in two different ways in ttl generated from any schema - including linkml itself:

```
linkml:SchemaDefinition a linkml:ClassDefinition ;
    rdfs:seeAlso <https://en.wikipedia.org/wiki/Data_dictionary> ;
    skos:altLabel "data dictionary" ;
    skos:definition "a collection of subset, type, slot and class definitions" ;
    skos:inScheme linkml:meta ;
    linkml:class_uri linkml:SchemaDefinition ;
    linkml:definition_uri linkml:SchemaDefinition ;
    linkml:is_a linkml:Element ;
    linkml:slots linkml:aliases,
        linkml:alt_descriptions,
        linkml:annotations,
        linkml:broad_mappings,
        linkml:classes,
        linkml:close_mappings,
...
linkml:AltDescription a linkml:ClassDefinition ;
    skos:definition "an attributed description" ;
    skos:inScheme linkml:meta ;
    linkml:class_uri linkml:AltDescription ;
    linkml:definition_uri linkml:AltDescription ;
    linkml:slots linkml:alt_description_source,
        linkml:alt_description_text .
```

I think in general slot_uri *should* be inverse functional, i.e. uniquely define a slot

For the metamodel I see two options:

 1. use the same slot `slots` for both usages, and use `slot_usage` to differentiate the different cases.
 2. remove the `alias` from slot_definitions, and weakly deprecate the use of `slots` to list slots at the schema level

**Comment by hsolbrig** [comment]
`I think in general slot_uri should be inverse functional, i.e. uniquely define a slot`

I don't think you can do that.  If I have an _existing_ data structure, meaning that I have absolutely no control over the names of the classes or slots in the JSON:
```json
{
      "P1": {
           "name": "Fred",
           "age": 17,
          "type": "Person"
      },
     "D1": {
          "doctor_name": "Sam",
          "role": "Primary Care",
          "type": "Clinician"
     }
}
```

While the creators of the above bit of data decided to use different labels for Persons and Clinicians, we want to map both of them to the same semantics if they are the same semantics.  Furthermore, if we have the RDF:

```
[] :a :Clinician, :Person;
    foaf:name "John";
    foaf:age 43;
    :role "Primary Care" .
 ```
I would expect this to be able to produce _either_ a Person (w/ "name": "Fred"), a Clinician (w/ "doctor_name": "Fred") or both.

**Comment by hsolbrig** [comment]
See: https://tinyurl.com/8xuy3k4b for the forward direction of the above example

**Comment by hsolbrig** [comment]
This is a reverse, https://tinyurl.com/y4je3f8e but, interestingly, it doesn't appear to override the context for `treated_by`.  Definitely need more discussion.

That said, I _do_think that we need to detect and warn about situations where two different slots _at the same level_ map to the same URI -- that is most likely an error.


As far as:
`remove the alias from slot_definitions, and weakly deprecate the use of slots to list slots at the schema level`

That would break a LOT of things.  Lets talk further about this option...

**Comment by sierra-moxon** [comment]
Do we still want to tackle this or was @hsolbrig's explanation of next steps for warning the user about the possible error a good next step?
