### ISSUE TITLE
Add pydantic support

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#172]
Some users eg @kshefchek have expressed a need for generated python classes to use pydantic. This gives better validation and works better with fastapi.

This could be an option on current oxygen rather than new code. 

There is a bridge layer which should help

https://pydantic-docs.helpmanual.io/usage/dataclasses/

**Comment by dwinston** [comment]
@cmungall note that [nmdc-server](https://github.com/microbiomedata/nmdc-server/blob/7760e3890bea4f85854e27171e1c6f1472419c39/nmdc_server/schemas.py) has custom-written many pydantic models for ingest and translation of the NMDC Schema, so this use case could be an application of linkml-model-generated pydantic models as well.

**Comment by dwinston** [comment]
cc @zachmullen

**Comment by cmungall** [comment]
See also #464

**Comment by cmungall** [comment]
Note, we now have a pydanticgen:

https://linkml.io/linkml/generators/pydantic.html

I'm leaving this open as it's not yet clear what the pros and cons are vs pythongen - see also https://github.com/linkml/linkml/issues/485

**Comment by cmungall** [comment]
one thing that would be useful to have is a way to instantiate classes that share the same interface as the existing pythongen classes.

E.g.

```
from my_model.pydantic import Person, Organization ## generated using pydanticgen

person_dc = json_loader.load('my_data.json') ## generated using pythongen
person_dict = as_dict(person_dc). ## plain python dict (not JsonObj)
person = Person(**person_dict)
```

it may be useful having a utility class that does this more directly

**Comment by cmungall** [comment]
@kevinschaper can you add a test for the existing pydanticgen?

**Comment by cmungall** [comment]
calling this done, thanks @kevinschaper !
