### ISSUE TITLE
Clarify semantics of overrides/non-monotonicity

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1730]
LinkML schemas *should* be monotonic. 

Subclassing and slot usage are intended to *refine* rather than *override*. Formally,[non-monotonic inference](https://en.wikipedia.org/wiki/Non-monotonic_logic) is not fully supported.

- The documentation should be clearer
- The tools should warn you when you attempt to do this
- There should be documented patterns on how to avoid this (e.g. using Any on parents)

Currently if a schema is non-monotonic, some odd things can happen

- #1508
- #1483
- #1702 

Rather than having people change their schema we can introduce clearer semantics for a limited amount of non-monotonicity. This does get quite difficult to do in the general case (e.g minimum and maximum values). 

This is a known issue with closed world systems and multiple inheritance, this is called a [Nixon Diamond](https://www.researchgate.net/figure/The-modiied-Nixon-diamond-is-inconsistent-but-only-implicitly_fig5_2732155)
![image](https://github.com/linkml/linkml/assets/50745/508fb32c-d9d2-4cf0-99d0-e83d5b7b9f34)

**Comment by sierra-moxon** [comment]
fixed with: https://github.com/linkml/linkml/pull/2108, closing
