### ISSUE TITLE
docgen should use alias field when reporting slots for a class

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1733]
https://linkml.io/linkml-model/latest/docs/Example/ says that Examples can use a `value_description` slot, but validation won't accept that. The alias `description` is required.

The documentation should show the `alias` here

**Comment by cmungall** [comment]
@turbomam check you are OK with my restructing your issue

**Comment by sierra-moxon** [comment]
I believe this is complete; I do not see mangled slots on class pages generated with `gen-doc`
