### ISSUE TITLE
How to help people understand that the case of element names may be altered on doc pages

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1734]
the nmdc-schema has a [external_identifier](https://github.com/microbiomedata/nmdc-schema/blob/4642786d8bbb2589efcdfdc5cd440a7baa41e2ca/src/schema/external_identifiers.yaml#L24-L33) type, but it is called [ExternalIdentifier](https://microbiomedata.github.io/nmdc-schema/ExternalIdentifier/) on the gen-doc page

**Comment by sujaypatil96** [comment]
The documentation generator does a "silent repair" (on the web documentation side, not in the schema itself) and formats/renders the names of elements based on some of the implicit rules described here (not exhaustively): https://linkml.io/linkml/schemas/linter.html#standard-naming

Perhaps, a dedicated FAQ page/adding a section to an existing FAQ page to clarify all the element "repairs" that are happening would be helpful.

**Comment by sujaypatil96** [comment]
Related FAQ entry: https://linkml.io/linkml/faq/modeling.html#why-are-my-class-names-translated-to-camelcase

**Comment by turbomam** [comment]
I think we should reciprocally link between that FAQ and https://linkml.io/linkml/schemas/linter.html#standard-naming

**Comment by sierra-moxon** [comment]
closing as complete.
