### ISSUE TITLE
Enhance gendoc for subset pages

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1735]
Taking NMDC's [data_portal_subset](https://github.com/microbiomedata/nmdc-schema/blob/4642786d8bbb2589efcdfdc5cd440a7baa41e2ca/src/schema/nmdc.yaml#L131-L145) and the corresponding docs page https://microbiomedata.github.io/nmdc-schema/DataPortalSubset/ as an example 

- [ ] the documentation page changes the case from `data_portal_subset` to DataPortalSubset
- [x] ~~the documentation page does not display the `description` or `comments`.~~
- [x] ~~the documentation page lists the slots that are in the subset. If classes had been placed into the subset, would they also appear on the page?~~

**Comment by sujaypatil96** [comment]
From the example in this issue: https://microbiomedata.github.io/nmdc-schema/DataPortalSubset/

- [ ]  the documentation page does not display the description or comments.

<img width="799" alt="Screen Shot 2023-11-15 at 2 06 04 PM" src="https://github.com/linkml/linkml/assets/20239224/da364a84-33c3-40dc-8bbd-47a390a71524">

- [ ] the documentation page lists the slots that are in the subset. If classes had been placed into the subset, would they also appear on the page?

Yes, the subset jinja template is generic, and can display tables for all:
* Slots in subset: https://github.com/linkml/linkml/blob/main/linkml/generators/docgen/subset.md.jinja2#L81-L92
* Classes in subset: https://github.com/linkml/linkml/blob/main/linkml/generators/docgen/subset.md.jinja2#L41-L78
* Enums in subset: https://github.com/linkml/linkml/blob/main/linkml/generators/docgen/subset.md.jinja2#L95-L106

**Comment by sujaypatil96** [comment]
Related issue: #1734

**Comment by turbomam** [comment]
thanks @sujaypatil96
