### ISSUE TITLE
TypeError: validate() got an unexpected keyword argument 'obj'

### ISSUE THREAD

**Issue by plbremer** [linkml/linkml#1738]
Hello,

When attempting to replicate the behavior described in the docs

https://linkml.io/linkml-validator/usage/#using-linkml-validator-as-a-module

with something like

```
from linkml.validator import Validator

my_dict={
    'species':'Homo sapiens'
}

schema_path='/Users/pgleasonbremer/coding_projects/altos/altos-labs-ontology/src/alo/schema/alo.yaml'

my_Validator=Validator(schema=schema_path)

my_Validator.validate(
    obj=my_dict,
    target_class='DataPackage'
)
```

I get 

```
Traceback (most recent call last):
  File "/Users/pgleasonbremer/coding_projects/altos/linkml/mwe_validator_broken.py", line 12, in <module>
    my_Validator.validate(
TypeError: validate() got an unexpected keyword argument `obj`
```

however, I get no error when changing the keyword to `instance`

```
my_Validator.validate(
    instance=my_dict,
    target_class='DataPackage'
)
```

I would submit a PR to fix it, but i dont have the bandwidth to figure out the autodoc stuff at the moment, sry.

**Comment by pkalita-lbl** [comment]
Hi @plbremer sorry for the confusion. The docs you're referring to (https://linkml.io/linkml-validator/usage/#using-linkml-validator-as-a-module) are for an older standalone package called `linkml-validator` (https://pypi.org/project/linkml-validator/). Documentation for the new built-in tools in the `linkml.validator` package can be found [here](https://linkml.io/linkml/data/validating-data.html) and [here](https://linkml.io/linkml/code.html#module-linkml.validator). When designing the functions and classes in the `linkml.validator` package we took a lot of inspiration from what was done in `linkml-validator`, but they're not totally identical. 

I'll leave this issue open as a reminder that we should add something to the `linkml-validator` docs to point people to the new built-in tools.

**Comment by plbremer** [comment]
@pkalita-lbl since the old docs got taken down maybe close this issue?
