### ISSUE TITLE
Add new generator for java

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#175]
Requested by @oblodgett and @julesjacobsen

We used to recommend linkml->jsonschema->jsonschema2pojo but this is sub-optimal as information is lost in the first transform

We would like to add a generator for a java object model, it could follow this as a template:

https://github.com/linkml/linkml/blob/main/linkml/generators/pythongen.py

The main decision to be made is what kind of object model to make

 * mutable:
    * POJO
    * JavaBean
 * immutable
    * https://immutables.github.io/
    * AutoValue https://github.com/google/auto/tree/master/value
    * Lombok Builder https://projectlombok.org/features/Builder
    * ...

**Comment by oblodgett** [comment]
I don't think it's going to be easy to solve the output format for the java objects. In AGR's case we will need Hibernate annotated lombok objects. However someone might want to decorate the objects with OGM (Hibernate for Neo) annotations, which are vary different from straight hibernate annotations. There is also nuance differences between hibernate and javax.persistance annotations, etc, etc, etc.

So what would seem straight forward to me is to take a POJO and apply a "decorator" to get the flavor of object that you are looking for. I would guess that some of these "decorators" could be mixed and combined to form the object that one desires. However that would take some sort of config on the generator side in order to apply decorators correctly.

I agree with @julesjacobsen it might be better to generate in java where you could subclass the decorator or implement an interface to create your custom version of the classes you were looking for.

**Comment by cmpich** [comment]
Interesting! Does that mean we need to tinker around with creating Java classes of the kind we'd like to have? is that generator not widely used / requested? Maybe, time for us to jump in.

**Comment by cmungall** [comment]
Just to be clear, there is no javagen yet!

I am sympathetic to the request to have the javagen be in java so it makes it easier to re-use existing frameworks and configure decorators etc. I would not recommend parsing meta.yaml directly. I would go with java classes that are themselves instances of schema classes e.g https://w3id.org/linkml/ClassDefinition... but to do that we need a java class generator!

**Comment by julesjacobsen** [comment]
@cmungall is the Python generator itself generated from the schema or was there a hand-coded bit there?

**Comment by oblodgett** [comment]
@cmungall I would guess that the "javagen" would have a bunch of classes as you state that represent the linkml definitions. And after reading in the schema you might have a class that holds all of the linkml java objects.

Then maybe have a few definitions of what the "Base" class looks like: POJO, lombok, AutoValue, etc. Then apply a decorator to generate annotations depending on which hibernation framework, is desired. This could be handled by an "DecoratedVisitorInterface", or other such idea.

The outcome would be if using a POJO then you would get getters and setters with hibernate annotations on them. Where as if the base class was lombok you would get the hibernate annotations on the fields definitions instead.

**Comment by cmungall** [comment]
There was iterative bootstrapping, the first was built from a dictionary
obtained from parsing the yaml then it switched to being self instantiating

**Comment by cmungall** [comment]
I think the best way to bootstrap this would be to write the first pass as a jinja2 template (taking schemaview objects as input). This would be easier for non-python programmers to manipulate to adapt to their style. In the future we may use native java generators but there will need to be bootstrapping of the metamodel first

**Comment by oblodgett** [comment]
Here is a link to the Alliance's model manually generated from the LinkML model:
https://github.com/alliance-genome/agr_curation/tree/main/src/main/java/org/alliancegenome/curation_api/model/entities
https://github.com/alliance-genome/agr_curation_schema/tree/main/model/schema

Olin

**Comment by cmungall** [comment]
We discussed this when @julesjacobsen visited Berkeley

We are making a general guide to porting: #779

The general gist is: bootstrap using existing generators (there is some existing work to do generate java records introduced i java16) then make a SchemaView library, then switch to generating from the java framework, leveraging existing java codegen tools

**Comment by sierra-moxon** [comment]
@kevinschaper @cmungall  - We have a javagenerator that has gone through a couple of iterations that make me feel like "add a new generator for java" is done (we can capture further work in more specific tickets?)  Do you agree? If not, please feel free to reopen of course. :)
