### ISSUE TITLE
Similar to linkml:required, could we have a linkml:recommended boolean?

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#177]
Occasionally in specifications fields aren't required, but they are recommended.  Would LinkML want a linkml:recommended boolean to indicate this so it can be reflected in user interfaces (but not validation)?

**Comment by cmungall** [comment]
I support this suggestion

Is this enough levels? The combination gives us the ISO recommended levels

Req=true -> MUST
Req=false, Rec=true -> SHOULD
Req=false, Rec=false -> MAY

and absence of a slot (asserted or inferred) is MUST NOT

But I wonder if we might want a more extensible scheme

**Comment by ddooley** [comment]
I like above required/recommended combo.  There may be other schemes but then people can just utilize them instead.

**Comment by hsolbrig** [comment]
Extensions from: https://datatracker.ietf.org/doc/html/rfc6919 ?  (MUST (BUT WE KNOW YOU WON'T) and REALLY SHOULD NOT, ...) ;-)

W3C official reference
https://datatracker.ietf.org/doc/html/rfc2119

Do we anticipate that "Rec" would effect the behavior of any of the tooling beyond the documentation generator?  Would someone want to have a "lint" mode that issues a warning on missing "SHOULD fields"?

**Comment by cmungall** [comment]
I think lint mode and dashboards are the right way to think about this.

**Comment by ddooley** [comment]
Yes, seems like recommended flag could be employed for reporting on dataset completeness, and certainly UI options.

Not sure where RFC2119 is used, but the language describing some choices is a bit odd! Trying to see equivalent to "Recommended", but they're a bit more general:

SHOULD CONSIDER

   The phrase "SHOULD CONSIDER" indicates that the authors of the
   specification think that implementations should do something, but
   they're not sure quite what.

OUGHT TO

   The phrase "OUGHT TO" conveys an optimistic assertion of an
   implementation behavior that is clearly morally right, and thus does
   not require substantiation.
