### ISSUE TITLE
Include a deprecation guide in the release management guide

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1771]
Release management how-to: #1765

We should add a section to this on deprecation. We can draw from:

- https://github.com/microbiomedata/nmdc-schema/blob/main/src/docs/schema_element_deprecation_guide.md
- https://biolink.github.io/biolink-model/maintaining-the-model/#deprecating-classes-and-slots

**Comment by sujaypatil96** [comment]
Related PR: #2079
