### ISSUE TITLE
linkml 1.6.4 eliminates old pydantic_version cli parameter

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#1780]
**Describe the bug**
Models that use 1.6.3 or earlier run a command like this to generate pydantic serialization of the model:
`$(RUN) gen-pydantic --pydantic_version 1 src/model/schema/model.yaml > $(PYMODEL)/pydanticmodel.py`
 
In 1.6.4 they should run:
`$(RUN) gen-pydantic --pydantic-version 1 src/model/schema/model.yaml > $(PYMODEL)/pydanticmodel.py`

we should support the underscore version for a few releases to help people transition.

**Comment by sneakers-the-rat** [comment]
i believe this was done in https://github.com/linkml/linkml/pull/1927
