### ISSUE TITLE
Can specification include a preferred user interface label slot for an entity?

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#179]
Often database fields (slots) have nicer names appear for them on table columns and form fields.  Is it within LinkML's purview to include a slot that would contain a recommended label (in a given language)?

**Comment by cmungall** [comment]
I'm not totally sure I follow

In general the convention is to use a domain specialist label as the main name in the yaml, and this is converted to something following computational conventions in the export, e.g snakecase for slots

You can also provide aliases with `aliases`, and attributed labels with `local_name`

there isn't language support, e.g. language-specific labels, as such but this is a reasonable thing to request

can you describe the use case more?

**Comment by ddooley** [comment]
E.g. in NCBI Biosample:
![image](https://user-images.githubusercontent.com/4000582/116013069-01b91c80-a5e3-11eb-9fbf-cf4bca91fd5d.png)

So for this a slot definition name would be "geo_loc_name" and an alias would be "geographic location"?  Then we could use the alias as a label for a form field input would be connected to geo_loc_name field.

**Comment by cmungall** [comment]
Yes. You could use local name to add metadata to the label as we do for
ontologies

Minor gripe: not sure of the history of mixs migs and why there are two
alternate field names one with arbitrary contractions... as if computers
can't handle longer labels

**Comment by ddooley** [comment]
ok, thanks.
