### ISSUE TITLE
Improvements to markdown generator

### ISSUE THREAD

**Issue by deepakunni3** [linkml/linkml#18]
- Differentiating between Entity, Association, Slot, Relation and Property during export from biolinkml. This could be handled by creating folders for each, and exporting the markdown into these folders.
- CURIE mappings from YAML should be in markdown export (currently missing).
- The title in each markdown should be camelcase instead of sentence case. For example, it should be `Class: NamedThing` instead of `Class: named thing`.

**Comment by cmungall** [comment]
@joeflack4 can you fold these into the PR you are working on?

**Comment by joeflack4** [comment]
@cmungall I added these to [markdowngen improvements master issue](https://github.com/linkml/linkml/issues/245). I also enumerated the bullet points there. I'm wondering if we should close this issue now that these have been added to there?
