### ISSUE TITLE
Add PermissibleValue:value to Enumerations

### ISSUE THREAD

**Issue by puja-trivedi** [linkml/linkml#1810]
**Is your feature request related to a problem? Please describe.**
I noticed that when defining enums in linkml I am unable to set a value for each label. I always convert my linkml to pydantic so I took a look at pydanticgen.py and oocodegen.py(specifically the generate_enums() function) and I saw that both the label and value are set to pv.text (`label = self.generate_enum_label(pv.text)` and `val = {"label": label, "value": pv.text.replace('"', '\\"')} `). I believe in Pydantic, the enum’s label does not necessarily have to match the enum’s value.

It seems (from my understanding of the generator code) that the only enum fields that are translating from linkml to pydantic are  PermissibleValue:description  and  PermissibleValue:text .

**Describe the solution you'd like**
I would like to have the ability to define an enum's value myself not it automatically getting set to PermissibleValue:text.
I am able to get the desired output by changing the code in oocodegen.py from val = {"label": label, "value": pv.text.replace('"', '\\"')}  to val = {"label": label, "value": pv.meaning.replace('"', '\\"')} . I’m just not sure if that is the correct use of PermissibleValue:meaning.
So ideally if we are able to add PermissibleValue:value then we can change the code to val = {"label": label, "value": pv.value.replace('"', '\\"')} .

For example, right now an Enum in pydantic would look like this (if I used linkml and gen-pydantic):
```
class Example(str, Enum):
    label1 = 'label1'  
    label2 = 'label2' 
```

But I would like it to look like this:
```
class Example(str, Enum):
    label1 = 'value1'  
    label2 = 'value2'
```

**How important is this feature?** 
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**Comment by cmungall** [comment]
Discussed with @puja-trivedi and @sujaypatil96 at the NWB Hackathon

The proposal is use `title` for the enum value (when present - default to name if not present)

This does not preclude the possibility of having something more customizable later on
