### ISSUE TITLE
Support annotating a slot as holding a local identifier

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1821]
The canonical way to represent IDs in data described by LinkML is as CURIEs (in the python/yaml/json, always expended to URIs in rdf).

however, it's quite common for data formats to use local ids, e.g.

`ncbi_gene_id: 1234`

rather than

`ncbi_gene_id: NCBIGene:1234`

@cthoyt suggests a mechanism for doing this:

https://genomic.social/@cthoyt@scholar.social/111733300801895702

I think this would be quite useful. This would be a straightforward extension to the metamodel. The rdf dumper and jsonld generator would be extended to ensure the correct mapping to URIs.

This also opens up the ability to have tooling to do additional validation on patterns - either via a validator plugin that uses a prefix registry, or tooling that uses a prefix registry at schema build time to materialize patterns

**Comment by sierra-moxon** [comment]
from dev call - can close, we now can validate materialized patterns.
