### ISSUE TITLE
jsonasobj 2.0 

### ISSUE THREAD

**Issue by patrickkwang** [linkml/linkml#183]
jsonasobj has new breaking changes: https://pypi.org/project/jsonasobj/
We need to either make corresponding updates, or just put an upper bound on the allowed jsonasobj version.

**Comment by hsolbrig** [comment]
What did it break? (In that I made the changes specifically for use w/ jsonasobj)

**Comment by hsolbrig** [comment]
Apologies -- locked it down at 1.2.1 until I can figure out what the issue is...

**Comment by hsolbrig** [comment]
Double apologies -- looks like 1.2.1 wasn't where we wanted to be either.  Yanked the 2.0.1 element from pypi and will figure out what happened next week

**Comment by hsolbrig** [comment]
@patrickkwang -- what _were_ the breaking changes you observed in 2.0.1 of jsonasobj?   The issue that I'm wrestling with is that it fixes several other issues so backing it out doesn't solve the problem either.

**Comment by patrickkwang** [comment]
We ran into this with Python 3.9.0 and
```text
bmt==0.6.0
linkml==0.0.7
linkml-model==0.0.10
jsonasobj==2.0.1
```
When attempting to
```python
from bmt import Toolkit
```
we receive
```text
ValueError: Slot: alt_descriptions - unrecognized element: JsonObj()
```

**Comment by hsolbrig** [comment]
Thanks!

**Comment by cmungall** [comment]
I'm pretty sure this is no longer an issue but reopen if I'm wrong @patrickkwang
