### ISSUE TITLE
Problem with `test_jsonschemagen.py` unit tests

### ISSUE THREAD

**Issue by paulmillar** [linkml/linkml#1835]
**Describe the bug**

When building the test environment, I found that `tests/test_generators/test_jsonschemagen.py` tests were failing.  Here is a typical error:
```
file /home/paul/git/linkml/tests/test_generators/test_jsonschemagen.py, line 258
  def test_required_slot_condition_in_rule(subtests, input_path):
E       fixture 'subtests' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, input_path, kitchen_sink_path, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, snapshot, snapshot_path, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

**To reproduce**

Check out `linkml` git repo.
Build virtual environment following instructions
Run `poetry run pytest tests/test_generators/test_jsonschemagen.py`

**Expected behavior**

There should not be any errors reported for this test suite.

**About your computer (if applicable, please complete the following information):**

```console
paul@monkeywrench:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
paul@monkeywrench:~$ 
```

**Additional context**

The problem is due to a missing dependency.  The `test_jsonschemagen.py` tests depend  on the `pytest-subtests` package being installed.

Manually installing this dependency fixes the problem:

```console
paul@monkeywrench:~$ pip3 install pytest-subtests
Collecting pytest-subtests
  Using cached pytest_subtests-0.11.0-py3-none-any.whl (6.7 kB)
Requirement already satisfied: pytest>=7.0 in ./Venv/test-linkml/lib/python3.11/site-packages (from pytest-subtests) (7.4.4)
Requirement already satisfied: attrs>=19.2.0 in ./Venv/test-linkml/lib/python3.11/site-packages (from pytest-subtests) (23.2.0)
Requirement already satisfied: iniconfig in ./Venv/test-linkml/lib/python3.11/site-packages (from pytest>=7.0->pytest-subtests) (2.0.0)
Requirement already satisfied: packaging in ./Venv/test-linkml/lib/python3.11/site-packages (from pytest>=7.0->pytest-subtests) (23.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in ./Venv/test-linkml/lib/python3.11/site-packages (from pytest>=7.0->pytest-subtests) (1.3.0)
Installing collected packages: pytest-subtests
Successfully installed pytest-subtests-0.11.0
paul@monkeywrench:~$ 
```

I believe I followed the instructions.  If so, then the `pytest-subtests` dependency should either be documented or configuration updated to ensure this dependency is pulled in automatically.

**Comment by pkalita-lbl** [comment]
Hi @paulmillar I think there was possibly an issue in setting up your development environment? The `pytest-subtests` dependency is declared in the `tests` group: https://github.com/linkml/linkml/blob/0a5bfd1814326db790c917df99cd04319ac7f61b/pyproject.toml#L143

I just checked out a fresh copy of the `linkml/linkml` repo and then ran:

```shell
$ poetry install
...
$ poetry run pytest tests/test_generators/test_jsonschemagen.py
```

The test ran without issue. 

You mentioned that you set up your virtual environment following the instructions instructions. Can you point me to which instructions you followed? Perhaps those need to be updated?

**Comment by paulmillar** [comment]
Hi @pkalita-lbl ,

Thanks for investigating this issue.

I've tried the sequence above and can confirm that running `poetry install` does install the `pytest-subtests` module.  A subsequent call to run the tests (`poetry run pytest ...`) then works, as expected.

In trying to reproduce the issue, I believe the problem was that I used `pip3 install .` to build the executables.  This worked (I have executables such as `linkml-lint`), but it seems that command doesn't install the test dependencies (like `pytest-subtests`).  A subsequent call to `poetry run pytest` then fails due to missing dependencies.

Running `poetry install` (after `pip3 install .`) brings in the test dependencies so that `poetry run pytest` then works.

To be honest, I'm now not sure which instructions I was following.  There doesn't seem to be a "how to build LinkML" document.  I also couldn't find any mention of `poetry install` in the documentation.

Feel free to close the issue, since I was simply using the wrong command to build LinkML -- sorry for the noise.

**Comment by pkalita-lbl** [comment]
This isn't noise at all! I'm surprised that [this page](https://linkml.io/linkml/contributing/contributing.html) -- which covers a lot of other testing topics -- doesn't cover the basics of setting up a development environment. Admittedly if you're familiar with Python in general but haven't used Poetry before it can be a little confusing. I will open a PR to add more setup information to that page and link it to this issue.
