### ISSUE TITLE
`SchemaView.imports_closure` import and override order obeys not the law of man nor god

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#1839]
**Describe the bug**

rename this issue i am not doing great with words right now.

# introduction

let us consider the `imports_closure` method. a nice method, we like it, it is a good method. but do not let your guard down yet:

https://github.com/linkml/linkml-runtime/blob/6763067c9651ae21e0b5c19de5d5100c24a3f1d9/linkml_runtime/utils/schemaview.py#L221-L245

this, as far as I can tell, is the main way that import order is determined in many of the generators, as it is upstream from the methods 
* [all_schema](https://github.com/linkml/linkml-runtime/blob/6763067c9651ae21e0b5c19de5d5100c24a3f1d9/linkml_runtime/utils/schemaview.py#L248) which
* [_get_dict](https://github.com/linkml/linkml-runtime/blob/6763067c9651ae21e0b5c19de5d5100c24a3f1d9/linkml_runtime/utils/schemaview.py#L434) then collapses from left to right.
* which is used by most of/the rest of the getters like `get_classes`

# ordering

What manner of order does it produce? Since imports are a tree (i guess they can be a kind of constrained DAG since two imports can import the same thing but it's deduped in the loop so the cycles never close, but i digress), there are multiple ways it could be ordered. 

Suppose one were to have a `main` schema which imports the tree below:

```
main
|- linkml:types
|- s1
|  |- s1_1
|  |- s1_2
|     |- s1_2_1
|- s2
|  |- s2_1
|  |- s2_2
|- s3
   |- s3_1
   |- s3_2
```

(ie. `main` imports `types`, `s1`, `s2` ... `s2` imports `s2_1` ...)

what order might one expect from `imports_closure`? 

| A | B | C | D |
| - | - | - | - |
| main | main | main | linkml:types |
| linkml:types | linkml:types | s3 | s1_1 | 
| s1 | s1 | s3_2 | s1_2_1 |
| s1_1 | s2 | s3_1 | s1_2 |
| s1_2 | s3 | types | s1 |
| s1_2_1 | s1_1 | s2 | s2_1 |
| s2 | s1_2 | s2_2 | s2_2 |
| s2_1 | s2_1 | s2_1 | s2 |
| s2_2 | s2_2 | s1 | s3_1 |
| s3 | s3_1 | s1_2 | s3_2 |
| s3_1 | s3_2 | s1_2_1 | s3 |
| s3_2 | s1_2_1 | s1_1 | main |

place your bets  (spoilers below)

- A - depth first search
- B - breadth first search
- **C - SchemaView.imports_closure**
- D - "python import order"

the `C` behavior is from the combination of `pop` which draws from the end list, and `append` which adds to the end, which gets a little weird when you're also appending multiple entries in one round. it gets weirder if multiple schemas import a common one upstream, because a given schema is handled only the first time. 

this matters because of the way `_get_dict` collapses the schemas (and their classes, slots, etc.) from first in the list to the end, each overriding the previous: https://github.com/linkml/linkml-runtime/blob/6763067c9651ae21e0b5c19de5d5100c24a3f1d9/linkml_runtime/utils/schemaview.py#L442

# issues

this is the cause of many issues! i first noticed it because I was trying to extend a class in an inheriting child schema, but i couldn't! ( https://github.com/linkml/linkml/issues/1825 )

**inheritance** is very hard to predict, eg. in the above tree the `s1_1` schema has the highest priority, so if we were trying to use `s1` and it extended a class from `s1_1`, you would actually get the `s1_1` class instead. and if you were inheriting from a schema that was imported from some very deep place in the tree... etc.
- apparently inlined also changes this behavior: https://github.com/linkml/linkml/issues/1664

also related to **monotonicity,** and I think they are somewhat separable questions. Monotonicity is more about putting constraints on the kinds of inheritance you should be able to do, but it is easy to get a monotonicity problem confused with an ordering/override problem when the ordering is wonky. 
- https://github.com/linkml/linkml/issues/1730
- it also looks like some generators have different resolution logic here: https://github.com/linkml/linkml/pull/1805
- https://github.com/linkml/linkml/issues/1349
- https://github.com/linkml/linkml/issues/1508

inheritance relationships should probably be orthogonal to "**overrides**", but in order for them to be orthogonal, it always needs to be the case that the parent class they are inheriting from is the known one: either referred to just by its local `ClassName` without a prefix, or if some prefix is specified, use that one specifically rather than any other class with that name. currently it is impossible to declare `myschema:ClassName` if `ClassName` is anywhere in your imports tree, even if they are intended to be totally unrelated classes.
- re: overrides https://github.com/linkml/linkml/issues/584

The problems of overrides, monotonicity, and inheritance are related in a few ways, but one common one is the desire to subclass and extend an identically named class  (eg.  a `Person` class) esp. when one can't do a partial import.

# ideas

There are a couple things that come to mind as potential fixes here:
- I feel like this class should be recursive, rather than flattening in the `imports_closure` method: the `SchemaView` should know about imports of other `SchemaView`s 1 layer below them, but then the next layer `SchemaView` computes its own independent closure, etc. that makes each schema behave predictably on its own. 
  - That would handle the generality of potential tree shapes best, which includes eg. this problem of handling relative imports ( https://github.com/linkml/linkml/issues/1228#issuecomment-1712390959 ). 
  - There are other further flung problems that have to do with the handling of local and global naming that I think could be more easily resolved with a recursive class like eg https://github.com/linkml/linkml/issues/1301 
  - and it would also allow for monotonicity to be computed more easily by just doing a local comparison between parent and child rather than evaluating it in a loop
- one could just change the ordering of course, imo the "D" python ordering would be the most intuitive one, even if it looks weird. Basically that does a "leaf-first search" where the main module's definitions always override, and but then one handles all the imports of the first module and then the first module, which can be overridden by the second module, and so on... That would probably be the closest at hand solution that would make imports behave a whole lot more intuitively than they do now. The "D" python ordering is *almost* the inverse of the current ordering, except note the odd placement of the first `types` import.
- or i also suppose one could just force all names to be full curies/iris, at least in the internal representation, which would be sort of unpleasant and require a lot of rewriting i think.

Anyway I thought that it would be good to try and parse out these related problems together bc i think both the implementation and documentation would benefit from definitions that draw clear boundaries between them, sorry this is long. as always i'm happy to pitch code on this, bc i am gonna do it anyway to resolve a problem i'm having with the activitypub linkml schema which does override + inheritance, but thought i'd ask abt preference

**Comment by kervel** [comment]
Hello,

What would be the steps necessary to introduce proper namespacing ?

* Adapt schemaview so that you can use a uri/curie in is_a / range. This doesn't seem to work yet.
* Make the schemaview collections of fields/classes have a schema in the key. Still prevent 2 classes or slots with the same name even in different schema. Make sure that if we use a curie in a range or in a is_a we enforce the correctness.
* Introduce new schema-aware API in schemaview
* Make schemaview opt-in for namespacing so that only generators that are namespace-aware can accept schema definitions where you have multiple types with the same name in different schemas.
* Start changing the generators ?

I guess this is a gross oversimplification. I don't know what a schema aware API would even look like. But trying to get the discussion started.

greetings,
Frank
