### ISSUE TITLE
giving a slot a class `range` and a `pattern` results in generated OWL that won't pass validation (like with jena riot, loading into a triplestore)

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1841]
Consider a `Person` who `works_for` an `Organization`. We can assert that `id` is the identifying slot for `Organization`, that its range is uriorcurie and that it must follow some pattern.

Since LinkML doesn't currently provide referential integrity checking, NMDC has been adding `pattern`s for slots like `works_for` when used in `Person`. That means that `linkml-validate` etc. will check `works_for`'s value against a regular expression, but
-  it seems to confuse the OWL generator about whether `works_for` is an object property or a data property
- it requires asserting the same pattern two places in the schema

**Comment by cmungall** [comment]
4 actions here, I suggest doing in order:

1. default validation (jsonschemagen) can check patterns on foreign keys by a primary key lookup even in the absence of ref integrity. I think this is a v quick enhancement
2. nmdc and others then stop with the redundancy
3. owlgen should not assume pattern applies to literals
4. make full RI support default (e.g. by chaining jsonschema and a custom RI checker)

**Comment by aclum** [comment]
@cmungall  can this get the first item, adding default validation, request prioritized?
