### ISSUE TITLE
propagate pattern constraints from referenced classes to foreign key fields in jsonschemagen (partial referential integrity)

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1845]
jsonschema doesn't support referential integrity: https://stackoverflow.com/questions/56429622/make-sure-object-field-has-value-existing-in-another-field-in-json-schema

However, we can implement *partial* RI, where we propagate pattern constraints on the identifier field for a referenced class to the reference field

From #1841
default validation (jsonschemagen) can check patterns on foreign keys by a primary key lookup even in the absence of ref integrity. I think this is a v quick enhancement

**Comment by sierra-moxon** [comment]
I believe this is done.
