### ISSUE TITLE
What is the preferred reference for LinkML? DOI preferable. Should be regenerated to stay in sync with current release.

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1853]
Wouter-Michiel Vierdag is planning on using [10.5281/zenodo.5703670](https://zenodo.org/doi/10.5281/zenodo.5703670) from a [slightly dated Zenodo page](https://zenodo.org/records/10070666)

For inclusion in https://www.frontiersin.org/articles/10.3389/fbinf.2024.1336257/abstract

**Comment by dalito** [comment]
Zenodo should be updated automatically for each new release. This obviously does not work anymore. If it would, the DOI you give above would show the latest release.

**Comment by cmungall** [comment]
Somehow the switch on zenodo was flipped to off. I'm blaming it on their upgrade. The next release should be synced

**Comment by cmungall** [comment]
We should also use the concept DOI [10.5281/zenodo.5703670](https://zenodo.org/doi/10.5281/zenodo.5703670).

**Comment by dalito** [comment]
The integration is working again. v1.6.11 released yesterday appeared on Zenodo.
