### ISSUE TITLE
yamlutils:as_json_object fails if context parameter is a dict

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#186]
See [here for the problematic line](https://github.com/linkml/linkml/blob/375e4dd26f4f8244f7ab07497dbeb37eab75ae6b/linkml/utils/yamlutils.py#L194)

if context parameter is a dict, you will see this error:
![image](https://user-images.githubusercontent.com/7070631/116080366-de4cab00-a690-11eb-8520-08e90b5272f8.png)

The reason is that `JsonObj` does not understand what to do with a dict parameter in the constructor. Note that this was working in biolinkml - this only broke since the switch to linkml. 

The workaround on the client-side is to make sure the context is passed in as a JsonObj, which is easy enough.

**Comment by sujaypatil96** [comment]
Hi @matentzn, could you tell me the command you ran that led to this `TypeError` exception being raised?

**Comment by matentzn** [comment]
@sujaypatil96 - I was using the yamlutils:as_json_object method in some python code in the SSSOM codebase, such as:

https://github.com/mapping-commons/sssom-py/blob/master/sssom/writers.py#L13

**Comment by sierra-moxon** [comment]
Checking into the code at this point in time, I think we've resolved this and it can be closed.  Please reopen if necessary.
