### ISSUE TITLE
Docs might need tune up for people to get started to build docs

### ISSUE THREAD

**Issue by yarikoptic** [linkml/linkml#1872]
https://github.com/linkml/linkml/blob/main/docs/README.md just says

```markdown
To build the doc locally:

poetry run make html
```

but doesn't work for me neither from root, nor from `docs/`:

```shell
❯ pwd
/home/yoh/proj/misc/linkml/linkml

❯ git describe --tags
v1.6.11

❯ poetry run make html

Skipping virtualenv creation, as specified in config file.
make: *** No rule to make target 'html'.  Stop.

❯ (cd docs; poetry run make html; )
Makefile   code.rst  contributing/  developers/   examples.md  generators/   howtos/  index.rst  linkml.generators.rst  linkml.rst        links.rst  modules.rst  specifications/
README.md  conf.py   data/          ecosystem.md  faq/         glossary.rst  images/  intro/     linkml.reporting.rst   linkml.utils.rst  make.bat   schemas/     supplement-progress.md
Skipping virtualenv creation, as specified in config file.
Running Sphinx v7.2.6

Extension error:
Could not import extension sphinx_click (exception: No module named 'sphinx_click')
make: *** [Makefile:20: html] Error 2
```

**Comment by dalito** [comment]
You need to install the dev dependencies. `poetry install --with dev`. I am not sure if it is possible to specify instlling dev-dependencies in with `poetry run` command. So if you are in the root folder it should be

```
poetry install --with dev
cd docs
poetry run make html
```

**Comment by dalito** [comment]
Just a minor addition: If linkml is installed with `poetry install` sphinx and other development dependencies get installed (so `with dev` is not required). However, if pip is used to install linkml the development dependencies will not be installed. @yarikoptic did you maybe install with pip?

**Comment by yarikoptic** [comment]
at that point it was nohow installed -- I was just following that README.md and it didn't say to do any other actions prior to that command.  Later (after filing this issue), to actually get docs built I indeed just installed "manually" with `pip` to get docs built.

**Comment by nlharris** [comment]
I have not personally tried installing linkml. If there are additional instructions that you think should be added to the documentation, could you please do a pull request on https://github.com/linkml/linkml/blob/main/docs/README.md to correct the instructions? Thanks!
