### ISSUE TITLE
Appropriate use of "meaning"

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#189]
I see https://linkml.github.io/linkml-model/docs/meaning/ has domain PermittedValue, but we were wondering if it could be applied to a slot itself.  We are collecting an organism datum for our CanCOGeN standard, and so have made a SlotDefinition for that field. We would point it to  organism (OBI:0100026) as its "meaning". What is your recommendation?  Is it that SlotDefinition meanings are a bit more abstract, more like IAO 'data items'? But meaning still seems appropriate, as a kind of "aboutness".

And thanks for all the good work, we are busy learning how to implement LinkML.

**Comment by hsolbrig** [comment]
Thanks for the input -- much appreciated!

If I understand your comment correctly, we are both on the same page wrt "meaning".  The LinkML model hasn't been consistent in it's nomenclature,  unfortunately.

Looking at https://docs.google.com/presentation/d/1jtV2vQhCwsGv_9fPplkG8ww1ru4V_JYyRGLAm2dxvdE/edit#slide=id.gcf33f470c2_1_311  -- the intent of "slot_uri" and "class_uri" is to represent the two aspects of the `Data_Element` / `Data_Element_Concept` meaning connection in the ISO/IEC 11179 model.   FWIW, the current names violate one of my own modeling rules -- if an attribute includes the target type in it's name (e.g. "code", "value", "uri"),  you probably haven't captured the semantics correctly.

So -- first question:  what should the `slot_uri` _of_ `slot_uri` be?   Is there something in IAO that represents that intent?  

Second question: should we consider renaming the "slot_uri" slot itself as we evolve to make the intent clearer?

**Comment by cmungall** [comment]
I think the slot_uri of slot_uri should be slot_uri :-)

We can of course have a mapping to IAO, but there is nothing in IAO that captures precisely the same semantics

**Comment by ddooley** [comment]
Ah, so slot_uri for SlotDefinition is what meaning is for PermittedValue !  We could run with that.

I'd say "is about" is the loose IAO object relation, insofar as LinkML provides the data structure specification whose instances hold information (data items) about other things.  

Your "meaning" could easily be a subproperty of "is about" in IAO, since in your "X meaning Y", the subject X represents the object Y as a whole; whereas other uses (and subclasses) of "is about" attach qualities/characteristics to an object/entity.

But that does make me think, wouldn't it be ok to just have "meaning" as a property that attaches from Class or SlotDefinition or PermissableValue to the meant RDF resource or ontology term?

**Comment by ddooley** [comment]
Anyone want to give feedback on that last point - couldn't "meaning" be a generalized property that replaces slot_uri and class_uri?

**Comment by cmungall** [comment]
Hi @ddooley - this would be a breaking change

**Comment by ddooley** [comment]
Ok, we can close it then.  I was just thinking of a simplification move.  Conceptually I think I can still proceed by using slot_uri, class_uri and meaning as all pointing to the semantic content that the LinkML representation is about.
