### ISSUE TITLE
graphql mapping could be improved [low priority]

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#19]
E.g.

https://github.com/biolink/biolink-model/blob/c535a7ad6c89fcdd159dcde9a3a9e91807b5493e/biolink-model.graphql#L891-L908

can we not assign a more specific type to subject?

Also, given we have type inheritance in graphql, is it necessary to repeat everything

**Comment by nlharris** [comment]
Is this still relevant?

**Comment by wdduncan** [comment]
I don't know if it still relevant. I'll close the issue. It can be reopened if needed.
