### ISSUE TITLE
metamodel OWL has `@prefix schema1: <http://schema.org/> .`

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1933]
https://raw.githubusercontent.com/linkml/linkml-model/main/linkml_model/owl/meta.owl.ttl

why not

```turtle
@prefix schema1: <http://schema.org/> 
```

**Comment by cmungall** [comment]
Is this causing problems? All RDF tooling should expand this.

This happens because rdflib assigns schema to https://schema.org/, not
http://schema.org.

https://github.com/linkeddata/rdflib.js/issues/550
https://github.com/RDFLib/rdflib/issues/1679

**Comment by nlharris** [comment]
Is there an action item here?
