### ISSUE TITLE
Consolidate metamodel tests

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#1948]
**Is your feature request related to a problem? Please describe.**
Still trying to make the tests run faster :)

**Describe the solution you'd like**
Test metamodel correctness separately from generator and cli script correctness.

Currently the metamodel is generated and tested in a few places, and it seems like some are duplicates, and others don't need to be tested. In particular the `test_scripts` directory generates a bunch of versions of the metamodel and then compares them to snapshots. It seems like `test_scripts` is for testing the cli scripts, but they use the metamodel as the demo data rather than a lighter weight model, so they end up taking a long time!

It seems like we should test the metamodel correctness and generation in `test_base/test_metamodel.py` and use a much cheaper model in `test_scripts`. This would shave off another 5-10m depending on which of the tests we decide to keep

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**Additional context**
I'm happy to do this if it would b useful. my goal is to make tests be fast enough that we can move quickly and confidently, we've already come down from an hour-ish to 25m, and we can keep going :)

**Comment by cmungall** [comment]
Thanks, fully agree with this analysis and suggested course of action

**Comment by sneakers-the-rat** [comment]
I can handle this - is there a script/tool already for creating and saving the snapshots? or how are those updated?
