### ISSUE TITLE
Docker build broken :(

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#1977]
**Describe the bug**
All the docker builds aren't working :(
https://github.com/linkml/linkml/actions/workflows/docker-build.yaml

Comparing the last working one: https://github.com/linkml/linkml/actions/runs/8275166684
to the first broken one: https://github.com/linkml/linkml/actions/runs/8301994721

it looks like buildkit version went from 

 builder-86d20cc5-b3b9-4627-af4e-eeaa12ffee050: moby/buildkit:buildx-stable-1 => buildkitd github.com/moby/buildkit v0.12.5 bac3f2b673f3f9d33e79046008e7a38e856b3dc6

to

builder-d03649ed-a16e-4ff9-8de4-d96bd25661840: moby/buildkit:buildx-stable-1 => buildkitd github.com/moby/buildkit v0.13.0 2afc050d57d17983f3f662d5424c2725a35c60f4

am not a docker person, do not particularly care for it, don't know how to fix :'(

**Comment by cmungall** [comment]
@Silvanoc do you happen to know offhand what is happening here? If not we'll have someone check this out ASAP monday

**Comment by Silvanoc** [comment]
@sneakers-the-rat I don't know where you got the version information that you're providing, but:
1. there is no buildx v0.12.5. It jumps from v0.12.1 to v0.13.0
2. I don't see any difference in the buildx version between the [working pipeline](https://github.com/linkml/linkml/actions/runs/8275166684/job/22641685363#step:5:115) and the [failing pipeline](https://github.com/linkml/linkml/actions/runs/8301994721/job/22723316507#step:5:115)

Am I missing something?

**Comment by Silvanoc** [comment]
I haven't been able to dig deep enough to get to the root-cause. Here what I've found out:
1. the [code reporting the error](https://github.com/moby/buildkit/blame/6c0b576ff334443369ad1b675fe59bba5f905d72/frontend/dockerfile/dockerfile2llb/convert.go#L1203) is 2 years old and the code around it is years (2-5) old, so the issue might be in any of the functions being called
2. I suspected that the called function [gitutil.ParseGitRef](https://github.com/moby/buildkit/blob/6c0b576ff334443369ad1b675fe59bba5f905d72/frontend/dockerfile/dockerfile2llb/convert.go#L1200) might be the origin of the error
3. wrong, nothing has changed in that function between both releases

Now I'm clueless 🤷

**Comment by sneakers-the-rat** [comment]
For the sake of google-ability in case we resolve it the error is:

```
Dockerfile:19
--------------------
  17 |     
  18 |     # Build project. The .git directory is needed for poetry-dynamic-versioning
  19 | >>> COPY ./.git ./.git
  20 |     COPY pyproject.toml poetry.lock README.md .
  21 |     COPY linkml linkml/
--------------------
ERROR: failed to solve: source can't be a git ref for COPY
```

**Comment by sneakers-the-rat** [comment]
I cant find any docs about not being able to do git refs in COPY, but in guides re: how to add git repo they say to use ADD like: https://docs.docker.com/reference/dockerfile/#add---keep-git-dir

**Comment by sneakers-the-rat** [comment]
OK https://github.com/linkml/linkml/pull/1980 fixes. boy i do not care for docker lol

**Comment by Silvanoc** [comment]
> I cant find any docs about not being able to do git refs in COPY, but in guides re: how to add git repo they say to use ADD like: https://docs.docker.com/reference/dockerfile/#add---keep-git-dir

I wonder how `--keep-git-dir` works in our case, since it's meant to be used for Git repos fetched from remote. See what the provided link says:
> When <src> is the HTTP or SSH address of a remote Git repository

I would assume that it works due to some inconsistency between documentation and implementation on buildkit side. Sometimes trying things out is worth, no matter what the documentation says 😄

**Comment by sneakers-the-rat** [comment]
See the commits in https://github.com/linkml/linkml/pull/1980 for trying out several versions :)
