### ISSUE TITLE
Bad link in main page markdown document

### ISSUE THREAD

**Issue by chris-grove** [linkml/linkml#199]
In the main GitHub page documentation there is a line pointing users to the linkml site:

"This documentation is best seen via the linkml site but can also be viewed via the GitHub repository"

but the "linkml site" hyperlink points to a 404:

https://linkml.github.io/linkml/

I'm pretty sure it should just be:

https://linkml.github.io/

**Comment by cmungall** [comment]
I think this is fixed, @sujaypatil96 can you check and close if it is?

**Comment by sujaypatil96** [comment]
The LinkML documentation has been updated since this issue. The docs at https://linkml.github.io/linkml/ don't have any broken links, so this issue is ready to be closed.
