### ISSUE TITLE
Absolute file paths have to be prefixed with "file://" in json-ld contexts

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#2]
Once issue #1 has been fixed, one discovers that absolute file paths (i.d. paths that start with a slash on a Unix system) are actually being treated as relative paths by the rdflib json-ld processor.  If you actually DO have a base (which occurs because of the fix for issue #1) the w3id prefix gets added to a local file name.

To fix this, you need to add "file://" to all absolute file paths.

Note:  I don't know whether this fix will work on a DOS system -- the question is, what does:

```python
import os
print(os.path.abspath('file'))
```

look like on a DOS system?

**Comment by nlharris** [comment]
Is this still needed? If so, who can it be assigned to?
