### ISSUE TITLE
adding metadata to pydantic fields

### ISSUE THREAD

**Issue by djarecka** [linkml/linkml#2005]
**Is your feature request related to a problem? Please describe.**

We are working with the pydantic (v.2) representation of the model, but there are important pieces of informations that are missing from the fields, e.g. `exact mapping` or `local_names` that we need to know to get the correct type of data from external sources.

**Describe the solution you'd like**

I think `exact_mapping`, `local_names` etc. could be added to `metadata` kwarg. of the pydantic `Field` class

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

I would say that the information is critical, but we are thinking about way around: using linkml tools to view the yaml schema 

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

**Comment by sneakers-the-rat** [comment]
gotcha https://github.com/linkml/linkml/pull/2036
