### ISSUE TITLE
Docker build failing for release tags

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#2007]
When 1.7.6 was released the Docker build and push workflow failed: https://github.com/linkml/linkml/actions/runs/8368783078. Specifically, during checkout the following error occurred:

```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules --depth=100 origin +4977f426cf4f3971cd66ea0dbae8fc0d039c7799:refs/tags/v1.7.6
  Error: fatal: Cannot fetch both 4977f426cf4f3971cd66ea0dbae8fc0d039c7799 and refs/tags/v1.7.6 to refs/tags/v1.7.6
```

I believe the culprit was the changes introduced in https://github.com/linkml/linkml/pull/1980. A brief glance at https://github.com/actions/checkout/issues/1467 indicates that there may be a problem with using both `fetch-depth` and `fetch-tags`, but I haven't read through that issue in great detail.

cc @sneakers-the-rat

**Comment by sneakers-the-rat** [comment]
Oh boy you love to see issues like that with a zillion other issues referencing them. Got it in a bit

**Comment by cmungall** [comment]
I am not sure if this is related:

https://twitter.com/chrismungall/status/1748530964605948336

(rarely post to X but was hoping to see a bit more engagement there)

**Comment by sneakers-the-rat** [comment]
This is part of why I do not care for docker
