### ISSUE TITLE
Documentation needs better discussion of inlining (and link there is broken)

### ISSUE THREAD

**Issue by rsc3** [linkml/linkml#2030]
**Describe the bug**
I have noticed several broken links on the website docs so I am opening this issue about them. Please let me know if there is a better place for this.

First one is the FAQ references to inlining is broken

https://linkml.io/linkml/faq/modeling.html#how-do-i-represent-relationships-in-linkml

https://w3id.org/linkml/inlining

In general a think the docs could use a clearer discussion of inlining as I think I just have to try it out on a bunch of examples to understand what it means.

**To reproduce**

**Expected behavior**

**Screenshots**

**About your computer (if applicable, please complete the following information):**

**Additional context**

**Comment by rsc3** [comment]
Maybe it should link here: https://linkml.io/linkml/generators/json-schema.html#inlining I am not sure if inlining is a general term or only applies to JSON Schema

**Comment by rsc3** [comment]
Or here. https://linkml.io/linkml/schemas/inlining.html

**Comment by nlharris** [comment]
I think the link should go to https://linkml.io/linkml/schemas/inlining.html
I can make that change if no one objects.
