### ISSUE TITLE
`any_of` ranges should be reflected in the usages section on slot documentation pages

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#2033]
Slot pages now show all ranges in an any_of union. great!

Imagine that slot S has a range of X or Y

If I visit the pages for X or Y, I should see an entry for S in the usages section

Will provide a concrete example form the NMDC berkeley-schema-fy24 soon.

**Comment by sujaypatil96** [comment]
Thanks for the issue @turbomam 😁 I've started working on a fix for this, but there will be PRs that need to be made into linkml-runtime fixing a couple of `SchemaView` methods. Once the PR and a release containing updates from that PR have been made, we can bring that into [berkeley-schema-fy24](https://github.com/microbiomedata/berkeley-schema-fy24) and other schema repos as well. I'm estimating a turnaround time of 2-3 weeks considering we don't have periodic releases, etc.
