### ISSUE TITLE
Add long description

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#205]
The setup.cfg long_description field is what appears in PyPi.   Not sure what formats PyPi supports, but we need to add one that provides a good jump-off point.

**Comment by sujaypatil96** [comment]
The addition of this [code block](https://github.com/linkml/linkml/blob/main/setup.cfg#L7-L8) via PR #380 solves this issue.

**Comment by gaurav** [comment]
Confirmed that a long description is now present on PyPi (https://pypi.org/project/linkml/), closing.
