### ISSUE TITLE
Unclear if SchemaDefinition.classes can be a list or must be a dictionary

### ISSUE THREAD

**Issue by gaurav** [linkml/linkml#206]
It's unclear to me if the `classes` property of a SchemaDefinition can be be a list, or if it must be a dictionary. According to [the documentation](https://linkml.github.io/linkml-model/docs/classes/), a list of ClassDefinitions is allowed, and the LinkML model specifically allows both lists and dictionaries:
https://github.com/linkml/linkml-model/blob/2747c33cb285ddf89da927ccad74b155e2718745/linkml_model/meta.py#L387-L391

However, if I actually try to use a list, I get an error from some of the generators that consume this model, including `gen-json-schema`, which expects a dictionary in the `linkml/utils/rawloader.py:107` file:
https://gist.github.com/gaurav/8ee077203eae9e22191fc21b8f5847de

Either the documentation or the code should be updated so that they are back in sync.

**Comment by hsolbrig** [comment]
The documentation is correct.  The code needs to be updated - the current `rawloader` package tries to do some processing _before_ it actually loads a schema into an instance of SchemaDefinition.
