### ISSUE TITLE
Validation error message is too vague to fix

### ISSUE THREAD

**Issue by paulmillar** [linkml/linkml#2088]
**Describe the bug**

I ran the command:

    linkml-validate -s DataModels/LinkML/services.yaml Distro/services.json 

to validate a particular JSON file matches the provided description.  There were a few validation errors reported.  Here is an example:

```
[ERROR] [Distro/services.json/0] {'abbreviation': 'VizieR', 'name': 'VizieR astronomical catalogue service', 'resourceOrganisation': 'cds', 'webpage': 'https:/
/vizier.cds.unistra.fr/', 'description': 'The VizieR archive consists of scientific data from refereed astronomy journal publications or data from ground based
 observatories/experiments or space missions. In VizieR terminology, a VizieR dataset is called a “catalogue”. Each "catalogue” can contain: \n\n- Tabular data
: Predominantly related to astronomical objects. \n\n- “Associated data”: non-tabular data such as spectra, images, data cubes etc. associated with journal pub
lications or with an observation catalogue provided by an observatory or a project\n\nThe VizieR service offers the functionalities for interactive and program
matic queries, including access via International Virtual Observatory Alliance (IVOA) protocols.', 'tagline': 'The VizieR astronomical catalogue service VizieR
 provides a library of published astronomical catalogues *tables and associated data* with verified and enriched data, accessible via multiple interfaces.', 'l
ogo': 'https://cds.unistra.fr/img/communication/vizier_420x245.png', 'scientificDomains': [{'scientificDomain': 'scientific_domain-natural_sciences', 'scientif
icSubdomain': 'scientific_subdomain-natural_sciences-physical_sciences'}], 'categories': [{'category': 'category-sharing_and_discovery-data', 'subcategory': 's
ubcategory-sharing_and_discovery-data-scientific_research_data'}], 'targetUsers': ['target_user-researchers', 'target_user-research_organisations', 'target_use
r-research_communities'], 'accessTypes': ['access_type-remote'], 'accessModes': ['access_mode-free'], 'tags': ['astronomy, astrophysics'], 'geographicalAva
ilabilities': ['WW'], 'languageAvailabilities': ['en'], 'resourceGeographicLocations': ['FR', 'US', 'IN', 'ZA', 'JP', 'CN'], 'publicContacts': [{'email': 'cds-ques
tion@unistra.fr', 'organisation': 'cds'}], 'helpdeskEmail': 'cds-question@unistra.fr', 'trl': 'trl-9', 'lifeCycleStatus': 'life_cycle_status-operation', 'certi
fications': ['CoreTrustSeal'], 'standards': ['International Virtual Observatory Alliance (IVOA) standards', 'IVOA VOTable', 'IVOA Cone Search', 'IVOA TAP/ADQL'
, 'FITS', 'OAI-PMH'], 'openSourceTechnologies': ['Python astroquery.vizier'], 'relatedResources': ['cds.simbad_simbad_astronomical_database_provides_basic_data
_cross-identifications_bibliography_and_measurements_for_astronomical_objects_outside_the_solar_system', 'eudat.b2find'], 'catalogueId': 'eosc', 'fundingBody':
 ['funding_body-cnrs', 'funding_body-cnes', 'funding_body-other'], 'helpdeskPage': 'https://cds.unistra.fr/help', 'userManual': 'https://cdsarc.cds.unistra.fr/
vizier/vizHelp/', 'termsOfUse': 'https://cds.unistra.fr/vizier-org/licences_vizier.html', 'privacyPolicy': 'https://cds.unistra.fr/vizier-org/licences_vizier.h
tml', 'maintenance': 'http://cds.unistra.fr/news.php?cat=3', 'orderType': 'order_type-fully_open_access'} is not valid under any of the given schemas in /servi
ces/cds.vizier_astronomical_catalogue_service
```

(Note: the above error is actually a single line.  I have broken it into multiple lines to make it easier to read.)

The message `not valid under any of the given schemas` provides no information on why this particular JSON object is not valid.

**To reproduce**
Create a LinkML description that uses enums,
Create an object that includes an incorrect enum value.
Run the `linkml-validate`

**Expected behavior**

I expect `linkml-validate` to provide sufficient information to understand what is wrong and how to fix it.

**About your computer (if applicable, please complete the following information):**
 
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

 
I'm using LinkML build from git, when the tip of `main` branch is checked out.

**Comment by cmungall** [comment]
Unfortunately this is the standard output of the JSON Schema validator, which we wrap.

I have run into this myself, especially with schemas that rely on a lot of `any_of`s

As a temporary measure, you could use `gen-json-schema` to make a json schema, and try validating your data against tools that purport to give more explanations. E..g https://www.json-buddy.com/ (not tried this)

Longer term, we will be less reliant on wrapping JSON-Schema, but I think that the general issue of making human readable explanations of validation errors of complex schemas (regardless of framework) is a research question.

**Comment by paulmillar** [comment]
Thanks for the comments, @cmungall.  Although I wouldn't want other people to suffer, it's good to hear that I'm not alone in experiencing this issue.

Please see #2089 for a proposed solution to this problem.  If you have a chance, perhaps you could give it a try and see if it is (or would have been) helpful in the situations you described.
