### ISSUE TITLE
value specifications for biolinkml

### ISSUE THREAD

**Issue by wdduncan** [linkml/linkml#21]
In biolinkml, can you define/map literal values to an ontology iri. For example, let's say we want the values "F" to represent a female organism and "M" to represent a male organism. In json-ld you could do something like this:
```
{
"@context":
{

      "ex": "http://example.com/",
      "sex":
      {
          "@id": "ex:sex",
 "@type": "@vocab"
},
        "M": "http://purl.obolibrary.org/obo/CARO_0000027",
"F": "http://purl.obolibrary.org/obo/CARO_0000028"
},
  "@graph":
  [
{
      "@id": "ex:host1",
 "sex": "F"
},
  {
      "@id": "ex:host2",
      "sex": "M"
    }
  ]
}
```
This translates into RDF:
```
<http://example.com/host1> <http://example.com/sex> <http://purl.obolibrary.org/obo/CARO_0000028> .
<http://example.com/host2> <http://example.com/sex> <http://purl.obolibrary.org/obo/CARO_0000027> .
```
The larger point I am trying to get at is that we may get a number of different values form multiple data sources that semantically represent the same kinds of entities (e.g., another data source may use the values "female" and "male"). Can we represent such differing value sets?

**Comment by cmungall** [comment]
this is covered by enums
