### ISSUE TITLE
How should LinkML validate consider slot: None values the same as absent slots values?

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#2117]
I have a pipeline that reads a file into a datamodel using LinkML runtimes converters, and then lives as a dataclass instance in my code. 

The interface to the validators are looking for yaml rather than dataclass instances (which all by itself could be questioned - why not allow dataclass instances to be passed to validator?).

What I access the converted dataclass instances, it instantiates every field. If there is no value, the value is set to `None`. The validator then reports, for example:

```
ERROR:root:None is not of type 'number' in /mappings/1/semantic_similarity_score
ERROR:root:None is not of type 'string' in /mappings/1/semantic_similarity_measure
ERROR:root:None is not of type 'string' in /mappings/1/issue_tracker_item
ERROR:root:None is not of type 'string' in /mappings/1/other
ERROR:root:None is not of type 'string' in /mappings/1/comment
ERROR:root:None is not of type 'string' in /mapping_set_version
```

All of which are optional. I cant control how the dataclasses represent these, e.g.

```
ERROR:root:{'mapping_set_id': 'https://w3id.org/sssom/mappings/7d68e013-fd2e-4e4c-b41f-d5a041257a83', 'license': 'https://creativecommons.org/licenses/by/4.0/', 'mappings': [{'subject_id': 'NANDO:1100001', 'predicate_id': 'skos:exactMatch', 'object_id': 'MONDO:0019056', 'mapping_justification': 'semapv:MappingCuration', 'subject_label': 'Neuromuscular disease', 'subject_category': None, 'predicate_label': None, 'predicate_modifier': None, 'object_label': 'neuromuscular disease', 'object_category': None, 'author_id': [], 'author_label': [], 'reviewer_id': [], 'reviewer_label': [], 'creator_id': [], 'creator_label': [], 'license': None, 'subject_type': None, 'subject_source': None, 'subject_source_version': None, 'object_type': None, 'object_source': None, 'object_source_version': None, 'mapping_provider': None, 'mapping_source': None, 'mapping_cardinality': None, 'mapping_tool': None, 'mapping_tool_version': None, 'mapping_date': None, 'publication_date': None, 'confidence': None, 'curation_rule': [], 'curation_rule_text': [], 
```

What to do? Thank you!

@pkalita-lbl commented the following

> I thought there was an issue or discussion out there about this already, but my searches are coming up empty. I think that LinkML is a little unclear about whether this data (expressed as a Python dict):
```
{
  "a": 1,
  "b": None
}
```
> is the same as this data:
```
{
  "a": 1
}
```
> At the moment the Validator (or at least JSON Schema-based validation) treats them as not the same. That might not be ideal for your particular use case, but I think it makes sense for others. Taking a very brief look at the code here it looks like there is a conversion from a pandas DataFrame happening. I wonder if there's an opportunity in that process to not add None values or perhaps strip them out afterwards.

Which is "the LinkML way" - filtering out dictionary elements with `None` values, or changing the tools to treat them the same?

**Comment by cmungall** [comment]
The reason @pkalita-lbl's search didn't find the existing issue is because it's a discussion:

- https://github.com/orgs/linkml/discussions/1975

I'll close this issue for now to avoid redundancy, but if the discussion results in a proposal to implement a distinction we can make an enhancement issue

**Comment by cmungall** [comment]
tho it seems maybe the jsonschema validator doesn't treat them as the same - I think it should strip out the Nones
