### ISSUE TITLE
JSON-LD Context Generator Enums ("@vocab": "@null")

### ISSUE THREAD

**Issue by vincentkelleher** [linkml/linkml#2122]
Hi 👋 

When trying to parse a generated JSON-LD context using tools such as [JSON-LD Playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2F2018%2Fcredentials%2Fv1%22%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%2Fsuites%2Fjws-2020%2Fv1%22%2C%22https%3A%2F%2Fw3id.org%2Fgaia-x%2Fdevelopment%23%22%5D%2C%22type%22%3A%5B%22VerifiableCredential%22%5D%2C%22id%22%3A%22did%3Aweb%3Agaia-x.eu%23my-legal-registration-numbe%22%2C%22issuer%22%3A%22did%3Aweb%3Alocalhost%3A3000%3Amain%22%2C%22issuanceDate%22%3A%222024-05-22T11%3A04%3A05.111%2B02%3A01%22%2C%22credentialSubject%22%3A%7B%22id%22%3A%22did%3Aweb%3Agaia-x.eu%3AlegalRegistrationNumber.json%22%2C%22type%22%3A%22gx%3AlegalRegistrationNumber%22%2C%22gx%3AvatID%22%3A%22FR79537407926%22%2C%22gx%3AvatID-countryCode%22%3A%22FR%22%7D%2C%22evidence%22%3A%5B%7B%22gx%3AevidenceOf%22%3A%22VAT_ID%22%2C%22gx%3AevidenceURL%22%3A%22https%3A%2F%2Fec.europa.eu%2Ftaxation_customs%2Fvies%2Fservices%2FcheckVatService%22%2C%22gx%3AexecutionDate%22%3A%222024-05-22T11%3A04%3A05.110%2B02%3A03%22%7D%5D%7D) with `safe` mode set to `true`, I get a `relative @vocab reference` error.

I've noticed that LinkML uses [an `ENUM_CONTEXT` constant](https://github.com/linkml/linkml/blob/2407a2f2c629092c15da6e0295600d895d34a465/linkml/generators/jsonldcontextgen.py#L23) to supply a specific context for enums. This context uses `"@vocab": "@null"` which is causing the issue mentioned above, this issue has been mentioned by @hsolbrig in #173 too.

From what I understand this `"@vocab": "@null"` is used during JSON-LD Framing and could be useful to _reset_ the JSON-LD context for an element but could someone explain why it is used here instead of just using `null` ?

### JSON-LD Playground Settings

Once you've clicked on the link above to open my example in JSON-LD Playground, you must enable safe mode on the processor.

![image](https://github.com/linkml/linkml/assets/4272277/4273ae92-19a3-42eb-90a3-b41e3391ce1e)

Once that's selected you will get the following error.

![image](https://github.com/linkml/linkml/assets/4272277/f4428c8f-a27f-4156-b095-690bc22fb855)

**Comment by vincentkelleher** [comment]
I've raised https://github.com/linkml/linkml/pull/2152 to fix this issue but the Github Actions pipeline constantly fails due to rate-limiting and issues connecting to kroki.io 😢 

Can someone help with this ?

**Comment by dalito** [comment]
You mean codecov? The code coverage could be checked and reported without an external service, see e.g. https://github.com/hynek/structlog/blob/main/.github/workflows/ci.yml. I also did this for ucumvert: ([report example](https://github.com/dalito/ucumvert/actions/runs/8350231121)).

**Comment by vincentkelleher** [comment]
Thanks @dalito for the tip 👍  Although it's the existing test pipeline that failed, not something I changed.

Finally, I got lucky and the pipeline was successful 🎉

**Comment by vincentkelleher** [comment]
https://github.com/linkml/linkml/pull/2152 has been merged so this issue can now be closed 🎉
