### ISSUE TITLE
`linkml-ws` Command Not Found after `pip install linkml`

### ISSUE THREAD

**Issue by NeilGraham** [linkml/linkml#2221]
**Describe the bug:**

- After running `pip install linkml`, the command `linkml-ws` is not found.

**To reproduce:**
1. Install LinkML using `pip install linkml`
2. Running the command `linkml-ws` or `linkml-ws --help` results in the command not being found.

**Expected behavior:**

- I am unable to initialize a new LinkML project directory because the command `linkml-ws` is not found.

**About your computer:**
 - OS: Microsoft Windows 11 Home
 - Version 10.0.22631 Build 22631

**Additional context:**

- The command `gen-project` is found.
- Also tested on Ubuntu 24.04 LTS (WSL2) with same issue.

**Comment by sierra-moxon** [comment]
Thanks for the issue @NeilGraham - can I ask how you tracked down the `linkml-ws` command in our documentation?  I think we are trying to encourage folks to use our `linkml-project-cookiecutter` for new-project setups: https://github.com/linkml/linkml-project-cookiecutter but we still may have documentation pointing to the older setup.

**Comment by NeilGraham** [comment]
@sierra-moxon Thank you for clarifying.

I was following the Quick Installation documentation here: https://linkml.io/linkml/intro/install.html 
(Github file location: https://github.com/linkml/linkml/blob/main/docs/intro/install.md)

**Comment by sneakers-the-rat** [comment]
got it https://github.com/linkml/linkml/pull/2226
