### ISSUE TITLE
Docstring of `SchemaView.all_classes` method contains typo

### ISSUE THREAD

**Issue by eecavanna** [linkml/linkml#2233]
Here's the line of code containing the typo (I think it originated as a copy/paste from a different method):

https://github.com/linkml/linkml-runtime/blob/09b1f0c6a8bd55b794068879a0c4db0315c6f822/linkml_runtime/utils/schemaview.py#L402

It says "slots" where I think the author meant for it to say "classes".

Proposal:

```diff
-         :param ordered_by: an enumerated parameter that returns all the slots in the order specified.
+         :param ordered_by: an enumerated parameter that returns all the classes in the order specified.
```

**Comment by nlharris** [comment]
This is a good example of an issue where the reporting person could create a PR to propose a fix! Do you want to try that, @eecavanna?

**Comment by eecavanna** [comment]
Hi @nlharris, sorry about the delay. Under normal circumstances, I am open to opening PRs. This ticket fell off my radar (I don't remember what was happening in late July that prevented me from opening a PR at that time).

Thanks for fixing this (in https://github.com/linkml/linkml-runtime/commit/cf9ada15d0ce36c8125ae38e851acfdf80bcc8f7). I'll close this ticket.
