### ISSUE TITLE
Change bug report template

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#2250]
I have no idea why we ask people for their web browser in our github issue template.

And why screenshots? Most people will be using an IDE or command line or environment in which precise formatted text can be pasted

personally and perhaps ironically when I submit issues I don't like to be constrained by templates or schemas.. we should only ask the most important information. If we do want to gather info, I would say the most relevant things to ask in order are:

- have you provided both a schema (and if applicable, a data file) that replicates the issue
- version of linkml

then maybe

- how did you install linkml
- what version of python (if you know)

**Comment by nlharris** [comment]
I can edit the templates as you describe, if that sounds good to others (e.g. @sierra-moxon).

https://github.com/linkml/linkml/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1
https://github.com/linkml/linkml/blob/main/.github/ISSUE_TEMPLATE/feature_request.md?plain=1
