### ISSUE TITLE
linkml-pr-bot introduced a non-existent debugpy release

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#2259]
Our pr-bot updated the poetry lock as normal:

- #2253         

Including bumping debugpy from 1.8.2 to 1.8.3

https://github.com/linkml/linkml/commit/6d721db3d74dd9a0c356b0972490d698ce5ab839#diff-f53a023eedfa3fbf2925ec7dc76eecdc954ea94b7e47065393dbad519613dc89R669-R673

Problem: this does not exist!

https://pypi.org/project/debugpy/1.8.3/

It turns it was *removed*, not *yanked*, and we are not the only ones to be affected:

https://github.com/microsoft/debugpy/issues/1647

**Comment by dalito** [comment]
Fixed in #2261
