### ISSUE TITLE
Trying to use linkml-validate in python3

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#2286]
**Describe the bug**
When I simply add this one line to a python script which has no other lines of code (running Python 3.11.7):

`from linkml.validator import Validator`

and try to run the script, I get this error right at the import line, with no further processing.

`"Input LinkML schema file not given"`

**Version of LinkML you are using**
linkml-validate, version 1.8.3

**Please provide a schema (and if applicable, a data file) that replicates the issue**
Just a one line file with import above, or I also tried:
from linkml.validator import validator

**Comment by cmungall** [comment]
I'm unable to reproduce this..

**Comment by nlharris** [comment]
Can someone else try this? Maybe there's some difference in Damion and Chris's environments that's causing the difference in behavior? Which version of Python are you using, @cmungall?

**Comment by cmungall** [comment]
Looks like the error is coming from DH, maybe you should ask the author of DH about the bug @ddooley 😉 

https://github.com/cidgoh/DataHarmonizer/blob/4925e6a7c1c7e062018b55c1f6d5e188dfcdecba/script/linkml.py#L47-L49

**Comment by ddooley** [comment]
Thanks for that hint, OMG, the now unused script in same folder called "linkml.py" was intercepting the linkml import.  Add one more day that I feel like a dunce!  Thx.
