### ISSUE TITLE
Strange translation of specific enums

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#232]
I have tried to define an enum:

```
enums:
  mapping_cardinality_enum:
    permissible_values:
      1:1:
      1:n:
      n:1:
      1:0:
      0:1:
      n:n:
```

Translating this to 

```
rdfs:range <http://UNKNOWN.org/mapping_cardinality_enum> 
```

in OWL and

```
class MappingCardinalityEnum(EnumDefinitionImpl):

    _defn = EnumDefinition(
        name="MappingCardinalityEnum",
    )

    @classmethod
    def _addvals(cls):
        setattr(cls, "61",
                PermissibleValue(text="61") )
        setattr(cls, "1:n",
                PermissibleValue(text="1:n") )
        setattr(cls, "n:1",
                PermissibleValue(text="n:1") )
        setattr(cls, "60",
                PermissibleValue(text="60") )
        setattr(cls, "0:1",
                PermissibleValue(text="0:1") )
        setattr(cls, "n:n",
                PermissibleValue(text="n:n") )

```

In the python data classes. What are these 60 and 61 values?

**Comment by hsolbrig** [comment]
Boy, you are definitely pushing the limits of the Enumeration definition  :-)

The 60 and 61 are undoubtedly the octal representations of the values "0" and "1".  _WHY_  we've managed to convert the text "1:0:" into those two values is a bit of a mystery, as well as why "0:1" made it through unscathed.   My guess is that that the answers lie deep in the bowls of the yaml spec?   (Try quoting the `0:1:` in the source?)

**Comment by matentzn** [comment]
Thats great, solves it! Thank you!
