### ISSUE TITLE
Need contributing.md

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#237]
Need to document how testing is done

**Comment by cmungall** [comment]
* [ ] document how to extend linkml-model and how to bring this into linkml-runtime (there is a video of @hsolbrig and I doing this)
 * [ ] document test framework
      - when do we check things into output/ folders
      - naming conventions for test_issues (I use linkml_test_NNN to distinguish from numbering system from biolinkml)
      - document the strategy of comparing outputs and how to read the false positives

**Comment by cmungall** [comment]
@sujaypatil96 added: https://github.com/linkml/linkml/blob/main/CONTRIBUTING.md
