### ISSUE TITLE
Unintuitive type errors in Pydantic classes with optional fields

### ISSUE THREAD

**Issue by ptgolden** [linkml/linkml#2377]
**Describe the bug**
When code instantiating Pydantic models built through LinkML is type-checked with Pyright, optional fields not included in kwargs to the constructor are marked as missing. I have not tested, but I imagine this is the case with schemas with default values as well. The cause of this is described [here](https://github.com/pydantic/pydantic/issues/3617) and [here](https://github.com/pydantic/pydantic/issues/3753).

**Version of LinkML you are using**
1.8.4

**Please provide a schema (and if applicable, a data file) that replicates the issue**
Given this schema:
```
id: http://example.com/thing
imports:
  - linkml:types

classes:
  Thing:
    attributes:
      id:
        identifier: true
      label:
        required: true
        range: string
      tag:
        range: string
```

And this example code, not including optional `tag`:
```
from model import Thing

thing = Thing(id="id", label="label")
```

Output from pyright:
```
$ pyright main.py 

/home/ptgolden/Code/tmp/linkml-pydantic/main.py
  /home/ptgolden/Code/tmp/linkml-pydantic/main.py:3:9 - error: Argument missing for parameter "tag" (reportCallIssue)
1 error, 0 warnings, 0 informations
```

---

This error is fixed by explicitly setting default values via keyword in generated Pydantic definitions. That is, changing the generated code from this:
```
class Thing(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'http://example.com/thing'})

    id: str = Field(..., json_schema_extra = { "linkml_meta": {'alias': 'id', 'domain_of': ['Thing']} })
    label: str = Field(..., json_schema_extra = { "linkml_meta": {'alias': 'label', 'domain_of': ['Thing']} })
    tag: Optional[str] = Field(None, json_schema_extra = { "linkml_meta": {'alias': 'tag', 'domain_of': ['Thing']} })

```
to this
```
class Thing(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'http://example.com/thing'})

    id: str = Field(..., json_schema_extra = { "linkml_meta": {'alias': 'id', 'domain_of': ['Thing']} })
    label: str = Field(..., json_schema_extra = { "linkml_meta": {'alias': 'label', 'domain_of': ['Thing']} })
    tag: Optional[str] = Field(default=None, json_schema_extra = { "linkml_meta": {'alias': 'tag', 'domain_of': ['Thing']} })

```

(Note the `default=` addition)

Passing the default keyword via a keyword should not be a change requiring much work, since it is the only allowed positional argument in `Field`.

**Comment by nlharris** [comment]
> Passing the default keyword via a keyword should not be a change requiring much work, since it is the only allowed positional argument in `Field`.

Thanks for your bug report. As you may have noticed, we have a large backlog of issues, and very limited developer time to work on these. If you are interested in making a PR to address this issue, we will try to review and merge it quickly!

**Comment by ptgolden** [comment]
Pull request submitted at #2390.

This is not a bug in pydantic or in pyright/pylance, but rather a consequence of [PEP 681](https://peps.python.org/pep-0681/). It is known to pydantic, and mentioned in [their documentation](https://docs.pydantic.dev/latest/integrations/visual_studio_code/#adding-a-default-with-field). The author of pydantic that [he won't change the API to require keyword arguments](https://github.com/pydantic/pydantic/issues/3617#issuecomment-1087437078), which is fair enough!
