### ISSUE TITLE
Author list on Zenodo needs updating

### ISSUE THREAD

**Issue by nlharris** [linkml/linkml#2383]
The list of authors in the [Zendo record](https://zenodo.org/records/13988760) needs updating. I am not sure how that can be updated - I will do it myself if someone can point me to the documentation about how to do it. But first I will discuss the author list with @cmungall and @sierra-moxon.

**Comment by dalito** [comment]
Currently Zenodo reads from your [CITATION.cff](https://github.com/linkml/linkml/blob/main/CITATION.cff) whenever a new release is made. If the `CITATION.cff` file would not be present it would uses the GitHub contributor information but ignore ORCID from the contributor´s GitHub profile (at least last time I tried). The best control over the info in Zenodo you have with a `.zenodo.json` file (see [example](https://github.com/nfdi4cat/voc4cat/blob/main/.zenodo.json) and [result on Zenodo](https://doi.org/10.5281/zenodo.8313340)).

I summarized the info here https://github.com/nfdi4cat/voc4cat-template/issues/17
