### ISSUE TITLE
Add documentation on range for how to use URI

### ISSUE THREAD

**Issue by amc-corey-cox** [linkml/linkml#2391]
**What is your feature request?**
URI's can't be used directly for range but it is common for people to believe that they can. We should enhance the documentation to show how to use appropriate URI's, i.e. instantiate them as a class and set the range to the class.

**How important is this feature to you?** Select from the options below:
• Low - it's just documentation but it may cut down on confusion and 

**Additional context**
We recently had a community member confused about this and asking for guidance. We had a fair amount of back and forth to tell them they needed to instantiate the class. 

I could use some guidance on the best places to put this in the documentation.

**Comment by sierra-moxon** [comment]
from dev call:
- put a `comment` in linkml-model repo near/on the range `description` 
- validation message is generated when you try to use a curie for range (maybe add the error message to the doc)

**Comment by amc-corey-cox** [comment]
Adding this to linkml/linkml-model here:
https://github.com/linkml/linkml-model/pull/207
