### ISSUE TITLE
Multiple docstrings contain grammatical error ("by looked")

### ISSUE THREAD

**Issue by eecavanna** [linkml/linkml#2394]
Multiple docstrings contain the phrase "by looked" where I think the author meant to write "by looking":

Here are the 6 occurrences I see:

https://github.com/linkml/linkml/blob/d9c2eb95d662c84e574958145def04ed4867c89f/linkml/validator/__init__.py#L62-L63

https://github.com/linkml/linkml/blob/d9c2eb95d662c84e574958145def04ed4867c89f/linkml/validator/__init__.py#L101-L102

https://github.com/linkml/linkml/blob/d9c2eb95d662c84e574958145def04ed4867c89f/linkml/validator/validator.py#L50-L51

https://github.com/linkml/linkml/blob/d9c2eb95d662c84e574958145def04ed4867c89f/linkml/validator/validator.py#L63-L64

https://github.com/linkml/linkml/blob/d9c2eb95d662c84e574958145def04ed4867c89f/linkml/validator/validator.py#L75-L76

https://github.com/linkml/linkml/blob/d9c2eb95d662c84e574958145def04ed4867c89f/linkml/validator/validator.py#L91-L92

**Comment by nlharris** [comment]
Thanks, please review PR: https://github.com/linkml/linkml/pull/2396
Next time, I encourage you to do a PR yourself, if you're up for it! Thanks!
