### ISSUE TITLE
Need a namespace manager generator, available at runtime vs. compile time.

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#24]
We need to be able to generate a namespace manager tool
The initial code can be found at:

https://github.com/ncats/translator-modules/blob/ARA_Workflow_API/ncats/translator/identifiers/__init__.py

@RichardBruskiewich  - no action required, just letting you know that we've got this

**Comment by nlharris** [comment]
Is this still active?

**Comment by nlharris** [comment]
@hsolbrig can this be closed?

**Comment by RichardBruskiewich** [comment]
@nlharris , @hsolbrig ...This is pretty ancient, and I'm so very unfamiliar with the latest LinkML code base, so I can't comment any further on the status of this particular component, but if anyone decides that another pair of eyeballs is needed on the any code in LinkML that relates to this issue, just give me a holler and I'll do the needful (just tell me where to look for the code to be reviewed).
