### ISSUE TITLE
linkml-runtime imports deprecated `typing` submodule

### ISSUE THREAD

**Issue by caufieldjh** [linkml/linkml#2420]
**Describe the bug**
`linkml-runtime` imports `re` from `typing`. That submodule is deprecated and removed in Python 3.13.
See https://github.com/python/cpython/issues/82472

Example:
https://github.com/linkml/linkml-runtime/blob/ad74966db72be214a38de19f361df88489286e83/linkml_runtime/utils/slot.py#L2
(that may be the only instance)

This renders `linkml-runtime` incompatible with Python 3.13.

**Comment by caufieldjh** [comment]
Would be fixed by https://github.com/linkml/linkml-runtime/pull/345

**Comment by asadow** [comment]
See #2378

**Comment by caufieldjh** [comment]
Closing as duplicate
