### ISSUE TITLE
Consider Linkml suffixes and mime types

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#249]
We may want to declare an explicit linkml suffix so that (future) syntax driven editors can recognize that we're building linkml (vs. generic yaml).  AS linkml can be written in yaml, json _or_ rdf (and probably csv and other formats) we may want to consider something like "linkml.yaml" or "yaml.linkml"?

Also, we should make mime type entries in the IANA registry (application/linkml+yaml, etc)

**Comment by sierra-moxon** [comment]
Hi @hsolbrig  - is this still a priority?
thanks,
Sierra

**Comment by cmungall** [comment]
low priority but let's keep open

**Comment by sierra-moxon** [comment]
from triage: https://iana.org/ - For consideration on a LinkML dev call (a MIME type), in order to assign someone to go do this work.
