### ISSUE TITLE
JSONLD context prefix with endings other than '/' or '#' not resolved correctly

### ISSUE THREAD

**Issue by jiaola** [linkml/linkml#25]
See [biolink model issue 301 odd CHEBI identifier](https://github.com/biolink/biolink-model/issues/301) for the report. This is because JSONLD is sensitive on how a synonym ends. If it ends with '_' for example in 'CHEBI_', it is not resolved correctly. It can be fixed by a @prefix attribute but only in JSONLD 1.1. See http://tinyurl.com/qmd4ggd for an example. 

To fix this: Add a parameter to the generator that switches between 1.0 and 1.1.  If emit 1.1, add "@version": 1.1 to the first bit of the context.

**Comment by nlharris** [comment]
Would this be considered a bug?
