### ISSUE TITLE
All ontology selectors extension to LinkML, similar to HCA jsonschema

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#274]
The Human Cell Atlas have developed an extension to json-schema that is used for restricting certain values to ontology branches

example from @dosumis:

https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/module/ontology/cell_cycle_ontology.json

```json
"ontology": {
            "description": "An ontology term identifier in the form prefix:accession.",
            "type": "string",
            "graph_restriction":  {
                "ontologies" : ["obo:hcao", "obo:go"],
                "classes": ["GO:0007049", "GO:0022403"],
                "relations": ["rdfs:subClassOf"],
                "direct": false,
                "include_self": false
            },
            "user_friendly": "Cell cycle ontology ID",
            "example": "GO:0051321; GO:0000080"
        },
```

There was an intent to make this officially part of json-schema but I don't think this is currently pursued. There is currently a custom validator that uses OLS to validate. E.g. in the above the value is constrained to be a non-reflexive ancestor of these two GO terms

there is clearly overlap between linkml enums and this and current discussions in CCDH cc @gaurav @balhoff 

I think it would be useful to have linkml enums support selector queries such as the above - thoughts @hsolbrig ?

**Comment by gaurav** [comment]
I think something like this could be very neat to have in LinkML!

**Comment by deepakunni3** [comment]
I agree! 💯 

This can extend the scope of what can be captured in LinkML as part of the schema/model itself

**Comment by cmungall** [comment]
See also AIRR https://github.com/airr-community/airr-standards/blob/master/specs/airr-schema-openapi3.yaml

for example, the species field is filled by an ontology term that is restricted to come from a branch of NCBITaxon:

```yaml
        species:
            $ref: '#/Ontology'
            nullable: false
            description: Binomial designation of subject's species
            title: Organism
            example:
                id: NCBITAXON:9606
                label: Homo sapiens
            x-airr:
                miairr: essential
                adc-query-support: true
                set: 1
                subset: subject
                name: Organism
                format: ontology
                ontology:
                    draft: false
                    top_node:
                        id: NCBITAXON:7776
                        label: Gnathostomata
```

This is the relevant part of the extensions spec:

https://github.com/airr-community/airr-standards/blob/d5857a47bee7e250281bdd70d12b8e1c3a08c127/specs/airr-schema.yaml#L122-L140

**Comment by cmungall** [comment]
See also this discussion:
https://github.com/json-schema-org/community/discussions/142

**Comment by cmungall** [comment]
Another use case

cellxgene format is a really nicely documented well thought out format for single cell data:

https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/2.0.0/schema.md

you can see they have thought carefully about which ontology terms can be used with different slots (keys)

some examples:

> categorical with str categories. This MUST be a child of [NCBITaxon:33208 (http://purl.obolibrary.org/obo/NCBITaxon_33208) for Metazoa.

> categorical with str categories. This MUST be a child of [PATO:0001894](http://purl.obolibrary.org/obo/PATO_0001894) for phenotypic sex or "unknown" if unavailable.

currently the metadata seems to be expressed as a markdown file of conventions on top of the AnnData matrix data standard. This is likely sufficient and perhaps linkml would be overkill here, but I think it would be nice to demonstrate how we could make a more computable schema for this, with dynamic enums driven by ontology selector queries

**Comment by cmungall** [comment]
We discussed this on the 2022-04-06 call

@joeflack4 @hsolbrig - can you provide a link to the presentation you gave and give a brief summary of where we stand? Can you also provide a link to external material, e.g. TCCM repo?

**Comment by joeflack4** [comment]
**Link to presentation**
https://docs.google.com/presentation/d/1qK6s6Alk67-3l7lLyuyZm2haoHWIjXyMdORAZ39kgYc/edit#slide=id.p

**Summary of where we stand**
We're working on i. LinkML model for CodeSet, ii. LinkML model for Enumeration, iii. TCCM API for CodeSet and Enumeration. I still need to to make GitHub issues for these. @hsolbrig might be able to correct me / elaborate.

**Additional links**
1. Repo for full TCCM LinkML model (not currently used by TCCM API): https://github.com/HOT-Ecosystem/tccm
2. Repo for limited subset of TCCM LinkML model (used by TCCM API): https://github.com/HOT-Ecosystem/tccm-model
3. Repo for TCCM API: https://github.com/HOT-Ecosystem/tccm-api
4. Repo for CCDH Terminology Service (an instance of a web API that extends TCCM API): https://github.com/cancerDHC/ccdh-terminology-service
5. CCDH Terminology Service instance (w/ swagger UI): https://terminology.ccdh.io

**Comment by cmungall** [comment]
Added in LinkML 1.3

**Comment by cmungall** [comment]
For people ending up on this issue:

https://linkml.io/linkml/schemas/enums.html#dynamic-enums
