### ISSUE TITLE
Consider adding Pipfile.lock to github

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#277]
At the moment, Pipfile.lock is in .gitignore.  The Python community philosophy (as near as I can tell) is that libraries ONLY use Pipfile and applications/programs include the lock file -- the idea being that, with a lock, the program is determinant, but you have to negotiate libraries amongst modules.

Before we make this change, however, we need to know whether folks are using linkml as a library in other packages...

**Comment by cmungall** [comment]
I don't understand why nothing shows here: https://github.com/linkml/linkml/network/dependents

But of course there are many projects that use it e.g https://github.com/microbiomedata/nmdc-schema/blob/main/requirements.txt

**Comment by deepakunni3** [comment]
Locking dependencies via a Pipfile.lock does help in having deterministic behavior for linkml, but it will cause issues with other libraries (we have seen this countless of times in Ontobio).

Like Chris mentioned above, linkml is being used to build the schema in many projects like NMDC (although it doesn't show on the dependents graph). 

But the scenario where locking dependencies will become an issue is when linkml is used to build other tools. For example, [biolink-model-toolkit](https://github.com/biolink/biolink-model-toolkit/) uses linkml as a dependency. 

We at GHGA are looking to build something like bmt to ensure that our APIs and services are schema aware.
So it is entirely possible that linkml serves as a direct dependency for many other downstream applications.

**Comment by deepakunni3** [comment]
@cmungall Regarding why nothing shows on the dependents tab, see https://github.community/t/bug-project-not-showing-network-dependents/3161

This seems to be a common bug in GitHub itself where dependencies are registered only in one direction.

Looks like they are solving it on a case-by-case basis, after contacting GitHub Support.
