### ISSUE TITLE
Inline properties of classes of custom types

### ISSUE THREAD

**Issue by deepakunni3** [linkml/linkml#28]
<img width="1042" alt="Screen Shot 2020-05-28 at 3 39 01 PM" src="https://user-images.githubusercontent.com/4530272/83200989-6335ea00-a0f9-11ea-9440-ee3dd0ea22a9.png">

When defining custom types, it would be good to have them be folded into the class that references these types.

For example, in the case of class `Biosample`, instead of having 5 arrows go to other types, would be nice to have them inline:

<img width="359" alt="Screen Shot 2020-05-28 at 3 46 23 PM" src="https://user-images.githubusercontent.com/4530272/83201479-67163c00-a0fa-11ea-8f25-872b3a41e653.png">

**Comment by sierra-moxon** [comment]
@sujaypatil96 - this is a good ticket for mermaid diagram.  From triage meeting, we want to keep types in the classes themselves, not as a arrowed diagram links to the type as a "box"

**Comment by hsolbrig** [comment]
I think we're using two different definitions of "Type".  LinkML has a `types` section that defines the basic data types.  These are the things that have to be mapped to a given target language.  The elements such as `TextValue` and the like in the above diagram are not "types" in the above sense.  As the model is today, is there any way to differentiate between "Biosample" and "TextValue"?

One useful distinction might be between classes that have an identifier element and those that do not?  Another might be to pay attention to the `inlined` attribute for a slot and draw it as "inlined"?

**Comment by sierra-moxon** [comment]
I believe we've handled this by not linking out to types in mermaid.
