### ISSUE TITLE
Schema/model version not included in artifacts generated via generators

### ISSUE THREAD

**Issue by deepakunni3** [linkml/linkml#285]
Schema/model version, via `version` slot, is not serialized into artifacts like Python dataclasses, OWL, JSONSchema, etc.
The only artifact that seems to have the version is the RDF TTL.

I think there is value in including both metamodel version as well as model version.

**Comment by deepakunni3** [comment]
If this has not yet been worked on then I can take a stab at it :)

**Comment by sierra-moxon** [comment]
closing as completed; thanks @deepakunni3 !
