### ISSUE TITLE
Investigate rdflib 6.0.0 and rdflib-jsonld

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#291]
rdflib 6.0.0 has a built in json-ld processor that is beta 1.1.  We need to see whether it would make more sense to move to this

**Comment by matentzn** [comment]
I think we need to prioritise this.. SSSOM builds are failing now because

- linkml needs RDFLIB 5
- rdflib 5 needs rdflib-jsonld
- rdflib-jsonld does not work with the latest setuptools anymore
-

**Comment by cmungall** [comment]
Wait, so the change from 0.6.1 to  https://github.com/RDFLib/rdflib-jsonld/releases/tag/0.6.2 was to **remove all functionality**. Really?

Anyway the fix is straightforward, just say <=0.6.1 in Pipfile?

Is this setuptools thing not a red herring?

**Comment by matentzn** [comment]
Will revert later. Not sure what is or was a red herring, but according to @hrshdhgd we still need to pin setup tools

**Comment by matentzn** [comment]
But at least the check pass now: https://github.com/mapping-commons/sssom-py/pull/148/files

**Comment by cmungall** [comment]
@hsolbrig will work on this with @putmantime

**Comment by cmungall** [comment]
we are now using rdflib6
