### ISSUE TITLE
Explicate boolean absent values

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#299]
**Is your feature request related to a problem? Please describe.**
Right now, if you omit a boolean value it sort-a defaults to `False`.  This is mostly because `if cls.slot:` treats `None` and `False` the same way.  We would suggest that we require that this behavior be explicit -- if it defaults to "False", add the line `ifabsent: false` to the definition itself.   

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Long-term - 6 months - 1 year

**Additional context**

**Comment by sierra-moxon** [comment]
if you put in an optional slot, (default to True), we have to put it in slightly differently because we can't default to "if absent = true"

**Comment by hsolbrig** [comment]
@sierra-moxon  - not sure I understand the above comment.  The snipped below:
```
   slots:
       is_needed:
           range: boolean
           ifabsent: True
```
Behaves as expected.  To be honest, I'm inclined to not do anything wrt. this issue besides some more documentation.  If we changed the boolean type to require an `ifabsent`, we'd pretty much break the internet.

**Comment by nlharris** [comment]
Can we close this as won't do?

**Comment by cmungall** [comment]
- https://github.com/orgs/linkml/discussions/2147
- https://github.com/orgs/linkml/discussions/1975
