### ISSUE TITLE
Python generator has hard coded prefix checks

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#3]
Imports to external modules (https://w3id.org/biolink/biolink-model/... and https://w3id.org/linkml/linkml/...) are referenced by hard-coded tweaks in the python imports generator.  We need to figure out how to map a uri to the appropriate import.

Note that biolinkml has a temporary fix to identify https://w3id.org/linkml/...

**Comment by sierra-moxon** [comment]
I no longer see hardcoded references to external modules in pythongen.  closing as complete; please reopen if I go this wrong.
