### ISSUE TITLE
Replace `definitions` with `$defs` in jsonschemagen.py

### ISSUE THREAD

**Issue by gaurav** [linkml/linkml#305]
jsonschemagen.py currently writes out definitions into the `definitions` field, but the JSON Schema recommends [using `$defs` instead](https://json-schema.org/understanding-json-schema/structuring.html#defs) (as of [2019](https://json-schema.org/draft/2019-09/release-notes.html#semi-incompatible-changes)). This should only require changes in the following lines:

https://github.com/linkml/linkml/blob/555d044d84128d37b009ebe6e09305a8d04baac7/linkml/generators/jsonschemagen.py#L47-L108

Originally reported as https://github.com/cancerDHC/ccdhmodel/issues/86

**Comment by cmungall** [comment]
ok - tag @wdduncan when you have a PR as we'd like to double check it for NMDC
