### ISSUE TITLE
compare with great expectations

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#307]
https://docs.greatexpectations.io/docs/why_use_ge

**Comment by cmungall** [comment]
Should be straightforward to compile down to GE expressions

**Comment by nlharris** [comment]
Is this still needed?

**Comment by cmungall** [comment]
It seems GX went from being a lightweight validation library to a full-blown cloud solution. It seemed to be impossible to find a link to the spec now. No one is asking for this, closing until there is interest.

**Comment by cmungall** [comment]
non-cloud core https://greatexpectations.io/gx-core/
