### ISSUE TITLE
Add a standard schema for reporting results of validation

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#325]
We should have a standard datamodel for representing the results of running validation (jsonschema, sparql, shex, shacl, sql, ...) over data. For example

 - string does not match regex pattern
 - required field missing
 - recommended field missing (WARN not ERROR)
 - cardinality violation
 - range constraint violation

Right now we are frequently using jsonschema validators directly, which works well, but a useful feature would be to have a unified interface that can be used to validate different kinds of data (in a sparql endpoint; in CSVs; in a SQL db; in a local ttl file; in a local json file; etc) using different validators (e.g. shex will have different expressivity than jsonschema)

The common interface would represent results in a standard schema, e.g.

 - the data instance that is problematic
 - the slot that is problematic, if any
 - severity
 - the dataset the instance belongs to (e.g. json file; named graph in triplestore)
 - further info

**Comment by gaurav** [comment]
This is a great idea! The SHACL specification defines a ValidationReport that is used to report SHACL validation errors. Might be a good idea to steal ideas from there: https://www.w3.org/TR/shacl/#validation-report

**Comment by cmungall** [comment]
https://github.com/linkml/linkml-model/blob/main/linkml_model/model/schema/validation.yaml

**Comment by cmungall** [comment]
completed
