### ISSUE TITLE
Improve comparisions between expected and actual outputs in the test suite

### ISSUE THREAD

**Issue by gaurav** [linkml/linkml#326]
**Is your feature request related to a problem? Please describe.**
Currently, expected and actual outputs differ because of minor changes such as [the generation date changing](https://github.com/linkml/linkml/commit/a7c1992dfefe5d302c0f8565932a25549688ef3f#diff-67acf396f2c7a4a9a9241d8861d60e56d9f1a58e62a4c468d88e41709b674979) or the [order of a list changes](https://github.com/linkml/linkml/commit/a7c1992dfefe5d302c0f8565932a25549688ef3f#diff-eb833dc1ecdf46a17fd3bdcb7fd5e864048a78be29d742c498d751e07defc7de). This makes it difficult to identify the relevant changes when looking at diffs like a7c1992dfefe5d302c0f8565932a25549688ef3f -- buried in there is the actual new files that have been created for the last PR, but it's really hard to tell where they are.

**Describe the solution you'd like**
Some possible solutions:
1. Fix/replace the JSON/YAML/RDF generators so that lists are always arranged in a particular way.
2. Provide a configuration setting so that generation dates are not generated, or a particular fixed point in time is always used so that output files remain consistent.
3. Create a script that deletes or edits the generation time lines in the output file so that the comparison can be made.

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Long-term - 6 months - 1 year

**Additional context**
N/A

**Comment by pkalita-lbl** [comment]
I believe this has been addressed by the introduction of the [snapshot test fixture](https://github.com/linkml/linkml/blob/d01019d9bd5bcbbda9e236755b03cbd61fceed13/tests/conftest.py#L127). It has code that specifically patches certain schema metadata fields so that they don't produce inconsequential diffs.
