### ISSUE TITLE
Replace GitHub Action test regeneration with manual test regeneration

### ISSUE THREAD

**Issue by gaurav** [linkml/linkml#327]
**Is your feature request related to a problem? Please describe.**
Currently, [a GitHub Action](https://github.com/linkml/linkml/runs/3509419022) (acting as `actions-user`) regenerates expected test files whenever changes are [merged into the `main` branch](https://github.com/linkml/linkml/blob/main/.github/workflows/main.yaml#L59-L71) (e.g. a7c1992dfefe5d302c0f8565932a25549688ef3f). Confusingly, this means that the PR that caused these changes (https://github.com/linkml/linkml/pull/323) only includes changes to the input files in the test suite: the changes in the expected output are in a separate commit that occurs after the PR has been merged into `main` (in this case, a7c1992dfefe5d302c0f8565932a25549688ef3f). I think it would be better if the PR contained both changes to input _and_ expected files -- among other things, looking at changes in expected output would be quite helpful in 

**Describe the solution you'd like**
Some possible solutions include:
- Using an environmental variable to manually regenerate expected outputs, which would then be included in the PR for review. This would change the developer workflow to:
    1. Make software changes.
    2. Rerun tests; note that tests are failing as expected because of the updated software.
    3. Rerun tests with an `OVERWRITE_EXPECTED` environmental variable, i.e. `OVERWRITE_EXPECTED=1 make test`. This will cause the expected output files to be overwritten.
    4. Check `git diff` to make sure that the expected output files have been changed as expected.
    5. Commit changes into PR.
    6. Rerun tests to make sure that they all pass now.
- Changing the GitHub Action so that it runs inside the PR, i.e. by changing its trigger to occur when [a PR is marked as "ready for review"](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request).

Note that for both of these changes, it would help to minimize the number of differences between the expected and actual output files (as covered by #326).

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Long-term - 6 months - 1 year

**Additional context**
N/A

**Comment by pkalita-lbl** [comment]
Closing this issue as no longer relevant. 

The GitHub Action referenced in this issue no longer exists. The current recommended way of writing tests that compare against a known, expected file is via the `snapshot` [fixture](https://linkml.io/linkml/contributing/contributing.html#custom-pytest-fixtures). Using the fixture it is expected that you check in snapshot changes along with your code/test changes.
