### ISSUE TITLE
1.1.1 did not get released to pypi

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#356]
This was apparently successful
https://github.com/linkml/linkml/actions/runs/1255062115

![image](https://user-images.githubusercontent.com/50745/134251102-892e397e-fe64-4fbc-82dd-7c81b33c6e16.png)

but it was released as 0.0.0, not 1.1.1

![image](https://user-images.githubusercontent.com/50745/134250961-87fc0867-3456-444e-9325-a6efd179b394.png)

**Comment by gaurav** [comment]
A rare triple off-by-one error 😛

**Comment by cmungall** [comment]
@sierra-moxon I fear this may be an unintended consequence of #332 :-(

**Comment by cmungall** [comment]
this seems to be fixed

FWIW, this happened again with the release prior to last but simply triggering action again fixed it!
