### ISSUE TITLE
Ensure all validators produce output in the same format and data model

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#368]
Currently the differennt validators each produce their own output - we should make them produce standard objects (see linkml_model.validation) and standard output

**Comment by cmungall** [comment]
We may want to follow the OAK model here

The interface returns an iterator over Validation objects:

https://github.com/INCATools/ontology-access-kit/blob/63df41569f2f62f1fe67c4ff81be770ca3c620d6/src/oaklib/interfaces/validator_interface.py#L48-L59

- this uses an iterator. This is useful if we later want to have say a BigTable validator that validates row by row in a streaming fashion
- it uses a Validation data model that is similar to the LinkML one (which itself came from shacl)

Data model: 

https://incatools.github.io/ontology-access-kit/datamodels/association/index.html

LinkML model:

https://github.com/linkml/linkml-model/blob/main/linkml_model/model/schema/validation.yaml

**Comment by j-simmons-phd** [comment]
+1 to addressing this issue.

**Comment by j-simmons-phd** [comment]
@sierra-moxon thanks for the instructions.  Official upvote added.

**Comment by cmungall** [comment]
Covered by #1555 (sorry to split the vote!)
