### ISSUE TITLE
Fix JSON Schema Generator to support handling of empty enums

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#369]
**Describe the bug**
This bug is related to issue [#85](https://github.com/cancerDHC/ccdhmodel/issues/85) on the [ccdhmodel](https://github.com/cancerDHC/ccdhmodel) repo. The issue highlights the fact that LinkML schemas, and consequently the generated JSON Schemas accept empty enums, i.e., enums without any values. This doesn't obey the [latest standards](https://json-schema.org/draft/2020-12/json-schema-validation.html#enum) as laid out by JSON Schema consortium. We should modify the JSON Schema generator in LinkML so that it outputs valid JSON Schema.

**To Reproduce**
1. Generate JSON Schema with LinkML
2. Validate it using the [Safer202012Validator](https://github.com/cancerDHC/ccdhmodel/blob/update-linkml/tests/test_validate_artifacts.py#L28)

**Expected behavior**
The [Safer202012Validator](https://github.com/cancerDHC/ccdhmodel/blob/update-linkml/tests/test_validate_artifacts.py#L28) shouldn't produce any errors. We can resolve this error in three ways:

- Add a single value called `null` to the empty enum
- Convert enum to a simple string
- Throw Exception asking user to fix LinkML schema

**Comment by sujaypatil96** [comment]
Linked to issue #127.

**Comment by sujaypatil96** [comment]
Note to self: check latest JSON Schema generator implementation and check if this issue is still relevant, and close it out if it's not.

**Comment by pkalita-lbl** [comment]
In the latest version of the JSON Schema generator, an `EnumDefinition` with no `permissible_values` will not generate an `enum` keyword in JSON Schema. This makes it sort of a no-op in JSON Schema just like it is in LinkML
