### ISSUE TITLE
Add `--version` flag

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#378]
As per https://clig.dev/ we should have a `--version` flag on generator and other commands. This should display the linkml version - perhaps also runtime.

not sure how to implement this:

```python
>>> import linkml
RDFLib Version: 5.0.0
>>> linkml.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'linkml' has no attribute '__version__'
```

**Comment by cmungall** [comment]
We need to solve this problem generally:

- the metamodel docs should show the version of linkml-model
- generated schemas should show the version of the schema in their own docs
- all tools should be able to report on the version of that tool, and also the version of the metamodel

The general blocker here is that we use github releases to handle all aspects of releases, including assigning version tags. This means the versions in all out pyproject.yaml files is 0.0.0, making introspection hard.

**Comment by dalito** [comment]
For automatic versioning with poetry, you may use https://github.com/mtkennerly/poetry-dynamic-versioning - It solved poetry`s automatic versioning problem for me. The version can be derived from a git-tag and temporarily injected to files you want. Can this not solve the 0.0.0 problem?

**Comment by cmungall** [comment]
oooh this may be just what we need!! thank you @dalito!
