### ISSUE TITLE
generators should take an --expand-slots option to control whether induced slot names are visible

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#385]
Context: https://github.com/linkml/linkml/discussions/144

often we want to suppress generation of induced slots `Class__Slot`, e.g.

 - in markdown
 - in OWL

These are already effectively suppressed in PythonGen, JsonSchemaGen, etc

some projects such as CCDH rely on having separate induced slots in the markdown, since they may be reusing slot names with vastly different semantics. However, in other cases e.g. mixs, we just want to use slot_usage to provide some minimal adornment onto a standard slot. Also when using `attributes` as a shorthand convenience we don't want to see these.

To satisfy all I would like to make this a switch. I propose the default is expand_slots=False, but this would require us in CCDH to be careful about adding this switch when the new implementing version is released

**Comment by sujaypatil96** [comment]
In the markdown pages we show all slots (direct and induced) by default and separate them out in different blocks.

Is this a useful option to add to the OWL generator still?
