### ISSUE TITLE
jsonschemagen should use tree_root to determine top_class

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#393]
if top-class not specified on CLI, use tree_root property to determine roo

**Comment by sujaypatil96** [comment]
Do we need to write a handler wrapping [line 51](https://github.com/linkml/linkml/blob/main/linkml/generators/jsonschemagen.py#L51)? I'm guessing it's **not** as simple as:

```python
self.topCls = top_class if top_class else self.tree_root
```

If not, how would be construct the logic to determine what the value of `self.topCls` should be?

**Comment by cmungall** [comment]
I think it is that simple! Let's try it!

**Comment by sujaypatil96** [comment]
Is this what we want: https://github.com/linkml/linkml/blob/spatil/jsonschemagen-tree-root/linkml/generators/jsonschemagen.py#L174-L176?

I tried logging the output of `cls.tree_root` on a couple of example schemas, `personinfo.yaml` and `mixs.yaml` but the output was `None` on all occasions.
