### ISSUE TITLE
Emit separate prefixes

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#4]
Need to emit 3 prefixes formats:

- json
- yaml
- context.jsonld  (separate file)

See: https://github.com/biolink/biolink-model/issues/397

**Comment by cmungall** [comment]
Mostly done, prefixmapgen just needs an option for yaml

**Comment by cmungall** [comment]
Should we deprecate prefixmapgen? It is redundant with jsonldgen with the following options:

 * `--flatprefixes`
 * `--no-model`

But we also need to better document the options on jsonldgen

**Comment by sierra-moxon** [comment]
closing as complete. please reopen if I made a mistake here, but we have all the prefixmap formats we need in Biolink as far as I know.
