### ISSUE TITLE
Question on range of subproperty_of

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#41]
The range of subproperty_of is currently uriorcurie, meaning that it may or may not reference a slot definition.  It appears that some of the biolink-model and markdown code expects it to always reference a slot definition.  Should we tighten this definition so that subproperty_of always references a slot?

See: subproperty_of: develops from in biolink-model for example of a non-reference

**Comment by nlharris** [comment]
sounds like this might be straightforward to fix; unassigning chris.

**Comment by nlharris** [comment]
or is this even a fix? if it's just an answer to a question, can it be closed?

**Comment by sierra-moxon** [comment]
Closing as done.
