### ISSUE TITLE
Use imports to merge LinkML files with shared classes to obtain union of slots

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#417]
See also #416 

I would like to import several LinkML files into a root file, including the option of mentioning different slots on a shared class across at least two of the files, so that the import gets the union of slots on that class.

It's not working in this minimal [repo](https://github.com/turbomam/inherit_slots_linkml_import):

> ValueError: Conflicting URIs (https://example.com/c, https://example.com/b) for item: classb

`a.yaml` is the root. `c.yaml` asserts an additional slot on class b from `b.yaml`.

**Comment by sierra-moxon** [comment]
@turbomam - this feels like an unexpected behavior, can you give us a specific example of how this would be relevant to a project?  

We don't usually put one half of a class definition in one yaml file and the other in another yaml file, but if you have a specific example, we can try to work on this? 

from @kevinschaper - this could be a "profile issue".  Denormalized slots need to be added to a core class and I want to add them on, without subclassing (though subclassing might work - we are not sure if using the same name for a subclass would work, or 'mygene' is a subclass of 'gene' and add an alias of 'gene' to 'mygene').

**Comment by sadnanalmanir** [comment]
I have encountered a similar ValueError: Conflicting URIs while importing schemas. Is there any condition on the 'slot' to avoid such an error?

**Comment by turbomam** [comment]
@sierra I agree that I my attempt to define parts of classes in separate YAML files is not supported by LinkML and I am happy to close this issue.

@sadnanalmanir if you can show me your work (eg a GitHub repo) then I might be able to help you.

**Comment by nlharris** [comment]
@kevinschaper @turbomam This turns out to be a blocker for Bridge2AI. @cmungall requested it to be prioritized.

@sadnanalmanir please see @turbomam's request for information so that he can investigate. Thanks!

**Comment by caufieldjh** [comment]
Is this issue still open? See also #1272
