### ISSUE TITLE
How can I find all classes with no mixins?

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#418]
I am currently using brute force with the schema view:

```Python
all_classes = schema.all_classes()
all_classes = list(all_classes.keys())

mixers = []
for i in all_classes:
    print(i)
    checkee = all_classes.get_class(i)
    mixers = mixers + checkee.mixins

mixers = list(set(mixers))

unmixed = list(set(all_classes) - set(mixers))
```

**Comment by cmungall** [comment]
This should work:

`[c for c in view.all_classes().values() if not c.mixin]`

Only classes declared with linkml:mixin should be the range of a linkml:mixins

`[c for c in view.all_classes().values() if not c.mixin]`

**Comment by sierra-moxon** [comment]
I am going to close this as "done" following Chris's example.  Please of course reopen if necessary.
