### ISSUE TITLE
execute_tutorial code sometimes flags false positives when diffing rdf

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#427]
execute_tutorial.py will execute the markdown tutorial files in the sphinx folder, running all examples, and comparing outputs.

RDF diffing should be used when comparing the outputs of commands like linkml-convert when used with `-t rdf` as the order of triples serialized is non-deterministc

**Comment by sierra-moxon** [comment]
I believe this is done.  Please reopen if I am mistaken :)
