### ISSUE TITLE
retroactively black format linkml codebase

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#430]
**Is your feature request related to a problem? Please describe.**
Run the [black](https://black.readthedocs.io/en/stable/) code formatter to retroactively format the codebase per black [standards](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html).

**Describe the solution you'd like**
Run the following command from outside the `linkml` folder on the entire codebase:

```
black linkml
```

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by hrshdhgd** [comment]
I was just about to create a new ticket for this asking for black formatting for autogenerated files. This is def a nice-to-have rather than a must-have but all projects developed by `linkml-ws new` will benefit from it and we won't see red squiggles in the `*.py` file generated.

**Comment by hrshdhgd** [comment]
> How will this work with autogen'd code, e.g. linkml-model in linkml-runtime?

If `black` is implemented within `tox` and is in the gh-action workflow, it'll flag the code while doing a lint check. See [sssom-py](https://github.com/mapping-commons/sssom-py/blob/1d3c3c2a2355da54bc2e68b19969d6322202b764/.github/workflows/qc.yml#L31) implementation. It does a flake8 check but it also flags code that may not be `black` formatted.

**Comment by cmungall** [comment]
It seems simplest to just add a make target to reformat as Sujay suggests?

or should this be an option on gen-python?

**Comment by hrshdhgd** [comment]
I think in an effort to start simple, just limiting it to `gen-python` makes sense.

**Comment by sujaypatil96** [comment]
Issue probably resolved by PR #902
