### ISSUE TITLE
when assert top-class in CLI, JSON schema should include required, description properties from that class

### ISSUE THREAD

**Issue by smrgeoinfo** [linkml/linkml#433]
**Describe the bug**
building JSON schema from YAML, I what to define the root class so the structure is 
{...
"title":"Name of the root class",
"description":"...",
"type":"object",
"properties":"slots on the root class",
"additionalProperties":"....",
"required": "required properties on root class",
"definitions": "object containing defintions of other classes used in model"
}

when I generate the JSON schema, only the "properties" for the root class get placed in root", not the required, and the definition of the class stays in the $def section, where it is superflous.

I'm validating using Oxygen, and its JSON validator doesn't recognize $def as valid key. 

Also with the attached schema, for some reason, 'producedBy' property is implemented as string, not "SamplingEvent" as datatype.

Here's the build command I'm using
gen-json-schema -t  PhysicalSampleRecord  --not-closed  iSamplesSchemaBasic0.3.yml  >  iSamplesSchemaBasic0.3.json

yml file attached, and my manually modified JSON schema the way I expect the output (in zip archive)
[iSamplesSchemaBasic0.3.zip](https://github.com/linkml/linkml/files/7401795/iSamplesSchemaBasic0.3.zip)

**Comment by cmungall** [comment]
Thanks, I am assigning @sujaypatil96 (for some reason github isn't allowing me to assign right now)

Let's scope the work of this ticket to include `required` in the top level properties

i.e. this
```json
 "required": [
            "id",
            "sampleidentifier",
            "label"
         ],
```

should appear in the top level properties at the bottom of the file

Regarding some other points

 - you are right that when top-class is specified there is a somewhat superfluous PhysicalSampleRecord retained under `$defs`. There may be some reasons to keep this -- e.g. reusing the same json schema to describe a list of physical samples. However, we should perhaps have an option `--include-root-as-def` (no idea what a good short name would be)
 - it sounds like Oxygen is using a very old version of the json-schema spec. What version of Oxygen are you using? We could perhaps introduce an option that allows serializing to older json-schema specs

unrelated/minor/unsolicited advice, I am sure you have all these in hand

 - sampleidentifier -> sampleIdentifier?
 - the range of sampleidentifier is string, but the docs says it is a URI. In my experience people put all kinds of junk in the id column, and those not coming from a linked data background may be confused by the use of URLs for identifiers
      - consider linking to separate documentation about iSample IDs
      - consider either a slot_usage `pattern`, OR define a new type such as `Identifier`, and document it there, and put a `pattern` there
 - consider using either semver or ISO-8601 for versions
 - GeospatialDDCoordLocation - what about martian samples?

**Comment by cmungall** [comment]
> 'producedBy' property is implemented as string, not "SamplingEvent" as datatype.

This is because by default references to classes with identifiers are not inlined, so the assumption is the json will be

```json
{producedBy: "EVENT:001", ...
```

not 

```json
{producedBy: {
   id: "EVENT:001", ...
   }
   ...
```

If you want the latter behavior, declare as `inlined`

See https://linkml.io/linkml/schemas/inlining.html

@sujaypatil96 we should add a FAQ entry about this
