### ISSUE TITLE
Linkml Tutorial Part 3 error

### ISSUE THREAD

**Issue by hrshdhgd** [linkml/linkml#442]
**Describe the bug**
I was going through [Part 3 of the linkml tutorial](https://linkml.io/linkml/intro/tutorial03.html#using-the-json-schema-directly) and on running:

`jsonschema -i bad-data.yaml personinfo.schema.json`

I get the error:
```
Failed to parse 'bad_data.yaml': Expecting value: line 1 column 1 (char 0)
```

I double checked the files and they match the ones in the [repository](https://github.com/linkml/linkml/tree/main/examples/tutorial/tutorial03).

**Comment by hrshdhgd** [comment]
It seems like the correct way of running `jsonschema` would be:
`jsonschema personinfo.schema.json -i data.json`. if this is run with an extra `-o pretty` , it gives 
```
===[SUCCESS]===(data.json)===
```

**Comment by cmungall** [comment]
yes. for the purposes of the tutorial we could link to e.g https://www.json2yaml.com/

**Comment by hrshdhgd** [comment]
#565 took care of this
