### ISSUE TITLE
Model Versioning

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#45]
We need to versioning support models generated via biolinkml.  The language supports a version identifier but, at the moment, there is no way to reference anything but the latest version of a given model via  [perma-id](https://github.com/perma-id/w3id.org).

It shouldn't be difficult to add a version to the w3id path, but we still need to:
a) determine how a version in a path resolves to the equivalent source in github
b) determine how to identify the "latest" version and dynamically map it to the appropriate path

**Comment by nlharris** [comment]
Is this still relevant?

**Comment by hsolbrig** [comment]
Yes - very much so.  This is a non-trivial task, but I think we need to make it front and center.  I believe that there is a poetry add-on that helps with this, but I don't recollect what it is off the top of my head

**Comment by nlharris** [comment]
Maybe @sujaypatil96 knows?

**Comment by dalito** [comment]
Added to linkML (not the model) here https://github.com/linkml/linkml/pull/1048 - The plugin is https://github.com/mtkennerly/poetry-dynamic-versioning

**Comment by cmungall** [comment]
This is done
