### ISSUE TITLE
Help wanted: Review FAQ

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#452]
https://linkml.io/linkml/faq/index.html

Document any gaps, mistakes, things that could be made clearer here. Or things you know now that you wish someone had explained before.

Make comments here in this issue; or go ahead and make PRs:

https://github.com/linkml/linkml/tree/main/sphinx/faq

**Comment by sierra-moxon** [comment]
I am going to close this as done; we do add more things to the FAQ regularly, and I've been through it since this ticket was opened and added the things that users have asked of me already.
