### ISSUE TITLE
Consider removing `linkml/generators/namespacegen.py`

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#454]
**Describe the bug**
We're not sure what the usefulness of `namespacegen.py` is so we should consider removing it.

**To Reproduce**
See this [file](https://github.com/linkml/linkml/blob/main/linkml/generators/namespacegen.py).

**Comment by sierra-moxon** [comment]
@sujaypatil96 - I see references to this code in the repo - can you take this on and resolve if necessary?

**Comment by sierra-moxon** [comment]
I'm going to close this bug after talking with Harold, we still use this code and Harold has some ideas to expand it. Please of course reopen if I am mistaken.
