### ISSUE TITLE
FAQ entry for adding slots to annotate slots

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#462]
May require modification of [LinkML meta model](https://github.com/linkml/linkml-model/tree/main/linkml_model/model/schema).

Use LinkML [annotations](https://linkml.io/linkml-model/docs/Annotation/) instead?

See also #452

**Comment by sierra-moxon** [comment]
Hi @turbomam  - can we close this one?  (I'll do that, but please reopen if I am mistaken -- I can show you how I do annotations in biolink, but I think I remember you helping with this before!)

**Comment by turbomam** [comment]
Yeah, I am using annotations now. Thanks.
