### ISSUE TITLE
Switch from pipenv to poetry

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#465]
* should be done across all main repos
     - linkml, runtime, model
     - don't bother with template for now
 * make sure actions work
 * I suggest making PRs on all 3 repos first, checking they work, then merge en masse
 * Ensure we have any necessary instructions in CONTRIBUTING.md for main IDEs

**Comment by sujaypatil96** [comment]
Start with transition to poetry with the linkml-runtime repo.

**Comment by sujaypatil96** [comment]
Reopening this issue since we are yet to _poetrify_ the core linkml repo.
