### ISSUE TITLE
Generate a subset of classes/slots in JSONSchema from a larger, more complex schema.

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#466]
We want to be able to output a subset of classes and slots in JSONSchema artifacts for use in ingesting data in bulk (without maintaining a hand-written JSONschema separate from our LinkML model)

A transformer script that would allow the user to specify an 'inclusion' (or 'exclusion') class and slot file.  Using that list, a derived yaml file could then be used to produce downstream artifacts.  

• Medium - can do work without it, but it's important 
• Medium-term 

Some considerations:
- for the first pass, if a class or slot is in the 'exclusion' list, then it is excluded.  pay no attention to the 'required' status of the slot, for example.  
-  if a class is excluded that is in the middle of a hierarchy where the child (and or grandparent) is meant to be included, simply exclude the class anyway (perhaps generate a warning for the user).
- sometimes we might want the definition of the slot to be inlined or not inlined depending on the artifact.  ie: for Java/python classes we would want inlined slots to enforce class hierarchy on update/insert.  for JSON schema, we might want slots not-inlined so that we don't have to submit entire classes and instead just curies that will be validated as objects later in the ETL pipeline.  (perhaps this can be done with click options on the generator that we can specify in our Makefiles when generating artifacts, vs. some more complicated solution as a first pass). 

This is for Alliance (need subsets of agr_curation_schema that we'll use for validating data to ingest) and Monarch (subsets of biolink-model to build classes).

**Comment by turbomam** [comment]
I'm working on something slightly related and @cmungall told me about this idea of yours.

My [get_dependencies.py](https://github.com/turbomam/linkml-round-trips/blob/main/linkml_round_trips/get_dependencies.py) script can extract one or more classes and/or slots and all of their dependencies. Sorry, there's no documentation yet and there's certainly a lot of grievous sw dev practices in there. 

So far I only have inclusion rules, not exclusion. And I'm only outputting a SchemaDefinition object or YAML. I don't have any direct support for JSONSchema yet.

There's a wrapper script and [Makefile](https://github.com/turbomam/linkml-round-trips/blob/030fbc3652745bedb3a0ef2dfd8b0d9d5514d6cf/Makefile#L50-L57) entry that illustrates getting just the soil class from the MIxS schema. The filesystem location of the MIxS schema is hardcoded into the Makefile rule, but I think you'll get the idea.

Internally, `get_dependencies.py` takes a dictionary of sets as the input. It also expects some global variables... I haven't refactored that yet. The dict below says to make a new schema based on the soil class.

```python
    class_slot_dict = {
        "pending_ranges": set("soil"),
        "pending_slots": set(),
        "exhausted_ranges": set(),
        "exhausted_slots": set(),
        "exhausted_enums": set(),
        "exhausted_types": set(),
    }
```
