### ISSUE TITLE
Switch from rdflib-jsonld to pyld

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#47]
rdflib-jsonld isn't planning to move to json-ld 1.1 anytime soon.  We need to replace the functionality it supplies in biolink w/ https://github.com/digitalbazaar/pyld -- a simple example of its use can be found at https://github.com/hsolbrig/stupid_jsonld_tricks/blob/master/src/gostaysitv2.py

**Comment by cmungall** [comment]
I don't think we want to do this - we want to just use rdflib6?

**Comment by hsolbrig** [comment]
It is my understanding that the latest version of rdflib (6.2.0) has an enhanced version of json-ld built in, with reasonable 1.1 capabilities.  A good and important project - we should consider adding it to an upcoming milestone

**Comment by cmungall** [comment]
pyld is seems to be abandoned. We should use rdflib for anything involving jsonld
