### ISSUE TITLE
consider publishing yaml alongside python in pypi package

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#475]
See https://kiwidamien.github.io/making-a-python-package-vi-including-data-files.html#:~:text=Place%20the%20files%20that%20you,.%5D%7D%20in%20setup.py%20.

if we include the yaml alongside the python package we can have easy introspection methods that use schemaview without any need to coordinate passing of an extra file

e.g

```
from my_model.schema import schemapath
sv = SchemaView(schemapath)
```

**Comment by wdduncan** [comment]
FWIW, I am doing this with the [nmdc-schema](https://github.com/microbiomedata/nmdc-schema).  See [nmdc_data.py](https://github.com/microbiomedata/nmdc-schema/blob/main/util/nmdc_data.py).

Also, see issue raised in #481 

I also included a command line util for retrieving data:
```bash
nmdc-data -h            
Usage: nmdc-data [OPTIONS]

Options:
  -f, --fetch TEXT  Fetches the specified data file from the nmdc-schema library.
                    Only one argument is permitted.
                    
                    fetch arguments:
                    yaml            returns the nmdc.yaml file as a string
                    jsonschema      returns the NMDC jsonschema as json
                    dict            returns the NMDC jsonschema as a dict
                    schemadef       returns the LinkML SchemaDefintion created from the nmdc.yaml file
                    filetypeenums   returns informaton about the NMDC file type enums as json
                    goldsssom       returns the gold-to-mixs.sssom.tsv file contents

  -h, --help        Show this message and exit.
```
Maybe this is gernalizable?
