### ISSUE TITLE
MappingSet.empty() initializes 'mappings' as a dict instead of a list

### ISSUE THREAD

**Issue by hrshdhgd** [linkml/linkml#477]
**Describe the bug**

When an empty MappingSet object is initialized for e.g.: `test =  MappingSet(mapping_set_id = "x", license = "v")` the resultant `test` object looks like this: 

```
MappingSet
  (
    mapping_set_id='x', 
    license='v', 
    mappings={}, # ***Should be empty list ****
    mapping_set_version=None, mapping_set_source=[], mapping_set_description=None, 
    creator_id=[], creator_label=[], subject_source=None, subject_source_version=None, 
    object_source=None, object_source_version=None, mapping_provider=None, 
    mapping_tool=None, mapping_date=None, subject_match_field=[], 
    object_match_field=[], subject_preprocessing=[], object_preprocessing=[], 
    match_term_type=None, see_also=[], other=None, comment=None
)
```

The 'mappings' initialization in the `MappingSet` class is as follows:

```
mappings: Optional[
        Union[Union[dict, "Mapping"], List[Union[dict, "Mapping"]]]
    ] = empty_list()
```

So an empty list is expected but in the example above , we see that the `mappings` object is an empty dictionary.

**To Reproduce**

Mentioned above.

**Expected behavior**
mappings = Empty List

**Comment by cmungall** [comment]
Does this help? https://linkml.io/linkml/schemas/inlining.html

**Comment by cmungall** [comment]
The quick fix for Harshad is to explicitly declare inlined_as_list in sssom.yaml

However, this shouldn't be necessary - it should have been auto-inferred that `mappings` was inlined_as_list, because there is no identifier declared for mappings

instead the code for MappingSet is:

```python
    mappings: Optional[Union[Union[dict, "Mapping"], List[Union[dict, "Mapping"]]]] = empty_list()

    ...

    def __post_init__(...
        ...

        self._normalize_inlined_as_dict(slot_name="mappings", slot_type=Mapping, key_name="subject_id", keyed=False)

```

oddly, it correctly assumes dict when generating the default (list), but for post_init it inlines as a dict

**Comment by hrshdhgd** [comment]
@cmungall : I tried the temporary fix of adding `inlined_as_list: true` within the `sssom.yaml` file and it did not seem to change anything. The error still persists. 

I also made the change in the `sssom` project and ran the pythonGenerator using:

`pipenv run gen-py-classes model/schema/sssom.yaml > sssom/sssom.py`

the resultant `sssom.py` file was no different.

**Comment by hrshdhgd** [comment]
The mistake was on my side. I use Anaconda for my virtual environment and when we ran `pipenv run which python`, it pointed to the python within conda rather than pipenv. I uninstalled pipenv within conda and reinstalled it to give me the result of `pipenv run which python` gave me `.local/share/virtualenvs/sssom-EA4zaZRB/bin/python`

Another mistake I had done previously was changed the `sssom/sssom/model/schema/ssssom.yaml` file instead of the `sssom/model/schema/ssssom.yaml`. The former is copied from the latter during the `make` process. I first ran `pipenv run make squeaky-clean` and then ran `pipenv run make all` and that yielded the desired result.

The `sssom.py` file showed a change in the following line:

**Before**
`self._normalize_inlined_as_dict(slot_name="mappings", slot_type=Mapping, key_name="subject_id", keyed=False)`

**After**
`self._normalize_inlined_as_list(slot_name="mappings", slot_type=Mapping, key_name="subject_id", keyed=False)`

This should take care of the issue in sssom-py.

**Comment by hrshdhgd** [comment]
Solution is [this PR](https://github.com/mapping-commons/sssom/pull/109)
