### ISSUE TITLE
find classes by their class_name

### ISSUE THREAD

**Issue by wdduncan** [linkml/linkml#478]
It is useful to be able to find the name of the class according to how it named in the code.

For example, in the [nmdc-schema python class](https://github.com/microbiomedata/nmdc-schema/blob/main/python/nmdc.py) , there is a class named `BiosampleProcessing`. But, if you run `list(view.all_class())`, you can only get back `biosample processing`.

cc @cmungall

**Comment by cmungall** [comment]
I think this is fixed by https://github.com/linkml/linkml-runtime/pull/77 can you confirm @wdduncan

**Comment by cmungall** [comment]
can you also edit the title of the issue to reflect what the ask is?

**Comment by wdduncan** [comment]
@cmungall renamed the title, but this issue looks to be stale. Perhaps best to close.

**Comment by sierra-moxon** [comment]
we also have the "uncamelcase" method in the runtime too, so we can go back and forth between class name representations in downstream code.  was the ask here that these methods be abstracted away and all versions of the names returned as a tuple?  If so, we don't have that.  I can close for now with the notion that code is available for downstream applications to go back and forth between naming conventions before/after calling the all_classes method?

**Comment by wdduncan** [comment]
@sierra-moxon Thanks for closing. I opened the ticket quite a while ago, and I don't remember the specific use case :(
