### ISSUE TITLE
suppress imports closure when loading schema into schemaview

### ISSUE THREAD

**Issue by wdduncan** [linkml/linkml#481]
In the NMDC, I am packaging the linkml yaml with the [nmdc-schema pypi package](https://pypi.org/project/nmdc-schema/). I have a general util to pull out data from the package (see [nmdc_data.py](https://github.com/microbiomedata/nmdc-schema/blob/main/util/nmdc_data.py)). E.g.:
```python
nmdc_yaml = get_nmdc_yaml_string()
```
or from the cli:
```bash
nmdc-data --fetch yaml
```
However, I am not able to load `SchemaView` using the yaml (string) returned by the util. E.g.:
```python
schema = get_nmdc_yaml_string()
view = SchemaView(schema)
list(view.all_classes())
```
raises error
```python
ValueError: unknown url type: 'external_identifiers.yaml'
```
`external_identifiers.yaml` is one of the imports in `nmdc.yaml`.  

**Note:** I can access the github repo without errors. For example this works as expected:
```python
schema = "https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc.yaml"
view = SchemaView(schema)
list(view.all_classes())
```
However, wouldn't it be better to be able to access the schema from the pypi package?  
Can add a flag to the `SchemaView` constructor not to load the imports?

cc @cmungall @sierra-moxon @turbomam

**Comment by cmungall** [comment]
The quick fix is to distribute the merged yaml with the python. Use `gen-yaml` for this

But it would still be nice to distribute in a modular fashion. But I am not sure we should suppress imports. Is this really what we you want @wdduncan? Would it not be preferable for imports to just work?

What you are describing seems like a bug. Can you describe more what your directory layout looks like?

**Comment by wdduncan** [comment]
Yes. I suppose I can create a merged file :) I was thinking it may be useful to have functionality to access individual files. But, maybe not ...

Right now I get around this by accessing the SchemaDefinition (see [get_nmdc_schema_definition](https://github.com/microbiomedata/nmdc-schema/blob/8a528782313d667ff2261bcd61197478a6bdab40/util/nmdc_data.py#L117)), which is implemented like so:
```python
schema = get_nmdc_schema_definition()
file_enums = schema.enums["file type enum"].permissible_values
```
All the yaml files are in the same directory (see [nmdc-schema/src/schema](https://github.com/microbiomedata/nmdc-schema/tree/main/src/schema))
![image](https://user-images.githubusercontent.com/3186638/143090749-c635bdab-c28e-480f-b020-1395f09378fe.png)

**Comment by cmungall** [comment]
OK, I had a look at the code. There is currently no way for relative imports to work because you are passing in a yaml string you parse yourself, losing links to any metadata about file paths, so SchemaView has no idea where to look for the imports

This should work:

`SchemaView(pkg_resources.resource_filename(__name__, 'relative/path/to/nmdc.yaml'))`

**Comment by wdduncan** [comment]
Ah ... yes. That's right! We discussed this in this issue: https://github.com/linkml/linkml-runtime/issues/52

So, I can load the schema using:
```python
SchemaView(os.path.join(os.path.dirname(sys.modules['nmdc_schema'].__file__), 'nmdc.yaml'))
```
In the ticket, we mentioned providing a shortcut to doing this. Something like this:
```python
SchemaView('nmdc.yaml', module='nmdc_schema')
```
Perhaps this would be useful to others?

**Comment by cmungall** [comment]
shall we close this?

**Comment by wdduncan** [comment]
@cmungall Did you decide if you wanted to add a functionality like this:
```python
SchemaView('nmdc.yaml', module='nmdc_schema')
```
as a shortcut for doing this:
```python
SchemaView(os.path.join(os.path.dirname(sys.modules['nmdc_schema'].__file__), 'nmdc.yaml'))
```
For cases in which you need to access files within the module?

**Comment by cmungall** [comment]
Indeed, and you can in fact do this now. You need to pass in the full python path to the module, e.g. `nmdc_schema.nmdc`
See https://github.com/linkml/linkml-runtime/pull/100

Example code:

https://github.com/linkml/linkml-runtime/blob/8d22a12dc1a2fd6e3d5a719e586ba87ae3847653/tests/test_utils/test_introspection.py#L6-12
