### ISSUE TITLE
Improve FAQ entry and docs on is_a vs mixins

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#482]
[brief notes from call]

We currently have:

 * https://linkml.io/linkml/faq/modeling.html#what-is-the-difference-between-is-a-and-mixins
 * https://linkml.io/linkml/schemas/inheritance.html

But these don't fully answer @pnrobinson's question from the SchemaView discussion today - why does linkml have this mechanism at all

It may be that we want to give different answers for different communities

For those coming from ontologies, polyhierarchies are the norm. In fact I even wrote a blog post https://douroucouli.wordpress.com/2019/05/10/ontotip-single-inheritance-principle-considered-dangerous/ which may seem at odds with linkml design

in fact a key formal distinction here is between the open world assumption (OWA) and CWA. OWL follows OWA, which necessitates **monotonicity** - i.e no overrides. There is a formal answer to the https://en.wikipedia.org/wiki/Nixon_diamond problem - OWL would yield an inconsistency.

With a CWA you can have overrides / non-monotonicity, but there should be clear rules about precedence/overrides. LinkML allows overrides via mixins, but this needs to be better documented

@sierra-moxon also had suggestions on the call

**Comment by sierra-moxon** [comment]
https://linkml.io/linkml/faq/modeling.html#what-is-the-difference-between-is-a-and-mixins closing! :)
