### ISSUE TITLE
Add a "how to cite" link to FAQ

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#493]
For now do we request

 - CFF #491
 - Zenodo #492. 

Hopefully we will have a arxiv paper soon

**Comment by turbomam** [comment]
Were you thinking that I would just compose a CITATION.cff by hand, or that I would write something to derive it from the repo contents? For keeping the version and release date current, etc.

**Comment by turbomam** [comment]
I see that https://github.com/linkml/linkml/blob/main/CITATION.cff already exists. Is this issue really just a matter of putting a link to `CITATION.cff` at https://linkml.io/linkml/faq/general.html#how-do-i-cite-linkml

I don't know where to edit the FAQ. Somewhere in https://github.com/linkml/linkml.github.io ?

**Comment by nlharris** [comment]
The FAQ seems to be in https://github.com/linkml/linkml/tree/main/docs/faqMoxon S, Solbrig H, Unni D, Jiao D, Bruskiewich R, Balhoff J, Vaidya G, Duncan W, Hegde H, Miller M, Brush M, Harris N, Haendel M, Mungall C. The linked data modeling language (LinkML): A general-purpose data modeling framework grounded in machine-readable semantics. 2021 International Conference on Biomedical Ontologies, ICBO 2021. CEUR-WS; 2021. p. 148–151. https://jhu.pure.elsevier.com/en/publications/the-linked-data-modeling-language-linkml-a-general-purpose-data-m

**Comment by sierra-moxon** [comment]
closing as complete.
