### ISSUE TITLE
Add a type to types.yaml that is the union of datetime and date

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#495]
Use case: we want to allow capturing dates where providers can optionally include a time component

We can use datetime, but this gives false precision where no time specified:

```python
>>> t=XSDDateTime('2021-01-01')
>>> t
'2021-01-01T00:00:00'
```

**Comment by cmungall** [comment]
Alternative: use a separate precision field

TODO: record FHIR/RDF experiences here @hsolbrig has experience here

Also of note on precision: in FHIR `6.00 != 6.0` they represent precision lexically (!!)

TODO: link to w3c thread

**Comment by cmungall** [comment]
https://github.com/linkml/linkml/issues/496
https://github.com/w3c/hcls-fhir-rdf/issues/92

**Comment by sierra-moxon** [comment]
I am closing as complete: https://github.com/linkml/linkml-model/blob/3b2a0b8bd072ff66308357cd07da3b6fcaee010e/linkml_model/model/schema/types.yaml#L101 

reopen if necessary :)
