### ISSUE TITLE
Fix and re-adjust YAMLRoot and TypedNode references

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#5]
Some bridge code has been added to help assert the equivalence of YAMLRoot and TypedNode whether it comes from the biolinkml or the linkml package.  This needs to be removed and re-tested once we finish the LinkML migration.

Code can be found in:
yamlutils.py
test_schemaloader.py
jsonldgenerator.py
schemagenerator.py

**Comment by sierra-moxon** [comment]
I believe this is done; closing as complete.
