### ISSUE TITLE
Prefixes section doesn't support CURIES

### ISSUE THREAD

**Issue by jiaola** [linkml/linkml#50]
Prefixes section doesn't support CURIES. When you supply one, you get: File "~/.local/share/virtualenvs/tccm-CoY-QjRv/lib/python3.8/site-packages/biolinkml/utils/metamodelcore.py", line 131, in init Without a line number reference. We should be able to pass identifiers and the line number generator should be smart enough to know whether it has them or not

**Comment by cmungall** [comment]
@hsolbrig is this still an issue? I am not sure I have enough context here to understand the problem

**Comment by hsolbrig** [comment]
Gotta say, I'm not sure that I understand this either.  Closing
