### ISSUE TITLE
Add a utility to validate and transform all registered example or data files in a repo

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#501]
Best practice for a schema repo is to always

 - have a folder of example files
 - provide links to these files for humans, so they can use the examples to help understand the schema
 - validate all example files against the schema to guard against examples getting out of sync with schema and increase overall robustness
 - translate the examples into different formats, e.g
     - if source examples are yaml, also provide json, json-ld, and rdf - to elucidate serialization-independence
     - if examples are amenable to a tsv serialization, convert to tsv/excel - also optionally to markdown tables
     - [when available] markdown version
     - [when available] graphical representation
     - A markdown index
 - integrate links between examples embedded in schema and example files    

We provide some tooling for some of this. E.g. when linkml-model-template is used, it will generate a python test file that iterates through a folder checking files

 - https://github.com/linkml/template-config-model/blob/main/tests/test_input_against_model.py
 - https://github.com/linkml/template-config-model/tree/main/tests/input
 - https://github.com/linkml/template-config-model/blob/main/Makefile#L60
 
But this codegen approach is not ideal here. E.g. if the above repo changes, then we lack a mechanism to distribute to all repos that use this. See also experiences with ODK. Better to use a central library.

I propose a click-wrapped module that takes as input

 1. A description in yaml of a collection of files, OR
 2. A folder, which is scanned to infer the above

And produced as output a new folder, with generated downstream files as above, and a new dataset metadata file. Fail fast on validation issues.

This would be run as part of `make test` for the repo and in the repo's actions

This will require some kind of minimal metadata model for describing a set of data files. Minimal information for each file would be:

 * local path (or URL if external, e.g. on s3)
 * format (e.g. yaml)
 * schema

It should be lenient with missing values. The default schema would be the schema that is managed in the repo. The format could be inferred by suffix. And the user should be able to pass in a folder, and standard python scanning is used to find all likely data files (excluding .md etc)

This could form the basis for a dataset/collection schema based on void/hcls/frictionless/csvw etc, see #86 -- however, the first iteration need not have parity

**Comment by sujaypatil96** [comment]
Bring this up at LinkML call and spec. it out in the context of new cookiecutter template.

**Comment by sujaypatil96** [comment]
@sujaypatil96 to work on this once priority has been determined.
