### ISSUE TITLE
linkml shouldn't import pandas

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#506]
**Describe the bug**
Pandas is a huge module and linkml does not need it.  It should not be a dependency.

**Comment by cmungall** [comment]
where are we with this @hrshdhgd ?

**Comment by hrshdhgd** [comment]
I believe this is taken care of ,although there are still `pandas` references in `toml` , `requirements.txt` and `pipfile`s

**Comment by hrshdhgd** [comment]
<img width="293" alt="Screen Shot 2022-05-27 at 1 03 19 PM" src="https://user-images.githubusercontent.com/5247075/170766141-b179fb1b-d483-40e8-b53c-def356ca04ae.png">

**Comment by hrshdhgd** [comment]
[PR](https://github.com/linkml/linkml/pull/804) to remove remnants.
