### ISSUE TITLE
reflect deprecation in the Dataclasses 

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#514]
`SlotDefinition`'s attribute [`owner`](https://linkml.io/linkml-model/docs/owner/) is deprecated within the model. I don't think that's reflected anywhere in the [Dataclass](https://github.com/linkml/linkml-model/blob/ec4bee7c691e2ba5e1b276a95139d1fc77445c38/linkml_model/meta.py#L1069), so I don't get any hint about it in my IDE (PyCharm)

It looks like it is possible to decorate a method as deprecated: https://python-deprecated.readthedocs.io/en/latest/tutorial.html#deprecated-method

**Comment by cmungall** [comment]
Dupe with #484?

**Comment by sujaypatil96** [comment]
Closing this issue as dupe of #484
