### ISSUE TITLE
Use Apache 2.0 instead of CC0

### ISSUE THREAD

**Issue by noelmcloughlin** [linkml/linkml#519]
Could you consider replacing CC0 with Apache 2.0 license to avoid patent concerns.

See also https://github.com/biolink/biolink-model/issues/920

Thanks, I am using linkml in some technology prototying and CC0 is a concern for software use

**Comment by cmungall** [comment]
Thanks @noelmcloughlin - our aim is to limit all possible barriers to linkml usage. We are very open to switching to Apache and are watching the other thread with interest. At what sort of time frame does this become a serious concern for you?

**Comment by noelmcloughlin** [comment]
@cmungall its not a concern at the moment, but I wanted to follow up as I proposed using LinkML in FINOS (https://github.com/finos) and I CC0 would certainly be a show stopper (in my experience).

**Comment by nlharris** [comment]
Flagging @kltm to see if he has an opinion.

**Comment by kltm** [comment]
I'd want to have more context if this is important, but CC0 is a public domain dedication tool/declaration and Apache 2.0 is a modern software license with specific patent-related language, liability limitations, disclaimer of warranty, etc. Pretty different things...
I'd think for most software one would choose between BSD 3-clause and Apache 2.0; the latter if one was concerned about having more protection WRT patents.

**Comment by nlharris** [comment]
Looks like this was fixed by #1754
