### ISSUE TITLE
Mismatch between the model and the generated JSON Schema

### ISSUE THREAD

**Issue by hongcui** [linkml/linkml#543]
This issue seems to be similar to #27 

Yaml:
[iSamplesSchemaBasic0.3.yaml.txt](https://github.com/linkml/linkml/files/7763989/iSamplesSchemaBasic0.3.yaml.txt)

Run:
```
gen-json-schema -t PhysicalSampleRecord --not-closed iSamplesSchemaBasic0.3.yaml
```

Output contains
```
 "producedBy": {
         "description": "object that documents the sampling event--who, where, when the specimen was obtained",
         "type": "string"
      }
``` 

but the type should be an object, like:

```
 "producedBy": {
         "description": "object that documents the sampling event--who, where, when the specimen was obtained",
         "$ref": "#/$defs/SamplingEvent"
      },
```

**Comment by cmungall** [comment]
By default reference by ID is assumed - if you want to inline the object
set inlined: true

Aside: I would strongly advise against exposing jsonld style keywords with
@s  at the schema level. Map these to idiomatic terms in a context file.I
will try and make a start on a jsonld guide today

**Comment by sierra-moxon** [comment]
@hongcui - from my interpretation of this ticket and @cmungall's answer, we can close this as completed?  If not, or if the resulting documentation or solution was not clear, please do feel free to reopen this ticket.  :)
