### ISSUE TITLE
Make release candidates for 1.2 series: Drop support for rdflib5

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#545]
In preparation for a 1.2 series, we should create pre-releases in github and pypi.

Even though the individual pypi release do not need to share patch versions we should sync on major and minor, so we would start with:

 * linkml-model-1.2.0rc1
 * linkml-runtime-1.2.0rc1
 * linkml-1.2.0rc1

We would have branches named `rc-1_2_0` on all three repos, and create github pre-releases from these branches, and pypi release candidate releases from these.

This will allow users to test against the release candidate, but they would have to do this explicitly, either by requesting a rc in their requirements.txt/Pipfile/pyproject.toml, *or* by specifying `--pre` when installing.

See:

 * [PEP-0440 pre-releases docs](https://www.python.org/dev/peps/pep-0440/#pre-releases)

I propose that the 1.2.x series drop support for rdflib5. Maintaining dual support for 5/6 via the shim is challenging.

We would also prepare release notes summarizing all changes since 1.1.0 in all projects.

**Comment by dalito** [comment]
With rdflib = ">=6.0.1" the requirement `rdflib-jsonld = "==0.6.1"` must be removed because rdf-jsonld was integrated into rdflib.
The PR #545 does not yet have this change.
