### ISSUE TITLE
Allow SchemaView to be instantiated from a python package (assumes yaml distributed alongside python classes)

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#546]
@wdduncan had a great suggestion here:

https://github.com/linkml/linkml-runtime/issues/52#issuecomment-926331669

The basic idea is that provided certain conventions are followed, when a python module is released to pypi, the yaml is also distributed alongside.

For example, for linkml-model itself, any place linkml_runtime is installed there will be a path to the yaml

E.g.

```
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model//__init__.py
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model//types.py
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model//linkml_files.py
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model//extensions.py
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model//annotations.py
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model//mappings.py
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model//meta.py
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/mappings.yaml
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types.yaml
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/extensions.yaml
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/meta.yaml
venv/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/annotations.yaml
```

We can use https://docs.python.org/3/library/pkgutil.html to find the yaml

Example:

```python
sv = SchemaView(pkgutil.get_data('linkml_runtime.linkml_model.meta', os.path.join('model', 'schema', 'meta.yaml')).decode("utf-8"))
```

Will create a SchemaView for the linkml model from any linkml-runtime distribution

The same pattern can be used to fetch the json-schema, the json-ld-contexts, etc

This relies on a convention of using the same relative path, which could be encouraged by projectgen and the model template repo. We could also have a few potential relative paths, and cycle through these.

E.g for nmdc_schema the files are at the same level as the python

```
~/.local/share/virtualenvs/sample-annotator-nWz4Swao/lib/python3.9/site-packages/nmdc_schema/prov.yaml
~/.local/share/virtualenvs/sample-annotator-nWz4Swao/lib/python3.9/site-packages/nmdc_schema/nmdc.yaml
~/.local/share/virtualenvs/sample-annotator-nWz4Swao/lib/python3.9/site-packages/nmdc_schema/nmdc.schema.json
~/.local/share/virtualenvs/sample-annotator-nWz4Swao/lib/python3.9/site-packages/nmdc_schema/core.yaml
~/.local/share/virtualenvs/sample-annotator-nWz4Swao/lib/python3.9/site-packages/nmdc_schema/nmdc.py
````

Example code:

https://github.com/microbiomedata/nmdc-schema/blob/8a528782313d667ff2261bcd61197478a6bdab40/util/nmdc_data.py#L18-L28

Alternatively, it could be argued this will bloat SchemaView, and it should instead be left to client code to form the correct path. Nevertheless some kind of utility library somewhere would be useful, e.g.

```python
def get_packaged_file(package: str, file_type: str, rel_path=None) -> str:
```

**Comment by wdduncan** [comment]
@cmungall sorry for the slow response.  
Did you decide this was not practical?
