### ISSUE TITLE
LinkML Actions repository

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#568]
**Is your feature request related to a problem? Please describe.**
The existing process of adding Actions to our projects, where we have to copy over the actions from the model exemplar linkml-runtime project is more cumbersome than necessary.

**Describe the solution you'd like**
Start a LinkML repository with the intent to create a parameterized Github Action that can be used across LinkML repos. This way we can generalize our Github Actions.

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by cmungall** [comment]
I don't think we will work on this until (a) we have worked out all the kinks in the exemplar repo (b) implemented this for most other repos

**Comment by cmungall** [comment]
@hsolbrig made a start: https://github.com/hsolbrig/actiontest
