### ISSUE TITLE
Add information to all CONTRIBUTING.mds on how to write tests that deal with issues

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#570]
There is a lot of tacit knowledge developers have when handling an issue in one of our repos

 - how to run tests
     - the core is very standard
     - but the test_config.ini  needs documented
 - the organization of the tests into subfolders
 - naming conventions for test python files and accompanying data files
 - best practice (no prints; use logging)

anything else?

**Comment by cmungall** [comment]
@sujaypatil96 I think you were going to do the first PR on this, using the info we put in the google doc?

**Comment by sujaypatil96** [comment]
@cmungall yup, I'll use the content we put into the Google Doc the other day to add the _How to author your first test_ section to the CONTRIBUTING.md doc. I'll get a PR in for this today or tomorrow.

**Comment by sujaypatil96** [comment]
Addressed in PR #585.
