### ISSUE TITLE
gen-project puts a SQL DDL file in the java/ directory

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#571]
will provide test by 2022-01-25

**Comment by turbomam** [comment]
see #700

**Comment by cmungall** [comment]
@sujaypatil96 is this still an issue?

**Comment by sujaypatil96** [comment]
@cmungall gen-project's excel generation feature was fixed in PR #769, but I don't think the Java, SQLDDL generator was fixed. I'll rerun gen-project and look at the artifact it places in the java output directory.

**Comment by sujaypatil96** [comment]
Java artifact generation has been disabled by default in gen-project. To reproduce this issue, uncomment the necessary line in projectgen.py and fix java artifact output.

**Comment by sujaypatil96** [comment]
@julesjacobsen @kevinschaper do either of you want to take this on?

**Comment by sierra-moxon** [comment]
Closing for now, when/if gen-sql needs to move back into gen-project, we can revisit.  gen-sql works fine for me.
