### ISSUE TITLE
Priority on prefixes in imports vs. local

### ISSUE THREAD

**Issue by jiaola** [linkml/linkml#58]

**Comment by nlharris** [comment]
Is this a question? A feature request? Does Harold know what is being asked for here?

**Comment by hsolbrig** [comment]
Not positive what this was about.  When I try the following:

test.yaml:
```id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  ex: https://gridlock.org/
imports:
  - linkml:types
  - stuff

default_range: string

classes:
  Person:
    class_uri: ex:Foo
```
and

stuff.yaml:
```
id: https://w3id.org/linkml/examples/stuff
name: stuff
prefixes:
  ex: https://examples.org/
```
`gen-python test.yaml` yields

`ValueError: Prefix: ex mismatch between personinfo and stuff`

So I'm not really sure what we are getting at here.  Maybe we had some reason that we wanted the "gridlock" prefix to override the imported one?
