### ISSUE TITLE
pip dependency conflict?

### ISSUE THREAD

**Issue by RichardBruskiewich** [linkml/linkml#592]
```
ERROR: Cannot install -r requirements.txt (line 33), -r requirements.txt (line 36), click>=8.0.0 and linkml==1.1.13 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested click>=8.0.0
    black 22.1.0 depends on click>=8.0.0
    linkml 1.1.13 depends on click~=7.0
...
```
KGX pulls in **black** with (`click>=8.0.0)` but also sets `Click~=7.0`. Can **linkml** also rather use click>=8.0.0 ?

Also affects code upstream, like **kgx** (see https://github.com/biolink/kgx/issues/371)

**Comment by dalito** [comment]
The [Pipfile](https://github.com/linkml/linkml/blob/f32b173ff2163b3dd64cacb1c9499ee0a5ca0a76/Pipfile#L7) is not yet updated. It still contains:
```
click = "~=7.0"
```

**Comment by RichardBruskiewich** [comment]
> The [Pipfile](https://github.com/linkml/linkml/blob/f32b173ff2163b3dd64cacb1c9499ee0a5ca0a76/Pipfile#L7) is not yet updated. It still contains:
> 
> ```
> click = "~=7.0"
> ```

Sorry.. my bad. Patched and committed.

**Comment by cmungall** [comment]
can this be closed?
