### ISSUE TITLE
Move generated docs from main branch to gh-pages branch

### ISSUE THREAD

**Issue by dalito** [linkml/linkml#597]
Like the title says (was "Why is the generated html-documentation in the repo?"). It is very rare to see this. I was wondering why you do it.

**Comment by hrshdhgd** [comment]
Hey @dalito!  As far as I understand the html-documentation in the `docs` folder, seem to be the source for GitHub Pages to render the [documentation page](https://linkml.io/linkml/) as per the documentation from [sphinx](https://www.sphinx-doc.org/en/master/tutorial/deploying.html#id1).

**Comment by dalito** [comment]
Thanks. I am more used to keeping all generated stuff out of code-repositories. But with gh-pages you have are bound to use a repo. It could be a different one then the one for code (like Numpy does). Anyway I was just curious - no critics!

**Comment by dalito** [comment]
I read a bit because _there must be a better solution_.

To keep the main branch free from the generated docs, it is suggested to push the generated documentation to a separate branch `gh-pages`. This should be easy to achieve, see

 * [Continuous Documentation: Hosting Read the Docs on GitHub Pages](https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/)
 * [Configuring a publishing source for your GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)

I think it would be nice to keep the main branch clean and small. So reopening the ticket with adjusted title.

**Comment by hrshdhgd** [comment]
Thank you so much for the research @dalito ! We will work towards making this change.
