### ISSUE TITLE
Add favicon to docs

### ISSUE THREAD

**Issue by StroemPhi** [linkml/linkml#600]
**Is your feature request related to a problem? Please describe.**
The docs (https://linkml.io/linkml/) don't have a favicon. At least not on my Win10 machine when using Firefox or Edge. It would be great for me to have a favicon that I can use to distinguish my pinned browser tabs. 
As a novice user of linkML, I frequently consult the docs and thus have them always open as a pinned tab. When workling with other pinned tabs that are e.g. autogenerated docs of my own linkML based schema, then it can become hard to keep the overview.

**Describe the solution you'd like**
Having a favicon in the linkML docs. 

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Long-term - 6 months - 1 year

**Additional context**
![grafik](https://user-images.githubusercontent.com/56996739/153153498-ae2bd9eb-cec2-47f7-837b-5af897e55436.png)

**Comment by Urjaswi-2655** [comment]
@cmungall I learnt to add favicon to a website and will be using following image if you allow me to go through this issue.
 I am not able to find the html file where I will add this favicon too.

**Favicon** : [](https://avatars.githubusercontent.com/u/79337873?v=4)

**Comment by cmungall** [comment]
Hi @Urjaswi-2655!

We use sphinx for the main linkml documentation

It looks like a plugin is required
https://pypi.org/project/sphinx-favicon/

The source for the sphinx is here:
https://github.com/linkml/linkml/tree/main/sphinx

**Comment by Urjaswi-2655** [comment]
@cmungall I will try to learn and implement it as soon as possible, Thanks.

**Comment by nlharris** [comment]
Thanks for volunteering to do this, @Urjaswi-2655!

**Comment by cmungall** [comment]
Hi @Urjaswi-2655 are you still interested in doing this?
