### ISSUE TITLE
Use bioregistry.io for prefixregistry

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#604]
Discussing with @hsolbrig 

Currently default_curi_maps use https://pypi.org/project/curieutil/ which fetches from prefixcommons

we should get prefixes from bioregistry

eg.

```
>>> from bioregistry import get_iri, get_prefix_map
>>> prefix_map = get_prefix_map(priority=["obofoundry"])
>>> prefix_map['pato']
'http://purl.obolibrary.org/obo/PATO_'
>>> get_iri('skos','')
'http://www.w3.org/2004/02/skos/core#'
```

We need bioregistry to have the correct casing first

**Comment by hrshdhgd** [comment]
Related issues: https://github.com/mapping-commons/sssom-py/issues/247

**Comment by sierra-moxon** [comment]
done: https://github.com/linkml/linkml-runtime/pull/231
