### ISSUE TITLE
setup.cfg - includes should be INSIDE biolinkml. (look at how w3id redirects work before you continue)

### ISSUE THREAD

**Issue by jiaola** [linkml/linkml#61]
At  the moment, the "includes" directory is included as part of the pypi distro.  This turns out to result in something that looks like:
```
   lib
        python3.8
              site-packages
                  attr
                  ...
                  **biolinkml**
                  ...
                  **includes**
```
The above works only because we're the only ones that have put `includes` at the root of an install.  This promises to break things in mysterious ways in the not-too-distant future.

**Comment by nlharris** [comment]
so is this fixed?

**Comment by sierra-moxon** [comment]
with poetry, we no longer use setup.cfg
