### ISSUE TITLE
Change tests so that they follow procedure documented in CONTRIBUTING.md

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#613]
Some tests in the linkml repos, specifically ones in [test_issues](https://github.com/linkml/linkml/tree/main/tests/test_issues) do not follow the guidelines detailed in the CONTRIBUTING.md doc, in that are incorrectly named, i.e., without the `test_` prefix in the filenames, which cause them not to be run by the Actions workflows.

**Comment by Urjaswi-2655** [comment]
@sujaypatil96 @krishna-saravan  Only tests which are named with numbers of issue are too be corrected right? If that's the condition then there are only first three tests with wrong name i.e. test no. 163,313 and 315.

**Comment by sujaypatil96** [comment]
@Urjaswi-2655 @krishna-saravan yes, that's right. Test issues 163, 313, and 315 need to be prefixed with the `test_` keyword in the filename, per the guidelines in the [CONTRIBUTING.md](https://github.com/linkml/linkml/blob/main/CONTRIBUTING.md) doc.

Some sanity checks:
* Run the test suite with `python -m unittest discover` to make sure the tests are going through
* You can log some output from these tests to check if they are going through

or

* Run `python -m unittest tests/test_issues/*`
* Check if the number of tests that were executed is equal to the number of tests in the `test_issues` folder

Once you've completed the above steps on a branch, you can submit a PR which we will review and merge. If all looks good, you can apply the same strategy to other linkml repos as well.

To make a PR, I suggest creating a fork of the linkml repo, and working on a branch called `issue-613-fix`.
