### ISSUE TITLE
Every 2nd line empty in csv/tsv output (Windows)

### ISSUE THREAD

**Issue by dalito** [linkml/linkml#622]
**Describe the bug**
When using link-convert to output data as tsv/csv every 2nd line is empty.

**To Reproduce**
1. Running `linkml-convert -t tsv -o examples\tutorial\tutorial02\data_win_bug.tsv -s examples\tutorial\tutorial02\personinfo.yaml examples\tutorial\tutorial02\data.yaml`
2. Gives:
```tsv
id	full_name	phone	age

ORCID:1234	Clark Kent	555-555-5555	32

ORCID:4567	Lois Lane		33


```
![bug](https://user-images.githubusercontent.com/2648874/155816787-b6bd41ed-9dfb-4e5e-9bf3-1ddcff7ad1ed.PNG)

 - OS: Win10-64bit, 
 - Python 3.9.10
 - linkml 1.1.19.dev29, linkml-runtime 1.1.24, json-flattener 0.1.7

**Additional context**
The problem is caused by the json-flattener which does not produce correct line-endings on windows. I'll report the bug here because it is not obvious that the problem is in json-flattener. I'll create a PR in the json-flattener repo.

**Comment by cmungall** [comment]
I'm leaving open til we bump the version in linkml-runtime.. which I think will pass as soon as pypi percolates...
