### ISSUE TITLE
Remove unused dependencies in Pipfile, and move dev packages to dev section

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#630]
I think wtachdog, sphinx, etc are only required for building the docs, so this can be a dev dependency? No need to make people installing linkml also install these

why do we have

argparse = ">=1.4.0"

If we use click everywhere?

**Comment by sierra-moxon** [comment]
closing for now as we have moved dependencies to poetry and pyproject.toml, and we've created a dev-dependencies section in the pyproject.toml . Locally, I removed argparse and am running tests, will put in a PR if all is well with the removal.
