### ISSUE TITLE
Display inherited links in local figures

### ISSUE THREAD

**Issue by wdduncan** [linkml/linkml#64]
When a class has an inferred slot, it is useful to have a link the local figure showing the relationships. For example, in the [NMDC schema](https://microbiomedata.github.io/nmdc-metadata/), The [omics processing](https://microbiomedata.github.io/nmdc-metadata/docs/OmicsProcessing.html) class, has an inherited slot:
``` 
biosample -> has input
Range: biosample
```
![image](https://user-images.githubusercontent.com/3186638/91473368-c7865800-e866-11ea-805a-337d46f6a8ab.png)

However, this link is not explicitly show in the local figure showing an omics processing relationship a biosample.
![image](https://user-images.githubusercontent.com/3186638/91473504-f8668d00-e866-11ea-8775-7126667a6daa.png)

**Comment by cmungall** [comment]
can you confirm this is still an issue @wdduncan ?

**Comment by sierra-moxon** [comment]
@sujaypatil96 - can you check if this is fixed in NMDC schema doc with your recent work on docgen?

**Comment by sierra-moxon** [comment]
From triage with Sujay, we should see also #1116 (this is a ticket about mermaid diagram generation - we'd like to have a brainstorm session to find out the requirements for mermaid generation).

**Comment by sierra-moxon** [comment]
We see the link between OmicsProcessing and Biosample now. :)
