### ISSUE TITLE
Tests are failing due to missing ipython_genutils in nbconvert

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#645]
We are not the only ones to notice:

 - https://github.com/jupyter/nbconvert/issues/1725

**Comment by cmungall** [comment]
See that issue for a temporary fix:

- include the transitive dependency
- exclude 

 - we should pin the version of nbformat to exclude 5.2.0

(I am still a bit confused by this - it looks like

**Comment by sujaypatil96** [comment]
Temporary fix: add `ipython-genutils` as a dev dependency to the Pipfile.

**Comment by sujaypatil96** [comment]
Use the above fix only until the `nbconvert` maintainers have a more permanent fix.

**Comment by cmungall** [comment]
looks like this was fixed upstream?
