### ISSUE TITLE
Empty list entries aren't detected

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#65]
```yaml
   in_subset:
      - abc
      -
```
Isn't detected until late in the process and then only by a mysterious failure.  Need to detect `None` in lists early in the process

**Comment by sierra-moxon** [comment]
Would be helpful to see the error message, and if possible submit a simple test that shows the issue?

**Comment by hsolbrig** [comment]
This turns out to be a real edge case.  If the empty entry isn't followed by a carriage return, the python yaml module misses it and it breaks in another part of the code.  I suppose that this could occur just often enough, however, that we probably need to fix it.

I'm weakly inclined to put a hack in the raw_loader that makes sure there is a carriage return at the end of the file...

I'll issue a PR for the test case and proposed fix.
