### ISSUE TITLE
pyyaml now requires explicit loader argument value

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#656]
We can see PR #647 isn't going through, and the reason for that is because of the `pyyaml` dependency.

See this SO post for reference: https://stackoverflow.com/questions/69564817/typeerror-load-missing-1-required-positional-argument-loader-in-google-col

The problem is in this block of code: `compare_objs()` method in the [dict_comparator.py](https://github.com/linkml/linkml/blob/8ce31715f53396ab885e251b29ee308fd2efde2d/tests/utils/dict_comparator.py#L36-L39) module.

There are two solutions that we can implement to resolve this:

* Use `safe_load()` instead of `load()`
* Add `loader=yaml.Loader` argument to `yaml.load()` call

**Comment by cmungall** [comment]
perhaps two steps:

1. create immediate new releases of runtime and linkml where we pin pyyaml < 5.4
2. change the code using one of the two methods above (I think the first is best)
