### ISSUE TITLE
gen-java creates NO output in the MIxS repository

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#660]
MIxS = https://github.com/GenomicsStandardsConsortium/mixs

will provide test case later

**Comment by turbomam** [comment]
did try with `--mergeimports`. no help.

**Comment by turbomam** [comment]
see also https://github.com/GenomicsStandardsConsortium/mixs/issues/361

**Comment by cmungall** [comment]
@sujaypatil96 can you confirm is this still an issue?

**Comment by sujaypatil96** [comment]
Check if dupe of #969

**Comment by sierra-moxon** [comment]
closing as dupe of #969
