### ISSUE TITLE
gen-linkml or another util should be able to expand structured_patterns

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#674]
FIrst, lets familiarize ourselves with https://github.com/linkml/linkml-model/blob/main/examples/pattern-example.yaml

Maybe use 

edge cases:
- period (.) in constant "settings"'s name
- curly bracket in constant "settings"'s name
- maybe just discourage or reject those cases

```
>>> syntax="{a} {b}"
>>> syntax.format(a='foo', b='bar')
'foo bar'
```

**Comment by ddooley** [comment]
I left a note in PR that lots of systems also have '{foo}{bar} {doh}' spacing variations that we need to account for.  Python's .format(**schema_view.schema.settings) can probably handle this in one line (with try-catch for catching key errors).

**Comment by ddooley** [comment]
For the record, this does a better job if we really want to hang on to dotted names. It messes up a little bit if say both {x=123, x.y=234} is mentioned in settings though.

```

from types import SimpleNamespace

def recurseAttr(namespace, key_string, value): 
    if '.' in key_string:
        (key, remainder) = key_string.split('.',1)
        
        if not key in dir(namespace):
            setattr(namespace, key, SimpleNamespace())
        
        elif str(type(namespace.__dict__[key])) != "<class 'types.SimpleNamespace'>":
            # Issue: this overwrites x=123 ancestor path constant if adding x.y=3456
            setattr(namespace, key, SimpleNamespace(self = namespace.__dict__[key]))

        recurseAttr(namespace.__dict__[key], remainder, value)

    else:
        setattr(namespace, key_string, value)
        
settings = {'foo':1,
'bar':'2', 
'dom':{'test':'that'},
'dom.da': 3, 
'di.domo.da': 4,
'dom.doy': 5, 
'dom.doy.du': 6
}

settings_2 = SimpleNamespace()
for key_string in settings:
    recurseAttr(settings_2, key_string, settings[key_string])

pattern = '{foo}.{bar} {dom.da}{di.domo.da} {dom.self}'.format_map(vars(settings_2))
print(pattern)
```

**Comment by cmungall** [comment]
@sujaypatil96 can you incorporate this? Thanks!

**Comment by ddooley** [comment]
I'm fixated on this because I sense hassles in the future if we don't get it right.  I offer up this, I think its more full proof.

import re

settings = {'foo':1,
'bar':'2', 
'dom':4,
'dom.da': 3, 
'di.domo.da': 4,
'dom.doy': 5, 
'dom.doy.du': 6,
'foo bar': 7,
'complex': {'test':'that'},
'funny': 'joke'
}

var_name = re.compile('{([a-z0-9_-]+([\.-_ ][a-z0-9]+)*)}', re.IGNORECASE)

pattern = '{foo}.{bar} {dom.da}{di.domo.da}{dom}{dom junk}{foo bar}{complex}{}{{funny}}'
matches = var_name.finditer(pattern)

reversed = []
for item in matches:
    if item.group(1) in settings:
        reversed.insert(0, {'key': item.group(1), 'start': item.start(), 'end': item.end()})

converted = pattern
for item in reversed:
    converted = converted[:item["start"]] + str(settings[item["key"]]) + converted[item["end"]:]
    
print(converted)

**Comment by cmungall** [comment]
Thanks @ddooley I agree with this approach

What should the defined behavior be for `{dom junk}`

I can see either

 - leaving as-is, as you have done
 - empty string
 - throwing an error

And what if I want an actual literal `{foo}` in my output (where foo might happen to be a setting)?

the two standard approaches are:

- double the `{` (consist with python format strings)
- escape with `\{`

**Comment by ddooley** [comment]
I think if {dom junk} is left passively as is, then this lets one implement {{foo}} which would return {foo} even if "foo" was a key in settings. Would have to test that.

**Comment by cmungall** [comment]
but that would only work if you set foo=foo, which is a bit awkward?

**Comment by ddooley** [comment]
Tested and realized had to adjust code:

```
import re

settings = {'foo':1,
'bar':'2', 
'dom':4,
'dom.da': 3, 
'di.domo.da': 4,
'dom.doy': 5, 
'dom.doy.du': 6,
'foo bar': 7,
'complex': {'test':'that'},
'funny': 'joke',
'foo':'testola'
}

var_name = re.compile('{([a-z0-9_-]+([\.-_ ][a-z0-9]+)*)}', re.IGNORECASE)

pattern = '{foo}.{bar} {dom.da}{di.domo.da}{dom}{dom junk}{foo bar}{complex}{} {funny} {{foo}} {{fooey}}'
matches = var_name.finditer(pattern)

reversed = []
for item in matches:
    # Detect double set brackets
    match_string = None
    if item.start() > 0 and item.end() < len(pattern) and pattern[item.start() - 1] == '{' and pattern[item.end()] == '}':
        match_string = item.group(1)

    elif item.group(1) in settings:
        match_string = str(settings[item.group(1)])
        
    if match_string:
        reversed.insert(0, {'string': match_string, 'start': item.start(), 'end': item.end()})
        
converted = pattern
for item in reversed:
    converted = converted[:item["start"]] + item["string"] + converted[item["end"]:]
    
print(converted)
```
