### ISSUE TITLE
In Tutorial 1, actual output of command does not match documentation

### ISSUE THREAD

**Issue by tombaker** [linkml/linkml#683]
**Describe the bug**

[Tutorial 1](https://linkml.io/linkml/intro/tutorial01.html) invites the reader to generate a Turtle file from the YAML example, but the output of the command does not match the output shown in the tutorial (or the `data.ttl` provided in the repo).

**To Reproduce**

1. Go to [Tutorial 1](https://linkml.io/linkml/intro/tutorial01.html) and to the corresponding [`tutorial01`](https://github.com/linkml/linkml/tree/main/examples/tutorial/tutorial01) directory in the repo.
2. Execute `linkml-convert -s personinfo.yaml data.yaml -o data.ttl`
3. Execute `git diff data.ttl`
4. See two differences: 1. In generated file, extra colon in prefix definition for `ns1`. 2. In supplied Turtle file, `[] a ns1:dict`.

**Expected behavior**

I expected the contents of the following three Turtle representations to be identical:
- the file [`data.ttl`](https://github.com/linkml/linkml/blob/main/examples/tutorial/tutorial01/data.ttl) supplied in the tutorial folder
- the Turtle file contents shown on the [tutorial page](https://linkml.io/linkml/intro/tutorial01.html)
- the Turtle file generated by `linkml-convert -s personinfo.yaml data.yaml -o data.ttl`

**Additional context**

![Screen Shot 2022-04-09 at 12 04 07](https://user-images.githubusercontent.com/1106086/162567258-763e49c5-3b34-48d7-80c9-3f858ecbe56a.png)

**Comment by cmungall** [comment]
Thanks!

We aim to auto-run all tutorials to validate the actual output is the same
as the stated and check this with gh-actions -- currently blocked on this:
https://github.com/linkml/linkml/issues/427

in the meantime we'll look at this and fix it, many thanks for trying the
tutorial and taking time to give feedback!

**Comment by cmungall** [comment]
@victoriasoesanto can you handle this one once you have fixed the rdf generation use the preferred prefixes?

**Comment by sierra-moxon** [comment]
see also #1043
