### ISSUE TITLE
Markdown generater sometimes generates too much

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#69]
When dealing with a lot of individual components, such as in https://github.com/HOT-Ecosystem/tccm/tree/master/model, generating the complete markdown for every import is overkill.  There needs to be a way to _combine_ the documents under a docs directory vs. generating a complete set of documentation for every module

**Comment by joeflack4** [comment]
This seems down my alley. I think I'll add this as a bullet to the [general markdowngen issue](https://github.com/linkml/linkml/issues/245), but keep it open as its own issue.

**Comment by sierra-moxon** [comment]
I am closing for now as I can no longer see the issue @hsolbrig found (404 error) and because we are moving forward with docgen.  Please reopen if I got this wrong, or if there is another example I can use as a test case to implement a fix.
