### ISSUE TITLE
modify javagen to be compatible with projectgen

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#703]
see 
- #700
- #701 
- #702

The generic `Generator` class has a `serialize` method that takes a `**kwargs` argument

`JavaGenerator` also has a `serialize` method but with a different signature that doesn't accept `**kwargs`

That means that it doesn't accept the `mergeimports` parameter that `ProjectGenerator` passes to all other generators

**Comment by cmungall** [comment]
is this still an issue?

**Comment by nlharris** [comment]
Can this be closed?

**Comment by nlharris** [comment]
gen-project no longer generating java, so we can close this

**Comment by sujaypatil96** [comment]
Related issue: https://github.com/linkml/linkml/issues/571
