### ISSUE TITLE
Create jsonschema parser

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#71]
We would like to be able to map from jsonschema to biolinkml

@hsolbrig any advice on how this would be implemented? Broadly:

 - use an existing Python jsonschema library
 - model jsonschema metamodel in biolinkml and bring in jsonschema as an instance of this in blml (this gets quite meta)
 - some other approach

I assume we would put this in a module path analogous to biolinkml.generators. In future we may want to create biolinkml from:

 - shex
 - dosdp
 - schemablocks
 - rdfs/owl (with the usual OWA/CWA caveats, this may be more heuristic)
 - ...

**Comment by cmungall** [comment]
`jsonschema2linkml` in linkml-model-enrichment

**Comment by sierra-moxon** [comment]
I have tested the jsonschem2linkml framework in schema-automator (formally known as linkml-model-enrichment) so I am closing this ticket "create json schema parser in biolinkml" as done.  Please of course reopen if I am incorrect.
