### ISSUE TITLE
gen-json-schema does not convert some slot definition attributes to "const"

### ISSUE THREAD

**Issue by gcampion-cdisc** [linkml/linkml#726]
**Describe the bug**
During generation, some slot definition attributes should be converted to "const" in the output json-schema. One example is "equals_string", but there are others.

**To Reproduce**
1. create a linkml with the following:

```
...
slots:
  MySlot:
      equals_string: My string value
...
```

2. Generate a json-schema using gen-json-schema

**Expected behavior**

A json-schema is generated with the following:

```
...
"properties": {
    "MySlot": {
        "const": "My string value"
    }
}
...
```
(Currently, a "const" is not created.)

**Comment by cmungall** [comment]
Thanks for the report!

@pkalita-lbl fixed this, and the fix is incorporated into https://github.com/linkml/linkml/releases/tag/v1.2.10, now on pypi
