### ISSUE TITLE
Generator versions are not maintained

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#73]
Generator version numbers are not being updated.  As an example, the json schema generator version is still at "0.0.2".  We need to either come up with a semi-automated way to maintain these or just remove this characteristic

**Comment by cmungall** [comment]
I think we should remove

**Comment by joeflack4** [comment]
I don't mind removing either. It is a nice-to-have, so I think it should be kept in some backlog, but there's probably a lot of other stuff that should be prioritized before this.
