### ISSUE TITLE
make aliases a common metadatum

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#732]
Proximal use case: putting [aliases](https://linkml.io/linkml-model/docs/aliases/) on permissible values, which inherit from the [common metadata](https://linkml.io/linkml-model/docs/CommonMetadata/) mixin. 

Real world: use case: building a model to account for a spreadsheet or relational database that has columns with different values representing the same thing. For example, "Human, person, H_sapiens etc." and "Mouse, m_muscuclus, etc. all in an "organism" column.

The model would contain an enum with PVs like "Homo sapiens" and "Mus musculus", which would both have a small list of aliases as illustrated above.

**Comment by turbomam** [comment]
see https://github.com/linkml/linkml-model/tree/issue-732-aliases-are-common

**Comment by StroemPhi** [comment]
shouldn't this be closed due to https://github.com/linkml/linkml-model/pull/94?
