### ISSUE TITLE
(New?) Runtime  Error in BMT

### ISSUE THREAD

**Issue by RichardBruskiewich** [linkml/linkml#737]
Building an application this weekend (late afternoon  PST, Saturday April 30th) within Pycharms on Mac OSX Monterery  12.3.1 and under Python 3.7.

The pip requirements I have are perhaps a bit constrained by my use of FastAPI. Here's the pip requirements file:

```
fastapi>=0.68.0,<0.69.0
pydantic>=1.8.0,<2.0.0
uvicorn>=0.15.0,<0.16.0
jsonschema==3.2.0
pyyaml==5.4
requests==2.25.1
bmt
```

The FastAPI constraints came from some other source (can't recall) but perhaps they should be reviewed.

The  application imports the latest BMT, which uses LinkML (latest release?). Running the application has the following RuntimeError out of the starting block (i.e. when  BMT is imported... the error is not sensitive to BMT version. I've also previously (i.e. over the past week) had no difficulty installing and running this code on a Windows and inside a Docker container.

I think either there is something amiss in the latest Linkml itself, or perhaps, the  FastAPI requirements for pydantic, pyyaml, jsonschema, etc. are now conflicting with the latest LinkML needs?. Here's the error trace:

```
 from bmt import Toolkit
  File "/Users/richard/PycharmProjects/reasoner-validator/py37/lib/python3.7/site-packages/bmt/__init__.py", line 1, in <module>
    from bmt.toolkit import Toolkit
  File "/Users/richard/PycharmProjects/reasoner-validator/py37/lib/python3.7/site-packages/bmt/toolkit.py", line 3, in <module>
    from linkml_runtime.utils.schemaview import SchemaView
  File "/Users/richard/PycharmProjects/reasoner-validator/py37/lib/python3.7/site-packages/linkml_runtime/__init__.py", line 2, in <module>
    from linkml_runtime.utils.schemaview import SchemaView
  File "/Users/richard/PycharmProjects/reasoner-validator/py37/lib/python3.7/site-packages/linkml_runtime/utils/schemaview.py", line 11, in <module>
    from linkml_runtime.linkml_model.meta import *
  File "/Users/richard/PycharmProjects/reasoner-validator/py37/lib/python3.7/site-packages/linkml_runtime/linkml_model/__init__.py", line 3, in <module>
    from .extensions import Extension, Extensible
  File "/Users/richard/PycharmProjects/reasoner-validator/py37/lib/python3.7/site-packages/linkml_runtime/linkml_model/extensions.py", line 45, in <module>
    class Extension(YAMLRoot):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 991, in dataclass
    return wrap(_cls)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 983, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dataclasses.py", line 904, in _process_class
    else 'self',
TypeError: dataclasses_init_fn_with_kwargs() missing 1 required positional argument: 'globals'

```

**Comment by RichardBruskiewich** [comment]
Sorry... not sure why,  but for some reason,  the pip install is not picking up the latest linkml... even though I don't apply the constraints. I wonder if this relates to the other indirect package restrictions (for  pedantic and pyyaml...)?

BTW, I've not previously used FastAPI on  my projects and thought it time to try... some of the constraints seem to  come  from there (unless I'm not getting the right dependencies in from there...)

**Comment by RichardBruskiewich** [comment]
Brief update: 

1. Even with an empty `venv` (in PyCharms, _without_ any global packages imported), the MacOSX version persistently installs the ancient LinkML module instead of the latest. I've performed the identical operations under a Windows copy of PyCharms, and LinkML **does** update to the latest version (1.2.10).
2. I tried enforcing the pip installation to `LinkML>=1.2.8`, but then I get another bizarre error: 
```shell
INFO: pip is looking at multiple versions of linkml to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements-service.txt (line 2), linkml and pyshex==0.7.20 because these package versions have conflicting dependencies.

The conflict is caused by:
    linkml 1.2.8 depends on rdflib>=6.0.0
    linkml-runtime 1.2.4 depends on rdflib>=6.0.0
    pyshex 0.7.20 depends on rdflib~=5.0
    pyshex 0.8.1 depends on sparqlslurper>=0.5.1
    pyshex 0.8.0 depends on sparqlslurper>=0.5.1
```

Baffling.

Anyhow, I'm back working on my Windows workstation today, without any of the above headaches (ran the exact same pip install on an empty `venv` and it works fine....although, a disclaimer is that I ran it with Python 3.9, not 3.7...)

Is anyone else using Pycharms on Mac OSX Monterery 12.3.1 and under Python 3.7, and encountering these problems?

Since fixing the above is not critical to my further progress with my application (under Windows), I'm going to leave this issue for now, posted for the kind consideration of other folks.

**Comment by cmungall** [comment]
I recommend poetry at least for debugging this kind of thing, it can reason
about the version constraint satisfaction problem much faster (but
explanations are still not as good as what you get when reasoning with
protege - i sometimes think we should encode dependencies in owl….)

So it looks like your initial dependencies are ultra restrictive. Do they
need to be?

It looks like it doesn’t want to install a newer pyshex- can you figure why?

**Comment by cmungall** [comment]
Also process of elimination usually works

I’d prune the search tree by starting with just bmt and linkml and expand
out

**Comment by cmungall** [comment]
FWIW I was able to get this to work with 3.9.5

```
[tool.poetry]
name = "linkml-bmt-test"
version = "0.1.0"
description = ""
authors = ["cmungall <cjm@berkeleybop.org>"]

[tool.poetry.dependencies]
python = "^3.9"
linkml = "^1.2.10"
bmt = "^0.8.4"
fastapi = ">=0.68.0,<0.69.0"
pydantic = ">=1.8.0,<2.0.0"
uvicorn = ">=0.15.0,<0.16.0"
jsonschema = "3.2.0"
PyYAML = "5.4"
requests = "2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

my guess is that 3.7 is too low for some newer version of some dependency, forcing the downgrade -- especially for some early 3.7.xs

Do you really need 3.7?
