### ISSUE TITLE
allowing some extra functionality for minimum_value and maximum_value

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#751]
**Is your feature request related to a problem? Please describe.**
So far linkml minimum_value and maximum_value accept only integer numeric values.
The XML specification is a bit more general, allowing min and max to apply to other kinds of data structure like Date.  We took advantage of that in DataHarmonizer to allow dates to be entered. 

**Describe the solution you'd like**
 Could validation on these be loosened up to allow for dates. We have dataharmonizer code in place to validate min and max dates.

As well we have a special value "{today}" which if put in a min value or max value field, forces any entered date to be before or after today.  This is a simple way to block erroneous future dates from being entered for a field that pertains to the past for example.  Possibly this could be handled via some other mechanism, like a linkml rule engine?

**How important is this feature?** Select from the options below:
• Medium - I'd have to do a workaround to preserve DH functionality.

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by cmungall** [comment]
Some options:

 1. range loosened to be Any to allow for floats, date
 2. add companion fields to https://w3id.org/linkml/equals_expression

The advantage of 2 is that could be used for more powerful expressions, e.g. `today+100` -- the full language is harder for tools to implement but we could define a profile

**Comment by sierra-moxon** [comment]
closing as complete; please reopen if I got this wrong. :)
