### ISSUE TITLE
`linkml-ws` followup: `make setup`: `poetry: command not found`

### ISSUE THREAD

**Issue by joeflack4** [linkml/linkml#753]
**Describe the bug**
I'm following the steps [in this video](https://asciinema.org/a/GHydP2cs0NIyUdhjvwvSFvB91) to set up a new LinkML project using `linkml-ws`.

**To Reproduce**
1. Create an empty directory in which to create project.
2. (~optional) Make a virtual environment
3. `pip install linkml`
4. Try to create a new LinkML workspace using: `linmkl-ws new -D "<WORKSPACE_NAME>" <WORKSPACE_NAME>`
5. `cd <WORKSPACE_NAME>`
6. `make setup`

**Expected behavior**
Project should be set up.

**Actual behavior**
```
make setup
poetry install
bash: poetry: command not found
make: *** [install] Error 127
```

**Things I tried**
1. Making sure LinkML is installed.
```
pip freeze | grep linkml
biolinkml==1.7.6
linkml==1.2.10
linkml-dataops==0.1.0
linkml-runtime==1.2.9
linmkl-ws new -D "tccm"
zsh: command not found: linmkl-ws
```

**Possible solutions**
1. Making sure that the following is included as an argument to `setup()` in `setup.py`:
```
      install_requires=[
          'poetry',
      ],
```

**Comment by joeflack4** [comment]
I mistyped `linkml-ws` as `linmkl-ws` lol

**Comment by sujaypatil96** [comment]
@joeflack4 you can see the repo no longer uses setuptools and pipenv for package management. We could have documented this better, but you can install the poetry binaries on your machine, and not as a python package, by following the instructions here: https://python-poetry.org/docs/

**Comment by joeflack4** [comment]
I am aware now, thanks Sujay. I discussed briefly w/ Chris during a LinkML meeting. He understands the UX argument I'm making. I think probably some automation can be done for the edge case where a random user on the internet wants to pick up LinkML, but isn't using poetry. But it is probably not worth the dev time anyway to handle that case, so I really don't mind if this PR is closed. I mainly wanted to bring attention to the issue. Hopefully I can contribute in a more meaningful way though some time in the future.

**Comment by sierra-moxon** [comment]
Hi @joeflack4  - thanks!  You could also checkout the linkml-initializer, which is the start of a web-based project creation strategy.  Closing for now, but please do try it out and give @pkalita-lbl any feedback about how it could be improved.
