### ISSUE TITLE
linkml/linkml PR testing new common metadata in linkml-runtime 1.3.0rc1

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#756]
https://pypi.org/project/linkml-runtime/1.3.0rc1/ includes additional common metadata from https://github.com/linkml/linkml-model/pull/94/files

For example, @ddooley's request for mappings on Permissible Values

**Comment by turbomam** [comment]
https://github.com/linkml/linkml/tree/issue-756-pv-mappings

**Comment by turbomam** [comment]
pyproject.toml says

linkml-runtime = "==1.2.*,>=1.2.4"

**Comment by turbomam** [comment]
https://pypi.org/project/linkml-runtime/1.3.0rc1/#history says

- 1.3.0rc1 @ April 28th
- 1.2.11rc1 @ May 6th

**Comment by turbomam** [comment]
allowing PyPI pre-releases in poetry: https://github.com/python-poetry/poetry/issues/3538

**Comment by nlharris** [comment]
Can this be closed?
