### ISSUE TITLE
Improve LinkML documentation

### ISSUE THREAD

**Issue by nlharris** [linkml/linkml#759]
This ticket is mostly a placeholder for me. I will work on improving the documentation and looping others in to help as appropriate.

Links:

- https://linkml.io/ -- main splash page
- https://linkml.io/linkml -- core tools docs
- https://github.com/linkml/schema-automator - schema inference
- https://linkml.io/linkml-registry/registry/

Peter: I think the [introduction](https://github.com/linkml/.github/blob/main/profile/README.md) is confusing:

> LinkML is a flexible modeling language that allows you to author schemas in YAML that describe the structure of your data. LinkML provides a framework for working with and validating data in a variety of formats (JSON, RDF, TSV) provides generators for compiling LinkML schemas to other frameworks.
 
It would be better to say
 
> LinkML is a both a flexible modeling language that allows you to author schemas in YAML that describe the structure of your data as well as a framework for working with and validating data in a variety of formats (JSON, RDF, TSV) provides generators for compiling LinkML schemas to other frameworks.
 
It would be even better not to use the same name for the schema and the tool!

Chris: So technically the schema that describes linkml is linkml-metamodel, the repos are:

https://github.com/linkml/linkml. ## various tools and scripts
https://github.com/linkml/linkml-model. ## the metamodel / self-describing schema

it would be a bit churny to change names now but I agree it's potentially confusing. Maybe if the linkml repo just better describes itself as being the tools...

Jules: Yes, I'd also like to see a lot more information in the README.md about the purpose and content of the repo, especially if it might not be the most accurately named one. Having an embedded link to detailed documentation is good, but I feel there still ought to be some detail in the README given it's the first thing anyone reads.

As you suggested, it would be good if https://github.com/linkml/linkml mentions that the repo contains various tools and scripts and briefly mention what the most important ones are and how they are used.

**Comment by nlharris** [comment]
BTW, I don't have the power to self-assign this ticket or to add a label.

**Comment by nlharris** [comment]
Chris suggested "we should flesh out https://linkml.io/linkml/developers/organization.html and include a link to it"

**Comment by sierra-moxon** [comment]
@nlharris - I checked your permissions on both the organization and this repo in particular, and from what I can see you have write permission here, and full dev privileges on linkml. 🤔

**Comment by nlharris** [comment]
<img width="723" alt="Screen Shot 2022-06-01 at 11 24 55 AM" src="https://user-images.githubusercontent.com/348704/171475853-4233650f-de10-435d-b1a5-9f12ef1bb1ae.png">

**Comment by nlharris** [comment]
todo:

- [ ] Improve topic page, https://github.com/topics/linkml
Add a description, image, and links to the linkml topic page so that developers can more easily learn about it.
Curate this topic: https://github.com/github/explore/blob/main/CONTRIBUTING.md

**Comment by cmungall** [comment]
We still need to properly unify contributor docs

https://github.com/linkml/linkml-runtime/blob/main/CONTRIBUTING.md

this refers to requirements.txt which is no longer used

**Comment by dalito** [comment]
What I missed in contributors docs: During running the tests a lot of files are created which are persisting and mess up a the checked-out repo. A note how to get rid of these test artifacts would be nice (or could these files be created in git-ignored directories?). Most other project do not require manual clean-up after running tests.

**Comment by nlharris** [comment]
> A note on how to get rid of these test artifacts would be nice (or could these files be created in git-ignored directories?)

Why not have the test-runner clean up the test files itself at the end of the run?

**Comment by dalito** [comment]
I was wondering the same...

**Comment by nlharris** [comment]
@dalito would you mind creating a new ticket with that suggestion? Thanks!

**Comment by dalito** [comment]
I created 2 PRs to improve the documentation of the current state and created #880 to address the "clean test run".
