### ISSUE TITLE
add link to the range of a slot in Jinja based the schema documentation

### ISSUE THREAD

**Issue by StroemPhi** [linkml/linkml#778]
At the moment the range class of a slot is not linked to in the schema documentation. I guess, it has to do with:
https://github.com/linkml/linkml/blob/1bbf442f5c0dab5b6a4eb3309ef25b95c74d0892/linkml/generators/docgen/slot.md.jinja2#L25

where it should actually be `{{gen.link(element.range)}}`. If I'm correct, I could attempt a PR.

**Comment by cmungall** [comment]
If you could do a PR that would be super-wonderful!
