### ISSUE TITLE
gendoc should use internal and external links appropriately

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#782]
Consider a schema that is split into modules, some of which import *external* schemas

E.g.

 * my_schema.yaml; imports a, b, linkml:types
 * a.yaml; imports linkml:types
 * a.yaml; imports biolink:biolink-model, linkml:types

The default behavior for gendoc should be to generate md files only for *internal* modules (my_schema, a, b), using *internal* links. When referring to an element in an *external* schema (e.g. Gene in biolink, String in linkml:types) then the full URI should be used for linking.

Ideally indexes for each internal module (e.g. my_schema.md, a.md, b.md) should also be generated, as well as index.md which contains the merger of all internal modules.

Note the distinction between 'external' and 'internal' is not always crisp and we will want to allow some configurability here (in particular for the metamodel, linkml:types is internal not external)

This will fix: https://github.com/linkml/linkml-project-template/issues/15

**Comment by sierra-moxon** [comment]
I believe this is done; I see URIs in linkml:type linking in nmdc docs.
