### ISSUE TITLE
Solve the yaml file distribution problem in the project template

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#797]
In
https://github.com/linkml/linkml-project-template/blob/main/pyproject.toml

We have

```
include = ["README.md", "src/linkml", "project"]
```

The intention is that I can make a schema project my_schema, release to pypi, and then others can use `package_schemaview` to introspect the schema (which is meant to read the yaml in src/linkml on the fly)

However, it seems this isn't working as advertised - @hrshdhgd ran into this with the NEAT repo. We were basing this off the nmdc repo but it seems nmdc is (accidentally) polluting the top level, which is not a scalable solution.

It seems others have run into this issue with poetry; there is a confusing ticket with what I think are false starts, see my summary:

https://github.com/python-poetry/poetry/issues/2015#issuecomment-1133467892

I'm a bit stuck as to suggesting how to proceed. the pre-build copy seems a little problematic.

The most robust solution is for people to have the source for their schemas live in `src/my_schema/my_schema.yaml`. We do this for projects like oaklib (see [src/oaklib/datamodels](https://github.com/INCATools/ontology-access-kit/tree/main/src/oaklib/datamodels)) but that's a Python-centric project

It seems suboptimal for projects that are not python-centric. Of course if the project doesn't intend to release to pypi at all there is no issue. But most projects are schema-centric that also have a pypi distribution. Here we would be asking curators and modelers to look in a folder `src/my_schema` for the source which is not the end of the world but is a little unsatisfying.

**Comment by cmungall** [comment]
@hrshdhgd has adopted one approach for sssom-schema, where we have `/src/` *under* the python package

but this means to use we need to do `import sssom_schema.src.sssom_schema`

To implement my scheme above for sssom we would have

 * sssom_schema
     - sssom_schema.yaml <- SOT, edited by schema maintainers
     - sssom_schema.py <- generated by gen-project in Makefile

(This could be optionally embedded further under a top level `src` but that's a separable decision)

The disadvantage is the location is slightly non-obvious for a non-python dev, we are forcing pythonic patterns on everyone. Also people may be confused to see a .py file next to the yaml.

Alternative: keep sssom_schema.yaml in a more intuitive location, and copy it to sssom_schema as part of the poetry publish step

**Comment by hrshdhgd** [comment]
I think I have a solution but need a second opinion:

This is with src being at the top level.

 - The only file structure change will be moving the `linkml` dir into `datamodel`
 - The _init_.py file under src/xxxx_schema folder will have this one line
```from .datamodel.xxxx_schema import *```

That's it. Once the `xxxx-schema` package is published using `poetry build` you have the yaml and python files and the target project (where the schema is implemented) , all that needs to be done is:
``` from xxxx_schema import ClassA``` and it works! 

I still have to figure out if it'll play with `package_schemaview` from `linkml` . If it doesn't we can use `pkg_resources` to get the YAML file and then use it as needed.

**Comment by nlharris** [comment]
Is this done?

**Comment by cmungall** [comment]
yes, in cookiecutter
