### ISSUE TITLE
Document index-slot

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#808]
Please document better what `-S/--index-slot` is. I am trying to do a 

tsv->schema generator->convert rdf workflow and I don't really get this "required" parameter.

**Comment by matentzn** [comment]
If this container object is so key to the conversion process, shouldn't the schema automator process create them when "inferring" a schema from a table?

**Comment by sierra-moxon** [comment]
@matentzn  - I think Chris answered your question?  If not, please of course feel free to reopen. :)
