### ISSUE TITLE
linkml-sqldb dump doesn't work when using --module argument

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#813]
I can't seem to get linkml-sqldb dump to work with the --module argument. It says

> UnboundLocalError: local variable 'sv' referenced before assignment

It does work with the --schema argument

See the problematic_sqlite rule in https://github.com/turbomam/linkml-abuse/blob/main/Makefile

I think that's coming from [linkml.utils.sqlutils.dump](https://github.com/linkml/linkml/blob/3b7a267fff62480a2d554dae3607f88444700564/linkml/utils/sqlutils.py#L303)

See also https://monarchinitiative.slack.com/archives/C01LDTVURH9/p1652987387692819

**Comment by cmungall** [comment]
We should definitely improve the reporting, but I think this works if you specify schema and module or module and target class

just specifying module alone gives insufficient information to know what the top level class to instantiate is

**Comment by turbomam** [comment]
Thanks. Under what circumstances would it be beneficial to specify the schema and the module (since you can do it with the schema alone)?

I'll try module and target class.

**Comment by cmungall** [comment]
You may wish to avoid the compilation step, perhaps you have dataclasses or pydantic generated some other way. Rare though
