### ISSUE TITLE
Add disjointness and disjoint union

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#82]
Want to be able to say a set of classes are disjoint

also disjoint union: Parent = C1 or C2 or ... Cn, where all children are disjoint

Also good to have shortcuts

E.g. at whole schema level, saying whole schema is JEPD (Jointly Exhaustive Pairwise Disjoint), or at the class level (all children are JEPD)

ALTERNATIVE: we could just map to an OWL ontology and do disjointness reasoning there

**Comment by sierra-moxon** [comment]
We do have `disjoint_with` in the metamodel now; closing as complete.
