### ISSUE TITLE
multivalued and required slot does not allow empty array when converted to OWL

### ISSUE THREAD

**Issue by adlerfaulkner** [linkml/linkml#826]
**Describe the bug**
When I have a slot that is both `multivalued` and `required`, generating owl from my linkml schema produces a `owl:someValuesFrom` restriction. From the [definition of this restriction](https://www.w3.org/TR/owl-ref/#someValuesFrom-def):

> A restriction containing an owl:someValuesFrom constraint describes a class of all individuals for which at least one value of the property concerned is an instance of the class description or a data value in the data range.

From this definition, a validation against the owl restriction should fail if my slot were empty. However, I would not expect `multivalued` and `required` to denote that an empty array is invalid. 

`multivalued` [indicates that the range of the slot is a list](https://linkml.io/linkml/schemas/slots.html?highlight=slot_usage#multivalued)
`required` specifies that the class [must have a value for that slot](https://linkml.io/linkml/schemas/slots.html?highlight=slot_usage#required)

I would expect these two definitions to allow for an empty array as the value of the slot, as long as the slot is present on an instance of the class. Is this mismatch just due to the fact that RDF can't really represent an empty list because there would just be no triples present for that subject & predicate pair?

**To Reproduce**
schema.yaml:
```
classes:
    NamedThing:
        attributes:
            subThings:
                required: true
                multivalued: true
```
Run:
`gen-owl schema.yaml > schema.owl.ttl`

**Expected behavior**
Not sure OWL can actually support having the field be required but not requiring  > 0 values in the list?

**Desktop (if applicable, please complete the following information):**
- OS: macOS 12.3.1
- Linkml: 1.2.11

**Additional Context**
https://github.com/json-ld/json-ld.org/issues/220

**Comment by cmungall** [comment]
Thanks @adlerfaulkner - this is actually working as intended. We need to clarify the definition of required - in fact for multivalued slots, required means at least one value.

Neither OWL not the LinkML instance model have a formal distinction between null values and empty collections of triples. i.e. the following are all equivalent:

```
{
  subThings: []
}
```

```
{
  subThings:
}
```

```
{
}
```

the last one is the canonical form emitted by json_dumper

I realize this is subtly different from programming language semantics, e.g. `Optional[List]` in python

(in future we could consider additional slots for empty list behavior for people who want to be able to precisely shape the json output or the shape of instantiated objects in code)

> From this definition, a validation against the owl restriction should fail if my slot were empty.

Remember, OWL is open-world. There isn't technically such a thing as validation against an OWL restriction. However, if you specified instance data that lacked a triple with this predicate, an OWL reasoner would infer it was there, you just hadn't told it about it.

Does that make sense?

**Comment by adlerfaulkner** [comment]
Yes, makes sense. 

Although it doesn't solve the empty array problem, maybe I should switch to generating SHACL which it would make more sense to validate against as it follows a closed world assumption.

**Comment by cmungall** [comment]
yes, generating shacl from the linkml to validate rdf makes sense - let us know if you have any issues. The json-schema generator is more widely used and thus better tested.

**Comment by adlerfaulkner** [comment]
@cmungall yeah, json-schema would be nice but I want to stick to the linked data world. Some questions:
1. Would it be possible to add an option to set `sh:closed false` on my generated shapes?
2. Would it be possible to add `a rdfs:Class` to the generated shapes?

**Comment by adlerfaulkner** [comment]
Ah also is it possible to add `rdfs:subClassOf` to the generated shapes based on the `is_a` slot of linkml classes?
