### ISSUE TITLE
Serialising language tags curated as slots in RDF

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#827]
Ok, I know what @cmungall will say to that:

I have a data model with two slots

- lang
- value

I would love it if somehow during RDF conversion, this could end up as "value"@lang.

Example:

```
lang: en
value: ship
```

... ?prop "ship@en".

Probably too crazy right, @cmungall? You would prefer a new datatype, "string with language tag" to solve this issue I assume? It seems like it would be nice if data models could curate language of a string independently of the string itself..

**Comment by cmungall** [comment]
Related:

- #694 

Note that the JSON-LD folks went through a lot of deliberation with how to unify a more conventional tree-like JSON data model with RDF literals - https://github.com/json-ld/json-ld.org/issues/133

I would like language support to be consistent - i.e. if you dump json using json_dumper, export a json-ld context, then merging these and feeding through a standard rdf tool will generate the desired rdf. 

I think this should be possible - basically the idea would be to have json_dumper target the desired form here:
https://json-ld.org/spec/latest/json-ld/#string-internationalization

**Comment by matentzn** [comment]
I have not thought about this deeply enough to answer that, I am literally thinking about this case:

| value | lang |
| ---- | ----- |
| ship | en |

turning to ship@en in RDF from a practical perspective of the table.  Oops forgot about #694 if you want, lets close this and move the discussion back there.

**Comment by sierra-moxon** [comment]
closed; discussion in 694
