### ISSUE TITLE
Duplicate arrows in YUML

### ISSUE THREAD

**Issue by lexjansen** [linkml/linkml#839]
I am relatively new to linkml. I have a simple linkml schema test.yaml

I create a YUML representation:  gen-yuml -f yuml test.yaml

Result:
https://yuml.me/diagram/nofunky;dir:TB/class/[CodeListTerm|term_id:string;term_value:string %3F]<codelist_term 0..1- [SubsetCodeList|name:string],[SubsetCodeList]- codelist_term 0..1>[CodeListTerm]

It gives the attached test,svg file.
Why are there 2 arrows from SubsetCodeList to CodeListterm?

[test.yaml.txt](https://github.com/linkml/linkml/files/8912767/test.yaml.txt)
![test](https://user-images.githubusercontent.com/11705643/173918462-49ead280-9ed6-40df-889d-3af97705d513.svg)

**Comment by cmungall** [comment]
Hi @lexjansen!

Apologies for the delay in responding. We're actually moving away from yuml towards mermaid, which will fix this issue

**Comment by lexjansen** [comment]
Thanks, @cmungall, much appreciated!
Cheers, Lex

**Comment by sierra-moxon** [comment]
Hi @lexjansen - I have captured this request in the project for mermaid and doc-generation.  :). Thanks for submitting it! I am going to close this issue now and address in mermaid.
