### ISSUE TITLE
Update rdflib dependency

### ISSUE THREAD

**Issue by hrshdhgd** [linkml/linkml#851]
**Describe the bug**
I was under the impression that `linkml` was updated to use `rdflib>=6.0.0` but it seems from the [`poetry.lock`](https://github.com/linkml/linkml/blob/main/poetry.lock#L1047) file that it is [`rdflib>=5.0.0`](https://github.com/linkml/linkml/blob/8906fb8539d77d858db5cf2c895f5f2358d71e0f/poetry.lock#L1046) and uses [`rdflib-jsonld`](https://github.com/linkml/linkml/blob/8906fb8539d77d858db5cf2c895f5f2358d71e0f/poetry.lock#L1047)

**To Reproduce**
When I run any CLI in `sssom-py` e.g. `sssom validate tests/data/basic.tsv` , I get 
```
DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
```

**Expected behavior**
No such warning since we already use `rdflib==6.1.1`.

**Additional context**

I seem to have the following installed through linkml:
```
rdflib-jsonld             0.6.1                    pypi_0    pypi
rdflib-pyldmod-compat     0.1.2                    pypi_0    pypi
rdflib-shim               1.0.3                    pypi_0    pypi
```
Are these all needed? Kindly advise.

**Comment by cmungall** [comment]
Remember, sssom, like most schema repos should only have `linkml` as a *developer dependency*. It should only have a *runtime dependency* on `linkml-runtime`

Either way, both libraries force rdflib 6.0.0 or higher. I expect what you are seeing in something peculiar to sssom or your own setup?
