### ISSUE TITLE
proposal: weakly deprecate default_curi_maps

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#852]
Proposal: 

- discourage use of imported prefix maps
- encourage use of explicit prefix maps
- exception: a very minimal set of core prefixes (owl, xsd, rdf, rdfs, linkml)
- better document existing tooling to assist in auto-populating prefixmaps e.g. using bioregistry

The rationale is that the imported prefix maps are not guaranteed to be in sync with the schema - a change in an default curi map upstream could modify the RDF produced for a data following some schema. It is better to have this be fully under control.

We may also want to explore ways of allowing for imports of prefix maps using the existing schema import mechanism

**Comment by matentzn** [comment]
I think it would be great if I could feed explicit curie maps to linkml-convert. Should I open a new ticket for that?

**Comment by sierra-moxon** [comment]
https://github.com/linkml/linkml-runtime/pull/231 - now we can use prefixmaps (incl. bioregistry) in a linkml model.  The PR doesn't weakly deprecate default_curi_maps.
