### ISSUE TITLE
Should parsers automatically trim strings?

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#855]
I am on the fence here, but I notice that if my **CSV table cells** have trailing or leading whitespace, these get manifested in the ontology - without so much as a warning.. 

Maybe this is a data quality issue, and rather than having linkml-convert deal with the issue, some more logging should be provided, but it seems like in 99.9% of all cases leading or trailing whitespace is just a mistake?

**Comment by cmungall** [comment]
is this just a CSV issue? Presumably it can happen with json/yaml/rdf, particularly where these are populated from a UI that doesn't do any checking

How would logging work in a way that doesn't disrupt things for people that for some reason do want trailing whitespace preserved?

My preferred way to deal with this is as a part of

- #845 

The schema author can declare slots or types to exclude trailing whitespace, these would be forbidden, but a general repair function could tidy this (optionally with warnings) on import.

That may be overkill for this use case and we may just want a simple pass-through option for csv loading, with pass through linkml-convert -> csv_loader -> csvreader. I worry a bit about lots of ad-hoc passthrough kwargs for dealing with things that aren't the responsibility of the framework though.

What do others think?

**Comment by matentzn** [comment]
I share exactly your questions and worries! This could be a case for `-vvv` logging mode perhaps, or, we can collectively decide this should be dealt with upstream, also fine!

**Comment by sierra-moxon** [comment]
from @turbomam - would also like internal whitespace condensed.

**Comment by sierra-moxon** [comment]
I think the linter now accomplishes this task; albeit via a different step.
closing as complete; but please reopen if I made a mistake :)
