### ISSUE TITLE
Make it possible to feed prefix maps to linkml-convert

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#856]
Right now, when transforming from a CURIE to a URI-based representation (i.e. TSV to RDF), we have to hard-code the prefix map in the linkml schema - which is not realistic for a wide range of data sets. I would like some one to pass a prefix map to linkml-convert, either through a simple yaml file (ala sssom-py) or through the already existing "context" parameter.

**Comment by sierra-moxon** [comment]
check on completeness

**Comment by cmungall** [comment]
Individual prefixes can be passed on the command line but passing a prefix
map file would be convenient and a good first issue for someone
