### ISSUE TITLE
Implement caching mechanism for imports

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#866]
The main problem with #502 (network runtimedependency via prefixcommons) is fixed, but we need to carry over one other issue - we would like it such that imports --- and in particular, importing linkml:types --- can be cached. Possibly using zenodo for releases

**Comment by sierra-moxon** [comment]
For larger files, I think zenodo has some limits (from work with @kltm @ GO).  Is GO considering another solution @kltm ? :)

**Comment by kltm** [comment]
> For larger files, I think zenodo has some limits (from work with @kltm @ GO). Is GO considering another solution @kltm ? :)

~50GB be load for Zenodo these days. What kind of sizes are you looking at? As I haven't found another easy-to-use versioned DOIed archive system, I think we'll either split things up or start chucking out some of the database products (with an "easy-to-use" docker runner system to build them on demand from archived data products.

If one is willing to be flexible, one can use OSF.io for DOIs and back them with AWS S3/Glacier or something, but that is sliding more out of the emergency/archive area and into file distribution.

**Comment by kltm** [comment]
Also, caching and archive are very very different use cases, IMO.
