### ISSUE TITLE
Allow classes to have version numbers

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#868]
**Is your feature request related to a problem? Please describe.**
A schema can have a version number but its classes cannot. Our DataHarmonizer use case is that our users are using one or more specific classes within a larger schema as a data collection standard.  They would like to increment a class version when some aspect of that particular class changes, so that downstream users of ONLY that class can update their data collection systems accordingly.  We have a Monkeypox schema with Canadian and International-specific classes, which would diverge in respective version x.y.z numbers when changes to just one or the other happen.

Later we'd try to automate the version increment but for now it is a manual process.

**Describe the solution you'd like**
Allow "version" slot for Classes.
Or, if concerned about name collision, call it "class_version".

**How important is this feature?** Select from the options below:
• Important - it's a blocker and can't do work without it
Not needed this week but very soon our CDN and INTL monkeypox classes will diverge.

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by ddooley** [comment]
It would be great to know if this is an easy change, or ideologically difficult!

**Comment by sierra-moxon** [comment]
@ddooley - I wonder if you could use an "annotation" here to specify the class version for your use case?  For example, in biolink-model, we use "[annotations](https://github.com/biolink/biolink-model/blob/880a59c69c8054c4474fea47add8c489a75d5342/biolink-model.yaml#L1421)" for downstream software to isolate specific parts of the model for use over others.

**Comment by ddooley** [comment]
Thanks, perfect! Case closed!
