### ISSUE TITLE
Remove excessive use of lambdas in old unit tests

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#870]
Some of the tests are a little over abstract

E.g
https://github.com/linkml/linkml/blob/49651de0a582be476457828c3885ca71b21ce016/tests/test_base/test_json.py#L40-L44

This passes in a variable `gen` which is a python class

this then calls

https://github.com/linkml/linkml/blob/49651de0a582be476457828c3885ca71b21ce016/tests/utils/generatortestcase.py#L27-L51

which then calls a lambda... which itself dynamically dispatched based on the value of `gen`:

https://github.com/linkml/linkml/blob/49651de0a582be476457828c3885ca71b21ce016/tests/utils/generatortestcase.py#L63-L65

This is a little hard to add tracepoints with a debugger, consider having a little more repetition to make it easier to mentally reason over

**Comment by nlharris** [comment]
Is this still needed?

**Comment by cmungall** [comment]
This has pretty much been taken care of by @sneakers-the-rat and @pkalita-lbl as part of general test framework overhaul
