### ISSUE TITLE
Use sv.class_slots(direct=True) in docgen to replicate the functionality in markdowngen 

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#878]
There is generic code in markdowngen for computing:
* list of all slots that directly belong to a class
* list of all inherited slots
* list of all slots acquired through mixing

which are useful helper methods that should also be present in docgen.

Block of code to look out for: https://github.com/linkml/linkml/blob/main/linkml/generators/markdowngen.py#L220-L257

**Comment by sierra-moxon** [comment]
Thanks @sujaypatil96!  

Is the schema view method `sv.class_slots(direct=True)` helpful here?   Is the intention with the latter code, that does an intersection, to exclude attributes and slot usage?

**Comment by cmungall** [comment]
what is the broader objective here?

**Comment by sujaypatil96** [comment]
Closing as this is resolved in PR #888
