### ISSUE TITLE
w3id.org for linkml/types returns 404

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#883]
**Describe the bug**
https://w3id.org/linkml/types redirects to https://linkml.io/linkml-model/docs/types and returns a 404.

**Comment by matentzn** [comment]
I dont know if this is related, but seems that when you search for `date`:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/7070631/184544215-ef7ca8ef-c9b0-49d4-9de1-6caa491dae5c.png">


Then click on `date` (lowercase)

you end up on a 404 as well

**Comment by cmungall** [comment]
It looks like this broke when we switched to docgen

Currently URLs like https://w3id.org/linkml/Float *do* resolve, however, the correct URL is in fact https://w3id.org/linkml/types/Float

It also appears that internal links within the site at https://w3id.org/linkml/ do work, so when we fix this we will have to make sure that the internal links work too

**Comment by sierra-moxon** [comment]
these seem to work now;closing as complete.
