### ISSUE TITLE
linkml-validate only shows first erorr

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#891]
there should be a mode to report all errors

**Comment by turbomam** [comment]
From Quan Wan from the Curated Metagenomic Data

**Comment by QuanWan89** [comment]
Hi, from our test with linkml-validate, it only returns the first error from our data. From our use case, we would like to return all errors from one csv or yaml at the same time. So that user can change all errors before resubmitting for next validation.

**Comment by sierra-moxon** [comment]
Thanks @QuanWan89 - great suggestion.

**Comment by only1chunts** [comment]
We've just been discussing this in the GSC working group too, and we feel it would be great if the validator ran across all values in the csv/yaml input file and provided a report of all warnings and failures instead of just stopping at the first error it finds.

**Comment by QuanWan89** [comment]
Thanks. I totally agree it is much helpful if linkML can directly validate csv file, too. Do we have any estimation of time for these two features?
