### ISSUE TITLE
better documentation for using functionality of LinkML CLI commands without Python system calls

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#893]
Users who have developed familiarity with LinkML CLI tools may be tempted to use Python's system call to wrap the CLI tool. We should make it clear how to use the relevant methods directly

**Comment by turbomam** [comment]
From Quan Wan from the Curated Metagenomic Data

**Comment by sierra-moxon** [comment]
@turbomam - sounds like a great idea, did you already have an idea of which methods you'd like to document for wrapping?  I think we could get some help with documentation if we had a roadmap or a list of functions that need to be documented. :)

**Comment by cmungall** [comment]
To echo what @sierra-moxon is saying: I am not sure how this is different from the more general issue of "make sure all classes and methods are well documented"

We could definitely do better here. We expose a subset of the developer API using standard sphinx here:

https://linkml.io/linkml/code.html

But I think there may be a deeper question here I am missing

**Comment by sierra-moxon** [comment]
I am going to close for now, I know we can do more to document our methods, including adding example usage to our docstrings.  But, this ticket probably isn't prompting us to do so.  (no one is assigned, and the mandate is too broad).   Please reopen if I got this wrong as usual! :)
