### ISSUE TITLE
JSONschema generator creates incorrect specs when hyphens present in names

### ISSUE THREAD

**Issue by ialarmedalien** [linkml/linkml#897]
**Describe the bug**

Hyphens in slot/attribute names get converted into underscores but do not get changed back when the jsonschema is generated.

**To Reproduce**

1. Create a schema with a field name such as `message-type` and set it to be a required field.
2. Generate a JSONschema version of it
3. Try validating a data file.
4. Cry at messages like `'message_type' is a required property`
5. Peruse generated JSONschema file and see that all your favourite hyphens have been turned into underscores.

**Comment by cmungall** [comment]
Dupe with #807

**Comment by sierra-moxon** [comment]
Keeping #807 open as the earlier ticket, tagging @ialarmedalien there as well to follow progress.  Closing for now as dupe.
