### ISSUE TITLE
Minimal biolinkml version attribute

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#90]
BiolinkML schemas need the ability to state the minimum biolinkml version required to interpret the model.  It would be a lot nicer to say "Sorry: I'm not smart enough to understand what's in this model" instead of regurgitating pages of error messages on perfectly valid models.

**Comment by RichardBruskiewich** [comment]
In revisiting the above issue, it seems that it was resolved ages ago by the discussion and LinkML code generation.  Models (e.g like the Biolink Model) already have an embedded `version:` tag, right? 

Thus, this issue can be closed?
