### ISSUE TITLE
docgen over-truncates some description strings

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#907]
When docgen is creating a summary table with a description column, it truncates everything the `.`

This is to deal with situations where descriptions are over-long and don't fit nicely in a table.

However, phenopackets has descriptions like "e.g. 50mg/ml 3 times daily for two weeks"

Which get truncated to `e`

Action:

- truncation should only be applied after this first N characters (N=30?)
- truncation behavior should be configurable. Some groups may want the full description in the summary table even if this doesn't render well

Note of course nothing is truncated in the per-element view

**Comment by sujaypatil96** [comment]
I'm looking at the docs here: https://cmungall.github.io/linkml-phenopackets/, and I don't see the descriptions being truncated anywhere in the summary tables: https://cmungall.github.io/linkml-phenopackets/#classes or https://cmungall.github.io/linkml-phenopackets/#slots?

Is there somewhere else I should be looking, for an example of how the descriptions are being truncated when there is a dot?

**Comment by sierra-moxon** [comment]
I'm going to close this as done; please reopen if I got that wrong.  On looking through the phenopackets links above, I see longer descriptions not truncated at `.` for class descriptions.  For slot descriptions I see truncation but it is not based on the `.`

I also see that phenopackets "examples" are being added to the description field so we get some longer descriptions like this one: https://cmungall.github.io/linkml-phenopackets/Timestamp/   I'm going to make (or find) the tickets for showing examples as their own section in the classes and slots doc in docgen.  Likely there needs to be a bit of code written to extract the phenopackets examples from the description as well.
