### ISSUE TITLE
Whenever a slot or class is a mixin or abstract, on that documentation page, show a table of all descendant elements

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#928]

**Comment by sierra-moxon** [comment]
In linkml-model itself, https://linkml.io/linkml-model/docs/CommonMetadata/ is a mixin class that several other classes "inherit" from.  e.g.: Element https://linkml.io/linkml-model/docs/Element/

**Comment by sujaypatil96** [comment]
There is logic in the upstream jinja templates that display the table that is described in the requirements of this issue. See the `Mixin Usage` table section on this NMDC Schema mixin slot page as an example: https://microbiomedata.github.io/nmdc-schema/gold_identifiers/#mixin-usage

The logic that creates this table can be found in:
* class jinja: https://github.com/linkml/linkml/blob/main/linkml/generators/docgen/class.md.jinja2#L43-L51
* slot jinja: https://github.com/linkml/linkml/blob/main/linkml/generators/docgen/slot.md.jinja2#L35-L43

**Comment by sujaypatil96** [comment]
I think the functionality is in, per my knowledge @sierra-moxon, but I can create a comprehensive test case for this issue to illustrate the workings of the jinja.

**Comment by sierra-moxon** [comment]
closing as complete.
