### ISSUE TITLE
owlgen should allow the option of collapsing class into class_uri

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#933]
Currently owlgen uses definition_uri for the class URI. if class_uri is provided it's added as a mapping

In #932 @deepakunni3 says:

>  seem to recall that is how it was in 2020/2021. Was the change intentional or a bug in the owl generator?

I believe it has used definition_uri for some time, so not a bug or change in behavior

however, adding an option to collapse these would be sensible. Ideally it would be the default but we don't want to break code

**Comment by deepakunni3** [comment]
This is addressed via #1484 which provides a configurable way to bring equivalentClass axioms between class and class_uri, with the default behavior still staying the same.
