### ISSUE TITLE
Proposal: rename project from biolinkml to something non-biological

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#94]
A lot of people are confused about the distinction between biolinkml and biolink. Also from a marketing perspective, biolinkml can be used for anything, there is nothing biology-specific.

 1. Decide if renaming is worth the churn
 2. decide on a cool new name
 3. manage the renaming process

For 1, we can have an initial discussion here, and then collect votes if necessary

I have no ideas for 2, I have a history of bad names. I don't know if we need an initialization/acronym. A requirement is that it should be fairly googleable, it should be possible to make a nice name for pypi/python modules

For 3, We would register a new w3id. I think we would rename the github repo to preserve history. We would do a search and replace in this repo.

we would keep biolinkml in pypi indefinitely, and the w3id urls, and the existing docs, projects could switch to the new name at their leisure to minimize disruption. I think work on the biolinkml branch would freeze. We could provide tips for people to migrate. This is mostly

 - requirements.txt or similar
 - prefix declaration
 - imports of biolinkml:types

in fact we could continue to support the biolinkml prefix even with the new package

Anyone should feel free to state their opinion on 1 and 2 below, just information gathering for now

**Comment by nlharris** [comment]
since the renaming has already been decided, can we close this ticket, or are there still things to be accomplished as part of the rename? if the latter, a checklist of remaining tasks might be helpful.
