### ISSUE TITLE
fixer.remove_redundant_slot_usage RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#954]
> Traceback (most recent call last):
  File “/Users/MAM/Documents/gitrepos/sheets_and_friends/sheets_and_friends/lint_and_fix.py”, line 29, in <module>
    fixer.remove_redundant_slot_usage(s)
  File “/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/linkml/utils/schema_fixer.py”, line 174, in remove_redundant_slot_usage
    self.remove_redundant_slot_usage(schema, class_name)
  File “/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/linkml/utils/schema_fixer.py”, line 177, in remove_redundant_slot_usage
    for sn, slot in cls.slot_usage.items():
RuntimeError: dictionary keys changed during iteration

**Comment by cmungall** [comment]
See https://stackoverflow.com/questions/4081217/how-to-modify-list-entries-during-for-loop

**Comment by sierra-moxon** [comment]
closing as completed; please of course reopen if I got this wrong. 
https://github.com/linkml/linkml/pull/955
