### ISSUE TITLE
schemasheets examples for ICBO 2022

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#959]
https://github.com/linkml/linkml/tree/issue-959-schemasheets-icbo22

- [ ] Use https://github.com/linkml/linkml/blob/main/examples/tutorial/tutorial05/personinfo.yaml or similar/related file as input into linkml2sheets
  - [ ] will require templates
- workshop participants will be provided with a sample data file with some new fields that keeps it from validating against any of the personinfo.yaml versions in the examples/tutorial path
- will require participants to modify schema
- I will think of a modification pattern that is more suitable to shcemasheets that direct YAML editing
- We will need to discuss issues of round tripping, SOT (YAML, shared Google Sheet, checked-in TSVs...)

**Comment by turbomam** [comment]
linkml/linkml isn't liking my attempt to make schemasheets a dependency

I might move all of this to linkml/schemasheets

**Comment by sierra-moxon** [comment]
closing this for now; post-ICBO.  Please of course reopen if I got this wrong. :)
