### ISSUE TITLE
[ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/dist-packages/markupsafe/__init__.py)] while running `linkml-validate` command

### ISSUE THREAD

**Issue by capsulecorplab** [linkml/linkml#966]
**Describe the bug**
`linkml-validate` command throws an `ImportError` with default [linkml installation](https://linkml.io/linkml/intro/install.html#install-linkml) with `pip` while following [Tutorial 1](https://linkml.io/linkml/intro/tutorial01.html#). Appears to be missing `markupsafe` from list of dependencies.

```
$ linkml-validate -s personinfo.yaml data.yaml
Traceback (most recent call last):
  File "/usr/local/bin/linkml-validate", line 5, in <module>
    from linkml.validators.jsonschemavalidator import cli
  File "/usr/local/lib/python3.8/dist-packages/linkml/validators/__init__.py", line 2, in <module>
    from linkml.validators.sparqlvalidator import SparqlDataValidator
  File "/usr/local/lib/python3.8/dist-packages/linkml/validators/sparqlvalidator.py", line 13, in <module>
    from linkml.generators.sparqlgen import SparqlGenerator
  File "/usr/local/lib/python3.8/dist-packages/linkml/generators/sparqlgen.py", line 9, in <module>
    from jinja2 import Template
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/dist-packages/markupsafe/__init__.py)
```

**To Reproduce**
1. pip install linkml as per [install linkml](https://linkml.io/linkml/intro/install.html#install-linkml) instructions
2. create schema as per [your first schema](https://linkml.io/linkml/intro/tutorial01.html#your-first-schema)
3. create example data and run `linkml-validate` command on data as per [creating and validating data](https://linkml.io/linkml/intro/tutorial01.html#creating-and-validating-data)

**Expected behavior**
Should see no errors

**Desktop (if applicable, please complete the following information):**
 - OS: Ubuntu 20.04 (Focal)

**Additional context**
Probably just need to add `markupsafe` to list of dependencies in [pyproject.toml](https://github.com/linkml/linkml/blob/main/pyproject.toml#L89)

**Comment by cmungall** [comment]
Thanks for the report!

It seems others are having similar issues:

https://stackoverflow.com/questions/72191560/importerror-cannot-import-name-soft-unicode-from-markupsafe

Try this:

`pip install markupsafe==2.0.1`

We don't use markupsafe directly - this is transitively imported from jinja2.

There is more discussion here:

https://github.com/pallets/jinja/issues/1585

It's not clear to me yet whether we need to:

1. move to a newer version of jinja, and pin to that
2. pin markupsafe in our own dependencies

I'm not a fan of 2 as it could cause issues if people want to use linkml plus newer markupsafe...

**Comment by cmungall** [comment]
Actually, I think we just want to pin the jinja2 version in our pyproject.toml to be >= 3.0. That's what it is in our lock file

@capsulecorplab a better solution for you might be to to 

```
pip install jinja2==3.1.2
```

only pin markupsafe if you have a reason for using an older jinja2

**Comment by capsulecorplab** [comment]
Thank @cmungall! pip installing Jinja2 pinned at v3.1.2 seems to have fixed `linkml-validate`!
![Screenshot from 2022-09-18 10-23-17](https://user-images.githubusercontent.com/14095576/190917766-d09e0125-c090-45e3-b47d-50bb6ed72c7b.png)

**Comment by cse0001** [comment]
The fundamental issue with your question stems from a dependency management conflict between two software ecosystems. According to the error message, your 'markupsafe' was installed using 'pip' at the path `/usr/local/lib/python3.8/dist-packages/markupsafe`. The 'jinja2' that depends on it was installed using 'apt' at the path `/usr/lib/python3/dist-packages/jinja2`. The versions of the two are not compatible. In fact, there is a version of 'markupsafe' in the system that 'jinja2' correctly depends on, but the Python interpreter prioritizes the 'markupsafe' installed by 'pip', leading to this issue. There are typically two solutions to this problem: (1) Use 'pip' to uninstall markupsafe, and then reinstall it using 'apt', or uninstall 'jinja2' using 'apt' and reinstall it using 'pip'. (2) Use Python's imp module to customize the path and import the 'markupsafe' from the 'apt' path before importing 'jinja2'. An example is as follows:

    import imp
    path = ['/usr/lib/python3/dist-packages']
    fp, pathname, description = imp.find_module('markupsafe', path)
    imp.load_module("markupsafe", fp, pathname, description)

I have developed an automated tool to solve problems like yours and am currently collecting real-world issues. I would really appreciate it if you could reply.
