### ISSUE TITLE
Excel generator docs point to SQL DDL rather than Excel output

### ISSUE THREAD

**Issue by mogul** [linkml/linkml#978]
**Describe the bug**
The link to sample output from the Excel generator points to SQL DDL rather than a .xlsx file

**To Reproduce**
1. Go to https://linkml.io/linkml/generators/excel.html#example-output
2. Click on '[personinfo.xlsx](https://github.com/linkml/linkml/tree/main/examples/PersonSchema/personinfo/excel/personinfo.xlsx)'
4. See DDL for setting up an SQL DB

**Expected behavior**
See an Excel file ready to be filled in.

**Comment by cmungall** [comment]
Thanks! This was due to an old bug in the naming of files, it was fixed but we need to regenerate all the artefacts, we'll take care of this after our workshop next week

**Comment by sierra-moxon** [comment]
@joshmoore - thank you for your SQLDDL generator ticket (#985). :) Here is another ticket that expresses a similar (same) issue.  I'll tag you here on the earlier ticket so you can get notified when a fix comes in.

**Comment by sierra-moxon** [comment]
From @joshmoore:
```
Describe the bug

https://github.com/linkml/linkml/pull/608 updated the personinfo schema derived artifacts, but apparently the CREATE TABLE commands were stored in the personinfo.xlsx rather than the spreadsheet itself:

(linkml) /opt/linkml/examples/PersonSchema/personinfo $diff sqlschema/personinfo.sql excel/personinfo.xlsx
(linkml) /opt/linkml/examples/PersonSchema/personinfo $
```

**Comment by joshmoore** [comment]
Thanks, @sierra-moxon, and sorry for not checking first :wink:

**Comment by sujaypatil96** [comment]
See PR #996 for fix
