### ISSUE TITLE
linkml-lint exit codes

### ISSUE THREAD

**Issue by ialarmedalien** [linkml/linkml#981]
I would prefer for the linter to exit with code 0 if it did not find errors and just emitted warnings.

If others prefer that warnings lead to a non-zero exit code, having exit codes that correspond to warnings only vs errors would be good, e.g. 

warnings => exit 1
errors => exit 10
warnings + errors => exit 11

Alternatively, having a command line option to ignore warnings when assessing how to exit the linter would be good.

Motivation: I run linkml-lint as a GitHub action and was surprised when the linter failed after emitting warnings about non-canonical URIs in the prefixes section.

If these features are already available, can documentation be added so it's obvious for users?

**Comment by pkalita-lbl** [comment]
I think these are good suggestions, and they're consistent with features of other linters out there. 

In the meantime, if you aren't concerned about the results of the `canonical_prefixes` rule you could consider making a [custom configuration](https://linkml.io/linkml/schemas/linter.html#configuration) that disables that rule.
