### ISSUE TITLE
make video tutorials to accompany documented tutorial (and linkml-tutorial repo) 

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#984]
Each branch in linkml-tutorial repo, corresponds to a section of the documentated tutorial that could be augmented by a recorded video for this module (youtube is a good place for this, do we need a linkml youtube org?).

We could use the LinkML Workshop tutorial at ICBO 2022 as a guide for the branches/modules.

**Comment by nlharris** [comment]
See also https://github.com/linkml/linkml-tutorial
