### ISSUE TITLE
personinfo.xlsx contains SQL DDL

### ISSUE THREAD

**Issue by joshmoore** [linkml/linkml#985]
**Describe the bug**

#608 updated the personinfo schema derived artifacts, but apparently the `CREATE TABLE` commands were stored in the personinfo.xlsx rather than the spreadsheet itself:

```
(linkml) /opt/linkml/examples/PersonSchema/personinfo $diff sqlschema/personinfo.sql excel/personinfo.xlsx
(linkml) /opt/linkml/examples/PersonSchema/personinfo $
```

**Comment by sierra-moxon** [comment]
Closing as duplicate of #978
