### ISSUE TITLE
Conditional/rules support in jsonschema generator

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#989]
### Discussed in https://github.com/linkml/linkml/discussions/988

Support advanced syntax as seen [here](https://linkml.io/linkml/schemas/advanced.html?highlight=conditional#unions-as-ranges) in JSONSchema generator.

- [ ] rules
  - [ ] preconditions/postconditions 
     - [ ] any_of
  - [ ] patterns
- [ ] defining_slots
- [ ] union ranges

**Comment by sierra-moxon** [comment]
+4 upvotes from teh discussion referenced above.

**Comment by mogul** [comment]
(Some of those are probably from other people in my team.)

**Comment by mogul** [comment]
Are there existing examples of conditional/rules support in other generators to crib from?

**Comment by mogul** [comment]
Hey there, a gentle ping... Can we get a sense of where this is in your priorities, and/or where we can look for examples to base a PR off of?

**Comment by cmungall** [comment]
Fully supporting all of the linkml-model extensions introduced in LinkML 1.3 is a high priority

Ideally we would tackle #1033 first, we will have a few joint coding sessions where we try and tackle this over the next few weeks. This should actually make tackling schema composition much easier. It's not so much work overall but factoring in other projects I would say 3-4 weeks.

We are open to receiving PRs before. Or if there is a sub-profile that is of useful (the most common pattern I have seen is implementing a simple union of atomic ranges) then that could be tackled separately. But my preference would be to tackle the underpinnings first.

**Comment by ialarmedalien** [comment]
It would be very useful to have documentation somewhere on what linkml syntax is and isn't supported when converting to JSONschema and by extension, when validating data against a linkml schema.

Ideally this documentation would be in a central location (e.g. a list of tags and whether or not they are correctly converted to JSONschema) as it is not always clear from the documentation, and it's also not always easy to find the relevant section of documentation if it is specified somewhere.

If certain linkml syntaxes are not supported, users may prefer to encode their schema using JSONschema to allow fuller validation of their data.
