### ISSUE TITLE
Generator does not handle case where schema parameter is a SchemaDefinition

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#99]
From the __init__:

                schema: Union[str, TextIO, SchemaDefinition, "Generator"],

the code handles the final and the first two cases, but not where someone passes in a schema object directly:

https://github.com/biolink/biolinkml/blob/3fb853b6302efa6926dc2a6efce7fc5c658ca69b/biolinkml/utils/generator.py#L75-L102

**Comment by sierra-moxon** [comment]
I see schema as a possible input to SchemaLoader now in the generator.py, so I am closing it as completed.  Please of course reopen if I am incorrect.
