### ISSUE TITLE
unexpected `_if_missing` annotations appear in gen-doc pages

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml#993]
**Describe the bug**
`_if_missing` appears as an annotation on gen-doc pages. How is it related to FAQ: https://github.com/linkml/linkml/blob/main/docs/faq/tools.md#what-does-_if_missing-mean-in-my-json-output?

We observe this on the MIxS and NMDC documentation pages. Example: https://microbiomedata.github.io/nmdc-schema/biotic_relationship/#annotations

**Comment by cmungall** [comment]
it looks like we have code to guard against this now? Maybe nmdc is using older code?

I see

```
| property | value |
| --- | --- |
{% for a in element.annotations -%}
{%- if a|string|first != '_' -%}
| {{ a }} | {{ element.annotations[a].value }} |
```

of course this shouldn't be necessary in the first place

**Comment by nlharris** [comment]
@sujaypatil96 is NMDC using the latest code?

**Comment by sierra-moxon** [comment]
I no longer see the `_if_missing` string.  closing as complete :)
